# Generated by Django 6.0.4 on 2026-07-01 08:38

from django.db import migrations, models


def blank_national_ids_to_null(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    Patient.objects.filter(national_id='').update(national_id=None)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(blank_national_ids_to_null, noop),
    ]
