# Generated by Django 6.0.4 on 2026-07-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_national_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='registration_source',
            field=models.CharField(choices=[('self', 'Self registration'), ('homecare', 'Homecare'), ('hospital', 'Hospital'), ('clinic', 'Clinic'), ('pharmacy', 'Pharmacy'), ('radiology', 'Radiology'), ('lab', 'Laboratory'), ('doctor', 'Doctor'), ('other', 'Other')], db_index=True, default='self', help_text='How the patient first got registered on AdhereMed.', max_length=20),
        ),
    ]
