# Generated by Django 6.0.4 on 2026-05-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('received', 'Received'), ('partial', 'Partially Received'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='draft', max_length=20),
        ),
    ]
