# Generated by Django 6.0.4 on 2026-05-21 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0009_increase_lat_lng_max_digits_to_30'),
        ('purchase_orders', '0002_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='pharmacy_profile.branch'),
        ),
    ]
