# Generated by Django 6.0.4 on 2026-09-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0003_add_branch_to_purchaseorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Recorded as an expense; NOT included in total_cost', max_digits=12),
        ),
    ]
