# Generated by Django 6.0.4 on 2026-09-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0004_purchaseorder_shipping_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='proof_image',
            field=models.ImageField(blank=True, help_text='Optional proof image (signed delivery note, receipt photo, etc.)', null=True, upload_to='po_proofs/'),
        ),
    ]
