# Generated by Django 6.0.4 on 2026-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('tenant_admin', 'Tenant Admin'), ('doctor', 'Doctor'), ('clinical_officer', 'Clinical Officer'), ('dentist', 'Dentist'), ('nurse', 'Nurse'), ('midwife', 'Midwife'), ('lab_tech', 'Lab Technologist'), ('radiologist', 'Radiologist'), ('pharmacist', 'Pharmacist'), ('pharmacy_tech', 'Pharmacy Technician'), ('cashier', 'Cashier'), ('receptionist', 'Receptionist'), ('homecare_admin', 'Homecare Admin'), ('caregiver', 'Caregiver'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
