# Generated by Django 6.0.4 on 2026-05-09 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin',
            field=models.CharField(blank=True, help_text='Unique 6-digit PIN used to acknowledge sensitive actions.', max_length=12, null=True, unique=True),
        ),
    ]
