# Generated by Django 6.0.4 on 2026-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Laboratory')], max_length=20),
        ),
    ]
