# Generated by Django 6.0.4 on 2026-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Laboratory'), ('homecare', 'Homecare')], max_length=20),
        ),
    ]
