# Generated by Django 6.0.4 on 2026-07-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_latitude_tenant_longitude_tenant_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='billing_grace_until',
            field=models.DateField(blank=True, help_text='Access is permitted despite overdue bills until this date (superadmin-granted grace / extended suspension).', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_suspended',
            field=models.BooleanField(default=False, help_text='Superadmin hard-lock of API access due to unpaid/overdue bills.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='suspension_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
