# Generated by Django 6.0.4 on 2026-09-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_billing_grace_until_tenant_billing_suspended_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='type',
            field=models.CharField(choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy'), ('lab', 'Laboratory'), ('homecare', 'Homecare'), ('radiology_center', 'Radiology Center'), ('clinic', 'Clinic'), ('inventory', 'Inventory / Warehouse')], max_length=20),
        ),
    ]
