# Generated by Django 6.0.4 on 2026-05-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0003_pharmacyprescription_pharmacyprescriptionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='refills',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of times this prescription can be refilled'),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='schedule',
            field=models.CharField(blank=True, help_text='e.g., Morning, Afternoon & Night / Before meals', max_length=100),
        ),
    ]
