# Generated by Django 6.0.4 on 2026-07-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_name', models.CharField(default='AdhereMed', help_text='Friendly From name shown to recipients.', max_length=120)),
                ('from_email', models.EmailField(default='info@adheremed.co', help_text='Address used as the From / login address.', max_length=254)),
                ('username', models.CharField(default='info@adheremed.co', help_text='IMAP/SMTP username.', max_length=255)),
                ('password', models.CharField(blank=True, default='', help_text='Plain-text mailbox password. Stored at rest.', max_length=512)),
                ('imap_host', models.CharField(default='mail.adheremed.co', max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(default='mail.adheremed.co', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True, help_text='If false, Django settings defaults are used instead.')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_ok', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail configuration',
                'verbose_name_plural': 'Mail configuration',
            },
        ),
        migrations.AlterField(
            model_name='coinpackage',
            name='currency',
            field=models.CharField(default='KES', max_length=3),
        ),
    ]
