# Generated by Django 6.0.4 on 2026-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment', 'Appointment'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('home_collection', 'Home Collection'), ('billing', 'Billing'), ('system', 'System'), ('dose_reminder', 'Dose Reminder'), ('dose_missed', 'Dose Missed'), ('escalation', 'Escalation'), ('teleconsult', 'Teleconsult'), ('insurance_claim', 'Insurance Claim'), ('caregiver_update', 'Caregiver Update'), ('stock_alert', 'Stock Alert'), ('consent', 'Consent')], max_length=20),
        ),
    ]
