# Generated by Django 6.0.4 on 2026-08-03 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('triage', '0002_triage_alcohol_use_triage_allergies_confirmed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='allergies_confirmed',
            field=models.JSONField(blank=True, default=list, help_text='Confirmed allergies'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='assessment',
            field=models.TextField(blank=True, help_text='Clinical assessment narrative'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='clinical_decision_making',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='differential_diagnosis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='consultation',
            name='disposition',
            field=models.CharField(choices=[('discharge', 'Discharge'), ('referral', 'Referral'), ('admission', 'Admission'), ('observation', 'Observation'), ('transfer', 'Transfer'), ('left_ama', 'Left Against Medical Advice'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='draft_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultation',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='medication_history',
            field=models.JSONField(blank=True, default=list, help_text='Reconciled medications'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='past_medical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='review_of_systems',
            field=models.JSONField(blank=True, default=dict, help_text='ROS checklist by system'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='social_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('signed', 'Signed'), ('locked', 'Locked')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='consultation',
            name='surgical_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='triage',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='triage.triage'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ConsultationAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_addenda', to=settings.AUTH_USER_MODEL)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='consultations.consultation')),
            ],
            options={
                'ordering': ['signed_at'],
            },
        ),
    ]
