# Generated by Django 6.0.4 on 2026-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque'), ('insurance', 'Insurance'), ('credit', 'Credit'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
