# Generated by Django 6.0.4 on 2026-09-20 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0002_salesorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='delivery_place_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
