# Generated by Django 6.0.4 on 2026-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_orders', '0003_salesorder_delivery_lat_salesorder_delivery_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery/shipping cost charged to the customer', max_digits=12),
        ),
    ]
