# Generated by Django 6.0.4 on 2026-05-02 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0004_add_branch_model'),
        ('pos', '0002_customer_postransaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='pharmacy_profile.branch'),
        ),
    ]
