# Generated by Django 6.0.4 on 2026-05-13 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_customer_loyalty_joined_at_customer_loyalty_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partial_paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partial_payment_method', models.CharField(choices=[('none', 'None'), ('cash', 'Cash'), ('card', 'Card'), ('mpesa', 'M-Pesa'), ('insurance', 'Insurance')], default='none', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partially Paid'), ('settled', 'Settled'), ('overdue', 'Overdue')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_record', to='pos.postransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
