# Generated by Django 6.0.4 on 2026-04-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_tenant_id', models.IntegerField(help_text='ID of the hospital tenant')),
                ('patient_user_id', models.IntegerField(help_text='ID of the patient user')),
                ('prescription_ref', models.CharField(max_length=100)),
                ('items', models.JSONField(help_text='List of medication items with dosage info')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('selected_pharmacy_tenant_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_tenant_id', models.IntegerField()),
                ('pharmacy_name', models.CharField(max_length=255)),
                ('items_pricing', models.JSONField(help_text='Per-item pricing: [{medication_id, name, qty, unit_price, total}]')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_available', models.BooleanField(default=False)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valid_until', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='exchange.prescriptionexchange')),
            ],
            options={
                'ordering': ['total_cost'],
            },
        ),
    ]
