# Generated by Django 6.0.4 on 2026-04-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_patientorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrderExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_tenant_id', models.IntegerField(help_text='ID of the hospital tenant that created the order')),
                ('source_tenant_name', models.CharField(blank=True, max_length=255)),
                ('ordering_doctor_name', models.CharField(blank=True, max_length=255)),
                ('ordering_doctor_user_id', models.IntegerField(blank=True, null=True)),
                ('patient_user_id', models.IntegerField(help_text='ID of the patient user')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('tests', models.JSONField(help_text='[{test_name, code, specimen_type, instructions}]')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('stat', 'STAT')], default='routine', max_length=10)),
                ('clinical_notes', models.TextField(blank=True)),
                ('is_home_collection', models.BooleanField(default=False)),
                ('collection_address', models.TextField(blank=True)),
                ('lab_tenant_id', models.IntegerField(blank=True, null=True)),
                ('lab_tenant_name', models.CharField(blank=True, max_length=255)),
                ('results', models.JSONField(blank=True, help_text='[{test_name, result_value, unit, is_abnormal, comments}]', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('sample_collected', 'Sample Collected'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
