# Generated by Django 6.0.4 on 2026-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_laborderexchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionexchange',
            name='source_tenant_type',
            field=models.CharField(default='hospital', help_text="'hospital' or 'homecare' — origin of this prescription", max_length=20),
        ),
    ]
