# Generated by Django 6.0.4 on 2026-05-07 05:59

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_alter_tenant_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_per_unit', models.PositiveIntegerField(default=1000, help_text='How many requests are billed as one cost unit.')),
                ('unit_cost', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Cost per `requests_per_unit` block.', max_digits=12)),
                ('currency', models.CharField(default='KSH', max_length=8)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_rates_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_days', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['tenant', 'date'], name='usage_billi_tenant__89fea9_idx')],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('requests_per_unit', models.PositiveIntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=14)),
                ('currency', models.CharField(default='KSH', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled')], default='ISSUED', max_length=12)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_bills', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('tenant', 'year', 'month')},
            },
        ),
    ]
