# Generated by Django 6.0.4 on 2026-05-11 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage_billing', '0002_doctorcommissionrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyusage',
            name='lab_request_count',
            field=models.PositiveIntegerField(default=0, help_text='Subset of request_count that hit /api/lab/* endpoints.'),
        ),
    ]
