# Generated by Django 6.0.4 on 2026-05-14 13:26

import django.db.models.deletion
import usage_billing.referral_models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_latitude_tenant_longitude_tenant_place_name'),
        ('usage_billing', '0003_dailyusage_lab_request_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(db_index=True, default=usage_billing.referral_models._generate_referral_code, max_length=12, unique=True)),
                ('coin_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_redeemed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('referral_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_profile', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-coin_balance'],
            },
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earned', 'Earned'), ('redeemed', 'Redeemed'), ('bonus', 'Bonus'), ('adjustment', 'Adjustment')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reason', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tenants.tenant')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='usage_billing.referralprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired')], default='active', max_length=12)),
                ('bonus_awarded', models.BooleanField(default=False)),
                ('tracked_requests', models.PositiveIntegerField(default=0)),
                ('coins_from_usage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='tenants.tenant')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('referrer', 'referred')},
            },
        ),
    ]
