# Generated by Django 6.0.4 on 2026-07-03 09:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_billing_grace_until_tenant_billing_suspended_and_more'),
        ('usage_billing', '0007_alter_monthlybill_status_mpesatransaction_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybill',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Coupons / offers applied to reduce the amount owed on this bill.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='monthlybill',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('CANCELLED', 'Cancelled'), ('WAIVED', 'Waived')], default='ISSUED', max_length=12),
        ),
    ]
