# Generated by Django 6.0.4 on 2026-04-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], default='available', max_length=20)),
            ],
            options={
                'ordering': ['ward', 'bed_number'],
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('general', 'General'), ('icu', 'ICU'), ('maternity', 'Maternity'), ('pediatric', 'Pediatric'), ('surgical', 'Surgical'), ('emergency', 'Emergency'), ('private', 'Private')], max_length=20)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('discharge_summary', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('transferred', 'Transferred')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admitting_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_made', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
                ('bed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='wards.bed')),
            ],
            options={
                'ordering': ['-admission_date'],
            },
        ),
        migrations.AddField(
            model_name='bed',
            name='ward',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward'),
        ),
        migrations.AlterUniqueTogether(
            name='bed',
            unique_together={('ward', 'bed_number')},
        ),
    ]
