# Generated by Django 6.0.4 on 2026-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(db_index=True, max_length=255)),
                ('brand_names', models.JSONField(blank=True, default=list)),
                ('category', models.CharField(choices=[('analgesic', 'Analgesic / Pain Reliever'), ('antibiotic', 'Antibiotic'), ('antifungal', 'Antifungal'), ('antiviral', 'Antiviral'), ('antiparasitic', 'Antiparasitic'), ('antimalarial', 'Antimalarial'), ('antihypertensive', 'Antihypertensive'), ('antidiabetic', 'Antidiabetic'), ('antihistamine', 'Antihistamine'), ('antacid', 'Antacid / GI'), ('cardiovascular', 'Cardiovascular'), ('respiratory', 'Respiratory'), ('cns', 'Central Nervous System'), ('hormone', 'Hormonal'), ('vitamin', 'Vitamin / Supplement'), ('vaccine', 'Vaccine'), ('dermatological', 'Dermatological'), ('ophthalmic', 'Ophthalmic'), ('oncology', 'Oncology'), ('immunosuppressant', 'Immunosuppressant'), ('nsaid', 'NSAID'), ('other', 'Other')], db_index=True, max_length=30)),
                ('subcategory', models.CharField(blank=True, max_length=100)),
                ('dosage_form', models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('cream', 'Cream'), ('ointment', 'Ointment'), ('drops', 'Drops'), ('inhaler', 'Inhaler'), ('suppository', 'Suppository'), ('suspension', 'Suspension'), ('powder', 'Powder'), ('gel', 'Gel'), ('patch', 'Patch'), ('lozenge', 'Lozenge'), ('spray', 'Spray'), ('solution', 'Solution'), ('other', 'Other')], max_length=20)),
                ('strength', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('controlled_substance_class', models.CharField(blank=True, help_text='e.g. Schedule II', max_length=10)),
                ('side_effects', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['generic_name'],
                'indexes': [models.Index(fields=['generic_name', 'category'], name='medications_generic_06dd2a_idx')],
            },
        ),
    ]
