# Generated by Django 6.0.4 on 2026-04-09 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='controlled_substance_class',
            field=models.CharField(blank=True, help_text='e.g. Schedule II', max_length=20),
        ),
    ]
