# Generated by Django 6.0.4 on 2026-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_alter_medication_controlled_substance_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='abbreviation',
            field=models.CharField(blank=True, db_index=True, help_text='Short code/abbreviation, e.g. PCM, AMOX, RHZE', max_length=20),
        ),
    ]
