# Generated by Django 6.0.4 on 2026-05-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0003_medication_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='interactions',
            field=models.TextField(blank=True, help_text='Free-text interaction notes'),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], default='moderate', max_length=20)),
                ('description', models.TextField(help_text='What happens when these drugs interact')),
                ('clinical_advice', models.TextField(blank=True, help_text='Recommended action / monitoring')),
                ('source', models.CharField(blank=True, help_text='Reference / citation', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('drug_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_a', to='medications.medication')),
                ('drug_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_b', to='medications.medication')),
            ],
            options={
                'ordering': ['-severity', 'drug_a__generic_name'],
                'indexes': [models.Index(fields=['drug_a', 'drug_b'], name='medications_drug_a__7353ff_idx'), models.Index(fields=['severity'], name='medications_severit_5ce79f_idx')],
                'constraints': [models.UniqueConstraint(fields=('drug_a', 'drug_b'), name='uniq_drug_pair')],
            },
        ),
    ]
