# Generated by Django 6.0.4 on 2026-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0004_medication_interactions_druginteraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, help_text='KEMSA product code, e.g. PM05ASA003', max_length=30),
        ),
    ]
