# Generated by Django 6.0.4 on 2026-05-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarepatient',
            name='additional_caregivers',
            field=models.ManyToManyField(blank=True, help_text='Additional caregivers / nurses assigned to this patient.', related_name='secondary_patients', to='homecare.caregiver'),
        ),
    ]
