# Generated by Django 6.0.4 on 2026-05-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0002_homecarepatient_additional_caregivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarepatient',
            name='address_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='homecarepatient',
            name='address_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
