# Generated by Django 6.0.4 on 2026-05-08 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0003_homecarepatient_address_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomecareAllergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('common_symptoms', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('seed', 'Seeded'), ('custom', 'Custom')], db_index=True, default='custom', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homecare allergy',
                'verbose_name_plural': 'Homecare allergies',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_homecare_allergy_name')],
            },
        ),
        migrations.CreateModel(
            name='HomecareDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, db_index=True, max_length=40)),
                ('icd_code', models.CharField(blank=True, db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('seed', 'Seeded'), ('custom', 'Custom')], db_index=True, default='custom', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homecare diagnosis',
                'verbose_name_plural': 'Homecare diagnoses',
                'ordering': ['category', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uniq_homecare_diagnosis_name')],
            },
        ),
    ]
