# Generated by Django 6.0.4 on 2026-05-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0004_homecareallergy_homecarediagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarepatient',
            name='assigned_doctor_info',
            field=models.JSONField(blank=True, default=dict, help_text='Free-form doctor info when no system user exists (name, specialization, qualification, phone, email, hospital, …).'),
        ),
    ]
