# Generated by Django 6.0.4 on 2026-05-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0005_homecarepatient_assigned_doctor_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecarepatient',
            name='id_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homecarepatient',
            name='id_type',
            field=models.CharField(blank=True, help_text='national_id | alien_id | passport | driving_license | birth_cert | military_id | other', max_length=30),
        ),
        migrations.AddField(
            model_name='homecarepatient',
            name='nationality',
            field=models.CharField(blank=True, default='KE', help_text='ISO-3166-1 alpha-2 country code (e.g. KE, UG, US).', max_length=10),
        ),
    ]
