# Generated by Django 6.0.4 on 2026-05-09 12:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0006_homecarepatient_id_number_homecarepatient_id_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, db_index=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('action', 'Custom Action')], db_index=True, max_length=16)),
                ('object_type', models.CharField(db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=512)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('payload_diff', models.JSONField(blank=True, default=dict)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='homecare_au_object__a3da79_idx'), models.Index(fields=['actor_user_id', '-created_at'], name='homecare_au_actor_u_27ed20_idx')],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device_type', models.CharField(choices=[('oximeter', 'Pulse Oximeter'), ('bp_monitor', 'Blood Pressure Monitor'), ('glucometer', 'Glucometer'), ('thermometer', 'Thermometer'), ('oxygen', 'Oxygen Concentrator'), ('nebulizer', 'Nebulizer'), ('bed', 'Hospital Bed'), ('wheelchair', 'Wheelchair'), ('walker', 'Walker / Crutches'), ('suction', 'Suction Machine'), ('ventilator', 'Ventilator'), ('infusion_pump', 'Infusion Pump'), ('ecg', 'ECG Monitor'), ('other', 'Other')], db_index=True, default='other', max_length=24)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('asset_tag', models.CharField(blank=True, db_index=True, help_text='Internal asset tag / barcode.', max_length=64)),
                ('qr_code', models.CharField(blank=True, help_text='QR payload for scanning.', max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned to Patient'), ('maintenance', 'In Maintenance'), ('repair', 'Needs Repair'), ('retired', 'Retired'), ('lost', 'Lost / Missing')], db_index=True, default='available', max_length=16)),
                ('location', models.CharField(blank=True, help_text='Storage location when not assigned.', max_length=255)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('warranty_expiry', models.DateField(blank=True, null=True)),
                ('last_maintenance_at', models.DateTimeField(blank=True, null=True)),
                ('next_maintenance_due', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='homecare/devices/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_devices', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecare_device_assignments', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='homecare.device')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='homecare.homecarepatient')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('routine', 'Routine Service'), ('calibration', 'Calibration'), ('repair', 'Repair'), ('inspection', 'Safety Inspection')], default='routine', max_length=16)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=16)),
                ('scheduled_at', models.DateTimeField()),
                ('performed_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by_name', models.CharField(blank=True, max_length=255)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('next_due_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_events', to='homecare.device')),
                ('performed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecare_maintenance_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
    ]
