# Generated by Django 6.0.4 on 2026-05-09 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0007_auditevent_device_deviceassignment_devicemaintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consent',
            name='signature_data_url',
            field=models.TextField(blank=True, help_text='Base64 data-URL of the captured signature image (PNG).'),
        ),
        migrations.AddField(
            model_name='consent',
            name='signature_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of (scope|patient|signature_data_url|signed_at) for tamper detection.', max_length=128),
        ),
        migrations.AddField(
            model_name='consent',
            name='signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='signed_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consent',
            name='signed_by_relationship',
            field=models.CharField(blank=True, help_text='self / parent / guardian / next-of-kin etc.', max_length=80),
        ),
        migrations.AddField(
            model_name='consent',
            name='signed_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consent',
            name='signed_user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(db_index=True, max_length=120)),
                ('drug_b', models.CharField(db_index=True, max_length=120)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], db_index=True, default='moderate', max_length=20)),
                ('summary', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('references', models.JSONField(blank=True, default=list, help_text='[{label, url}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['drug_a', 'drug_b'],
                'indexes': [models.Index(fields=['drug_a', 'drug_b'], name='homecare_dr_drug_a_be64b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('drug_a', 'drug_b'), name='uniq_drug_interaction_pair')],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionSafetyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('allergy', 'Allergy Conflict'), ('interaction', 'Drug Interaction'), ('duplicate', 'Duplicate Therapy')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('minor', 'Minor'), ('moderate', 'Moderate'), ('major', 'Major'), ('contraindicated', 'Contraindicated')], db_index=True, default='moderate', max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('drugs', models.JSONField(blank=True, default=list, help_text='Drug names involved.')),
                ('overridden', models.BooleanField(default=False)),
                ('overridden_at', models.DateTimeField(blank=True, null=True)),
                ('override_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homecare_overridden_alerts', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_alerts', to='homecare.homecareprescription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
