# Generated by Django 6.0.4 on 2026-05-09 16:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0008_consent_signature_data_url_consent_signature_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarePathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, help_text='SNOMED CT or local code identifying the condition / pathway.', max_length=64)),
                ('code_system', models.CharField(blank=True, default='http://snomed.info/sct', max_length=64)),
                ('condition_label', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('default_duration_days', models.PositiveIntegerField(default=14)),
                ('goals', models.JSONField(blank=True, default=list, help_text='List of plain-text goals.')),
                ('medication_orders', models.JSONField(blank=True, default=list, help_text='[{medication_name, dose, route, times_of_day, frequency_cron, duration_days, instructions, requires_caregiver}]')),
                ('vital_targets', models.JSONField(blank=True, default=dict, help_text='{spo2_min: 94, hr_max: 110, ...} for monitoring/alerting.')),
                ('tasks', models.JSONField(blank=True, default=list, help_text='[{title, day_offset, category}] standing tasks.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarePathwayEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('withdrawn', 'Withdrawn')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_by_user_id', models.IntegerField(blank=True, null=True)),
                ('target_end_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('outcome_notes', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='homecare.carepathway')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathway_enrollments', to='homecare.homecarepatient')),
                ('treatment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pathway_enrollments', to='homecare.treatmentplan')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['patient', 'status'], name='homecare_ca_patient_b19fb1_idx')],
            },
        ),
    ]
