# Generated by Django 6.0.4 on 2026-05-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0009_carepathway_carepathwayenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='category',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('hca', 'Health Care Assistant')], db_index=True, default='nurse', help_text='Caregiver tier: registered Nurse or Health Care Assistant.', max_length=10),
        ),
    ]
