# Generated by Django 6.0.4 on 2026-05-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0010_caregiver_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, help_text='Optional friendly From name. Defaults to the tenant name.', max_length=120)),
                ('email', models.EmailField(help_text='Mailbox address used as From / login.', max_length=254)),
                ('imap_host', models.CharField(max_length=255)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('imap_use_ssl', models.BooleanField(default=True)),
                ('smtp_host', models.CharField(max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('smtp_use_ssl', models.BooleanField(default=True)),
                ('username', models.CharField(help_text='IMAP/SMTP username.', max_length=255)),
                ('password', models.CharField(blank=True, help_text='Plain-text mailbox password. Stored at rest in the tenant DB.', max_length=512)),
                ('is_active', models.BooleanField(default=True, help_text='If false, the global default mail config is used.')),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_ok', models.BooleanField(default=False)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mail account',
                'verbose_name_plural': 'Mail account',
            },
        ),
    ]
