# Generated by Django 6.0.4 on 2026-05-10 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0011_mailaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='last_generation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_generation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_generation_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_generation_by_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_generation_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicationschedule',
            name='last_generation_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
