# Generated by Django 6.0.4 on 2026-05-10 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0012_medicationschedule_last_generation_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doseevent',
            name='administered_by_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='doseevent',
            name='administered_by_role',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='doseevent',
            name='administered_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doseevent',
            name='audit_log',
            field=models.JSONField(blank=True, default=list, help_text='History of status changes with actor & reason.'),
        ),
        migrations.AddField(
            model_name='doseevent',
            name='auto_missed',
            field=models.BooleanField(default=False, help_text='Set when system auto-marks as missed.'),
        ),
        migrations.AddField(
            model_name='doseevent',
            name='reason',
            field=models.TextField(blank=True, help_text='Reason for skip / not given / edit.'),
        ),
        migrations.AddField(
            model_name='doseevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='doseevent',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('taken', 'Documented'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('refused', 'Refused'), ('not_given', 'Not given')], default='pending', max_length=20),
        ),
    ]
