# Generated by Django 6.0.4 on 2026-05-10 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0013_doseevent_administered_by_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='visit_pin',
            field=models.CharField(blank=True, default='', help_text='Numeric PIN entered by caregiver to confirm check-in / check-out.', max_length=10),
        ),
        migrations.AddField(
            model_name='caregiverschedule',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When caregiver acknowledged the shift at check-in.', null=True),
        ),
        migrations.AddField(
            model_name='caregiverschedule',
            name='auto_missed_at',
            field=models.DateTimeField(blank=True, help_text='Set when system auto-marked this shift as Missed.', null=True),
        ),
        migrations.AddField(
            model_name='caregiverschedule',
            name='reassigned_to',
            field=models.ForeignKey(blank=True, help_text='New schedule that replaced this missed shift, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassigned_from', to='homecare.caregiverschedule'),
        ),
        migrations.AddField(
            model_name='caregiverschedule',
            name='reassignment_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='caregiverschedule',
            name='reassignment_requested',
            field=models.BooleanField(default=False),
        ),
    ]
