# Generated by Django 6.0.4 on 2026-07-02 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0014_caregiver_visit_pin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDataSharing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_shared', models.BooleanField(default=True, help_text='Master switch — turn off to hide everything from the patient.')),
                ('share_profile', models.BooleanField(default=True)),
                ('share_care_team', models.BooleanField(default=True)),
                ('share_vitals', models.BooleanField(default=True)),
                ('share_medications', models.BooleanField(default=True)),
                ('share_treatment_plan', models.BooleanField(default=True)),
                ('share_notes', models.BooleanField(default=True)),
                ('share_adherence', models.BooleanField(default=True)),
                ('share_escalations', models.BooleanField(default=True)),
                ('share_consents', models.BooleanField(default=True)),
                ('share_documents', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sharing', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Patient data sharing',
                'verbose_name_plural': 'Patient data sharing',
            },
        ),
    ]
