# Generated by Django 6.0.4 on 2026-07-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0015_patientdatasharing'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='currency',
            field=models.CharField(default='KES', max_length=8),
        ),
        migrations.AddField(
            model_name='device',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='default_hire_period',
            field=models.CharField(choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month')], default='daily', max_length=12),
        ),
        migrations.AddField(
            model_name='device',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Refundable security deposit collected on hire.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_rentable',
            field=models.BooleanField(default=True, help_text='Whether this device can be hired out to patients.'),
        ),
        migrations.AddField(
            model_name='device',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='weekly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='hire_period',
            field=models.CharField(blank=True, choices=[('hourly', 'Per Hour'), ('daily', 'Per Day'), ('weekly', 'Per Week'), ('monthly', 'Per Month')], max_length=12),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='hire_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='total_charged',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
