# Generated by Django 6.0.4 on 2026-07-02 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0016_device_currency_device_daily_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=1, help_text='Flag as "almost out" when available ≤ this.'),
        ),
        migrations.AddField(
            model_name='device',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Total units of this item owned.'),
        ),
        migrations.AddField(
            model_name='device',
            name='quantity_available',
            field=models.PositiveIntegerField(default=1, help_text='Units currently available for hire.'),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='facility_name',
            field=models.CharField(blank=True, help_text='Name of the external homecare / facility hiring the device.', max_length=255),
        ),
        migrations.AddField(
            model_name='deviceassignment',
            name='hire_to_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('facility', 'Facility / Organisation')], db_index=True, default='patient', max_length=12),
        ),
        migrations.AlterField(
            model_name='deviceassignment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_assignments', to='homecare.homecarepatient'),
        ),
    ]
