# Generated by Django 6.0.4 on 2026-07-02 15:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0017_device_low_stock_threshold_device_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationschedule',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional charge per administered dose, used for patient billing.', max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='MedicalSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Nasogastric feeding tube (Fr 16)', max_length=255)),
                ('category', models.CharField(choices=[('feeding', 'Feeding / Nutrition'), ('catheter', 'Catheter / Urinary'), ('wound', 'Wound Care / Dressing'), ('iv', 'IV / Infusion'), ('respiratory', 'Respiratory'), ('incontinence', 'Incontinence'), ('diabetic', 'Diabetic'), ('hygiene', 'PPE / Hygiene'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit', models.CharField(blank=True, default='unit', help_text='unit, pack, box, roll, …', max_length=40)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('supplied_at', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, help_text='Manufacturer expiry of the product.', null=True)),
                ('max_use_days', models.PositiveIntegerField(blank=True, help_text='How many days the item can safely be used once in service.', null=True)),
                ('replace_due', models.DateField(blank=True, help_text='When the item should be replaced (auto from supplied + lifespan).', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('billable', models.BooleanField(default=True, help_text='Include in the patient bill.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Medical supply',
                'verbose_name_plural': 'Medical supplies',
                'ordering': ['-supplied_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(editable=False, max_length=32, unique=True)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('as_of', models.DateTimeField(default=django.utils.timezone.now, help_text='Charges computed up to this moment.')),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('line_items', models.JSONField(blank=True, default=list, help_text='[{kind, label, qty, unit, rate, amount}]')),
                ('care_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('equipment_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('supplies_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('medication_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('partial', 'Partially Paid'), ('paid', 'Paid'), ('void', 'Void')], db_index=True, default='issued', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('generated_by_user_id', models.IntegerField(blank=True, null=True)),
                ('generated_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='homecare.homecarepatient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('per_visit', 'Per Visit'), ('day_time', 'Day Shift (Day-time)'), ('night_time', 'Night Shift (Night-time)')], db_index=True, default='daily', max_length=16)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Manually-set price per period / visit.', max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by_user_id', models.IntegerField(blank=True, null=True)),
                ('created_by_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='homecare.homecarepatient')),
            ],
            options={
                'ordering': ['-is_active', '-start_date'],
                'indexes': [models.Index(fields=['patient', 'is_active'], name='homecare_ca_patient_602cab_idx')],
            },
        ),
        migrations.CreateModel(
            name='PatientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=8)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('insurance', 'Insurance'), ('other', 'Other')], db_index=True, default='cash', max_length=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by_user_id', models.IntegerField(blank=True, null=True)),
                ('received_by_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='homecare.patientbill')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='homecare.homecarepatient')),
            ],
            options={
                'ordering': ['-paid_at'],
                'indexes': [models.Index(fields=['patient', 'paid_at'], name='homecare_pa_patient_6379e8_idx')],
            },
        ),
    ]
