# Generated by Django 6.0.4 on 2026-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0018_medicationschedule_unit_cost_medicalsupply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careplan',
            name='auto_bill',
            field=models.BooleanField(db_index=True, default=True, help_text='Automatically generate a bill at the end of each period.'),
        ),
        migrations.AddField(
            model_name='careplan',
            name='last_auto_billed_at',
            field=models.DateTimeField(blank=True, help_text='End of the last period an auto-bill has been generated for.', null=True),
        ),
        migrations.AddField(
            model_name='careplan',
            name='last_auto_billed_visits',
            field=models.PositiveIntegerField(default=0, help_text='Number of completed visits already covered by auto-bills (per-visit plans only).'),
        ),
    ]
