# Generated by Django 6.0.4 on 2026-07-06 07:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0020_hr_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('initial', 'Initial Assessment'), ('head_to_toe', 'Head-to-Toe Baseline'), ('reassessment', 'Reassessment'), ('admission', 'Admission'), ('discharge', 'Discharge Assessment')], db_index=True, default='initial', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('signed', 'Signed Off')], db_index=True, default='completed', max_length=16)),
                ('arrival', models.JSONField(blank=True, default=dict, help_text='{arrival_timestamp, arrival_mode}')),
                ('initial_survey', models.JSONField(blank=True, default=dict, help_text='Vitals, consciousness, chief concern, pain, skin, safety checks, allergies & meds.')),
                ('head_to_toe', models.JSONField(blank=True, default=dict, help_text='Body-system survey: neuro, eyes/ENT, cardiac, respiratory, abdomen/GI, MSK, skin, continence, nutrition.')),
                ('braden', models.JSONField(blank=True, default=dict, help_text='{sensory, moisture, activity, mobility, nutrition, friction, total, risk_level}')),
                ('vte_caprini', models.JSONField(blank=True, default=dict, help_text='{age, factors:{…}, points, risk_level}')),
                ('falls', models.JSONField(blank=True, default=dict, help_text='{history_of_falls, secondary_dx, ambulatory_aid, iv_lock, gait, mental_status, score, risk_level}')),
                ('must', models.JSONField(blank=True, default=dict, help_text='{height_cm, weight_kg, bmi, bmi_score, weight_loss_percent, loss_score, acute_no_nutrition, acute_score, total_score, risk_level}')),
                ('cam', models.JSONField(blank=True, default=dict, help_text='{acute_onset, inattention, disorganized_thinking, altered_consciousness, cam_positive}')),
                ('pain', models.JSONField(blank=True, default=dict, help_text='{score, score_category, before, after, last_pain_meds, reassessment_due_at}')),
                ('catheter_bundle', models.JSONField(blank=True, default=dict, help_text='CAUTI prevention bundle (present, type, insert_date, indication, closed_system, bag_below_bladder, …).')),
                ('ventilator_bundle', models.JSONField(blank=True, default=dict, help_text='VAP prevention bundle (HOB elevated, SBT, sedation vacation, oral care, vent settings).')),
                ('central_line_bundle', models.JSONField(blank=True, default=dict, help_text='CLABSI prevention bundle (line type, insert date, site, dressing, maximal barrier, hub scrub, …).')),
                ('wound_bundle', models.JSONField(blank=True, default=dict, help_text='Pressure-injury / wound bundle (wound_details, turn schedule, special mattress, barrier cream).')),
                ('disease_bundles', models.JSONField(blank=True, default=dict, help_text='{diabetes:{…}, heart_failure:{…}, …}')),
                ('braden_total', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('caprini_points', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('morse_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('must_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('pain_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('cam_positive', models.BooleanField(blank=True, db_index=True, null=True)),
                ('overall_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('alerts_triggered', models.JSONField(blank=True, default=list, help_text='[{code, severity, message, …] generated by the scoring engine.')),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(blank=True, help_text='Caregiver who performed the assessment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_sessions', to='homecare.caregiver')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_sessions', to='homecare.homecarepatient')),
                ('schedule', models.ForeignKey(blank=True, help_text='Linked caregiver visit / shift, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_sessions', to='homecare.caregiverschedule')),
            ],
            options={
                'verbose_name': 'Assessment session',
                'verbose_name_plural': 'Assessment sessions',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Stable alert code (e.g. BRADEN_RISK) for dedup.', max_length=40)),
                ('category', models.CharField(choices=[('pressure', 'Pressure Injury Risk'), ('vte', 'VTE Risk'), ('falls', 'Falls Risk'), ('nutrition', 'Malnutrition Risk'), ('delirium', 'Delirium'), ('pain', 'Severe Pain'), ('device', 'Device Bundle'), ('other', 'Other')], db_index=True, max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='warning', max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('threshold', models.CharField(blank=True, help_text='e.g. "Braden ≤ 18"', max_length=80)),
                ('value', models.CharField(blank=True, help_text='e.g. "16 – Mild Risk"', max_length=80)),
                ('recommendation', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_alerts', to='homecare.escalation')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='homecare.assessmentsession')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['patient', '-assessed_at'], name='homecare_as_patient_6946f9_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['session_type', '-assessed_at'], name='homecare_as_session_b10588_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['overall_risk_level', '-assessed_at'], name='homecare_as_overall_1aa541_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentsession',
            index=models.Index(fields=['status', '-assessed_at'], name='homecare_as_status_8f19bb_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentalert',
            index=models.Index(fields=['session', 'severity'], name='homecare_as_session_16ace0_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentalert',
            index=models.Index(fields=['category', 'resolved'], name='homecare_as_categor_3083f4_idx'),
        ),
    ]
