# Generated by Django 6.0.4 on 2026-07-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0021_assessment_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='skin',
            field=models.JSONField(blank=True, default=dict, help_text='Skin care bundle: {reposition, surface, moisture, nutrition, heels, inspect, completed_count, completed_items, bundle_completed}.'),
        ),
    ]
