# Generated by Django 6.0.4 on 2026-07-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0022_add_skin_field_to_assessment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caregivernote',
            name='category',
            field=models.CharField(choices=[('diet', 'Diet'), ('activity', 'Activity'), ('observation', 'Observation'), ('vitals', 'Vitals'), ('incident', 'Incident'), ('medication', 'Medication'), ('doctor', 'Doctor Note'), ('nurse_hca', 'Nurse / HCA Note')], max_length=20),
        ),
    ]
