# Generated by Django 6.0.4 on 2026-07-08 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0023_add_doctor_nurse_note_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300)),
                ('category', models.CharField(choices=[('insurance_card', 'Insurance Cards'), ('id_document', 'ID Documents'), ('lab_report', 'Lab Reports'), ('imaging', 'Imaging / Radiology'), ('clinical_note', 'Clinical Notes'), ('prescription', 'Prescriptions'), ('consent', 'Consents'), ('care_plan', 'Care Plans'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('access_level', models.CharField(choices=[('care_team', 'Care Team'), ('doctor_only', 'Doctor Only'), ('nurse_only', 'Nurse Only'), ('restricted', 'Restricted')], db_index=True, default='care_team', max_length=15)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='homecare/patient-documents/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='homecare.homecarepatient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['category', 'access_level'], name='homecare_pa_categor_2de437_idx'), models.Index(fields=['patient', 'category'], name='homecare_pa_patient_2b851b_idx')],
            },
        ),
    ]
