# Generated by Django 6.0.4 on 2026-07-08 19:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_assessment_scales(apps, schema_editor):
    """Copy existing per-scale JSON data on AssessmentSession into the
    new strictly-separate per-type tables before the legacy JSON
    fields are removed from the parent model.

    The legacy scoring engine recomputed EVERY scale on EVERY session
    save (``recalculate_session``), and several calc_* functions
    return a concrete zero/False value rather than ``None`` even when
    no real input was given (e.g. Caprini/Morse/MUST always produce a
    0 score, CAM always produces ``cam_positive=False``). So we can't
    trust "value is not None" alone to mean "this scale was actually
    performed" for those four. Instead we prefer the ``component_key``
    tag the newer record-dialog stores in ``notes`` (JSON) to know
    exactly which single scale a session represents. For legacy rows
    saved before that tagging existed (no component_key), we only
    backfill Braden and Pain — the two scales whose calc_* functions
    reliably return ``None`` when nothing was entered — plus Skin
    Care / GCS / disease bundles, which were never part of the
    blanket recompute and so are only ever populated when genuinely
    recorded.
    """
    import json as _json

    from homecare.assessments import (
        calc_braden, calc_caprini, calc_morse, calc_must, calc_cam,
        calc_pain, calc_gcs,
    )
    AssessmentSession = apps.get_model('homecare', 'AssessmentSession')
    BradenAssessment = apps.get_model('homecare', 'BradenAssessment')
    CapriniAssessment = apps.get_model('homecare', 'CapriniAssessment')
    MorseAssessment = apps.get_model('homecare', 'MorseAssessment')
    MustAssessment = apps.get_model('homecare', 'MustAssessment')
    CamAssessment = apps.get_model('homecare', 'CamAssessment')
    PainAssessment = apps.get_model('homecare', 'PainAssessment')
    SkinCareAssessment = apps.get_model('homecare', 'SkinCareAssessment')
    GcsAssessment = apps.get_model('homecare', 'GcsAssessment')
    DiabetesBundleAssessment = apps.get_model('homecare', 'DiabetesBundleAssessment')
    HeartFailureBundleAssessment = apps.get_model('homecare', 'HeartFailureBundleAssessment')

    def _component_key(session):
        if not session.notes:
            return None
        try:
            meta = _json.loads(session.notes)
        except (TypeError, ValueError):
            return None
        return meta.get('component_key') if isinstance(meta, dict) else None

    for session in AssessmentSession.objects.all().iterator():
        component_key = _component_key(session)
        common = dict(
            episode_id=session.id, patient_id=session.patient_id,
            notes=session.notes or '', assessed_by_user_id=session.assessed_by_user_id,
            assessed_by_name=session.assessed_by_name or '', assessed_at=session.assessed_at,
        )

        braden = session.braden or {}
        if braden.get('total') is not None and component_key in (None, 'braden'):
            c = calc_braden(braden)
            BradenAssessment.objects.create(
                sensory=c.get('sensory'), moisture=c.get('moisture'),
                activity=c.get('activity'), mobility=c.get('mobility'),
                nutrition=c.get('nutrition'), friction=c.get('friction'),
                total=c.get('total'), risk_level=c.get('risk_level') or '',
                **common,
            )

        caprini = session.vte_caprini or {}
        if component_key == 'caprini':
            c = calc_caprini(caprini)
            CapriniAssessment.objects.create(
                age=caprini.get('age'), factors=c.get('factors') or {},
                points=c.get('points'), risk_level=c.get('risk_level') or '',
                **common,
            )

        falls = session.falls or {}
        if component_key == 'morse':
            c = calc_morse(falls)
            MorseAssessment.objects.create(
                history_of_falls=bool(falls.get('history_of_falls')),
                secondary_dx=bool(falls.get('secondary_dx')),
                ambulatory_aid=str(falls.get('ambulatory_aid') or ''),
                iv_lock=bool(falls.get('iv_lock')),
                gait=str(falls.get('gait') or ''),
                mental_status=str(falls.get('mental_status') or ''),
                score=c.get('score'), risk_level=c.get('risk_level') or '',
                **common,
            )

        must = session.must or {}
        if component_key == 'must':
            c = calc_must(must)
            MustAssessment.objects.create(
                height_cm=must.get('height_cm'), weight_kg=must.get('weight_kg'),
                bmi=c.get('bmi'), bmi_score=c.get('bmi_score'),
                weight_loss_percent=must.get('weight_loss_percent'),
                loss_score=c.get('loss_score'),
                acute_no_nutrition=bool(must.get('acute_no_nutrition')),
                acute_score=c.get('acute_score'),
                total_score=c.get('total_score'), risk_level=c.get('risk_level') or '',
                **common,
            )

        cam = session.cam or {}
        if component_key == 'cam':
            c = calc_cam(cam)
            CamAssessment.objects.create(
                acute_onset=bool(c.get('acute_onset')),
                inattention=bool(c.get('inattention')),
                disorganized_thinking=bool(c.get('disorganized_thinking')),
                altered_consciousness=bool(c.get('altered_consciousness')),
                cam_positive=c.get('cam_positive'),
                **common,
            )

        pain = session.pain or {}
        if pain.get('score') is not None and component_key in (None, 'pain_reassess'):
            c = calc_pain(pain)
            PainAssessment.objects.create(
                score=c.get('score'), score_category=c.get('score_category') or '',
                **common,
            )

        skin = session.skin or {}
        if skin and component_key in (None, 'skin_care'):
            items = [k for k in ('reposition', 'surface', 'moisture', 'nutrition', 'heels', 'inspect') if skin.get(k)]
            SkinCareAssessment.objects.create(
                reposition=bool(skin.get('reposition')), surface=bool(skin.get('surface')),
                moisture=bool(skin.get('moisture')), nutrition=bool(skin.get('nutrition')),
                heels=bool(skin.get('heels')), inspect=bool(skin.get('inspect')),
                completed_count=skin.get('completed_count') or len(items),
                completed_items=skin.get('completed_items') or items,
                bundle_completed=bool(skin.get('bundle_completed')),
                **common,
            )

        survey = session.initial_survey or {}
        has_gcs = survey.get('gcs_total') is not None or (
            survey.get('gcs_eyes') is not None and survey.get('gcs_verbal') is not None
            and survey.get('gcs_motor') is not None
        )
        if has_gcs and component_key in (None, 'gcs'):
            c = calc_gcs({
                'eyes': survey.get('gcs_eyes'), 'verbal': survey.get('gcs_verbal'),
                'motor': survey.get('gcs_motor'), 'total': survey.get('gcs_total'),
            })
            GcsAssessment.objects.create(
                eyes=c.get('eyes'), verbal=c.get('verbal'), motor=c.get('motor'),
                total=c.get('total'),
                **common,
            )

        bundles = session.disease_bundles or {}
        diabetes = bundles.get('diabetes') or {}
        if diabetes and component_key in (None, 'diabetes_bundle'):
            DiabetesBundleAssessment.objects.create(
                glucose=diabetes.get('glucose'), ketones=diabetes.get('ketones'),
                **common,
            )
        hf = bundles.get('heart_failure') or {}
        if hf and component_key in (None, 'hf_bundle'):
            HeartFailureBundleAssessment.objects.create(
                weight_kg=hf.get('weight_kg'), fluid_balance_ml=hf.get('fluid_balance_ml'),
                spo2=hf.get('spo2'),
                **common,
            )


def noop_reverse(apps, schema_editor):
    """Data intentionally stays in the new tables on reverse; the old
    JSON fields are recreated empty, so there is nothing to copy back.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0024_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsession',
            name='gcs_total',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='BradenAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensory', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('moisture', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('activity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mobility', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nutrition', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('friction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braden_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='braden_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Braden Scale assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='CamAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acute_onset', models.BooleanField(default=False)),
                ('inattention', models.BooleanField(default=False)),
                ('disorganized_thinking', models.BooleanField(default=False)),
                ('altered_consciousness', models.BooleanField(default=False)),
                ('cam_positive', models.BooleanField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cam_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'CAM assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='CapriniAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('factors', models.JSONField(blank=True, default=dict, help_text='{factor_key: bool, …}')),
                ('points', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caprini_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caprini_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Caprini Score assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='DiabetesBundleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('ketones', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_bundle_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diabetes_bundle_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Diabetes bundle assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='GcsAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('verbal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('motor', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcs_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gcs_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'GCS assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='HeartFailureBundleAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('fluid_balance_ml', models.IntegerField(blank=True, null=True)),
                ('spo2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hf_bundle_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hf_bundle_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Heart Failure bundle assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='MorseAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history_of_falls', models.BooleanField(default=False)),
                ('secondary_dx', models.BooleanField(default=False)),
                ('ambulatory_aid', models.CharField(blank=True, max_length=20)),
                ('iv_lock', models.BooleanField(default=False)),
                ('gait', models.CharField(blank=True, max_length=20)),
                ('mental_status', models.CharField(blank=True, max_length=20)),
                ('score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morse_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morse_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Morse Fall Scale assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='MustAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_kg', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('bmi_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('weight_loss_percent', models.FloatField(blank=True, null=True)),
                ('loss_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('acute_no_nutrition', models.BooleanField(default=False)),
                ('acute_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('total_score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='must_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'MUST assessment',
                'verbose_name_plural': 'MUST assessments',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='PainAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('score_category', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Pain reassessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.CreateModel(
            name='SkinCareAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reposition', models.BooleanField(default=False)),
                ('surface', models.BooleanField(default=False)),
                ('moisture', models.BooleanField(default=False)),
                ('nutrition', models.BooleanField(default=False)),
                ('heels', models.BooleanField(default=False)),
                ('inspect', models.BooleanField(default=False)),
                ('completed_count', models.PositiveSmallIntegerField(default=0)),
                ('completed_items', models.JSONField(blank=True, default=list)),
                ('bundle_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_care_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skin_care_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Skin Care Bundle assessment',
                'ordering': ['-assessed_at'],
            },
        ),
        migrations.RunPython(backfill_assessment_scales, noop_reverse),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='braden',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='cam',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='falls',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='must',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='pain',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='skin',
        ),
        migrations.RemoveField(
            model_name='assessmentsession',
            name='vte_caprini',
        ),
    ]
