# Generated by Django 6.0.4 on 2026-07-08 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0025_split_assessment_scales_into_own_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='painassessment',
            options={'ordering': ['-assessed_at'], 'verbose_name': 'Pain assessment', 'verbose_name_plural': 'Pain assessments'},
        ),
        migrations.AddField(
            model_name='painassessment',
            name='acceptable_pain_goal',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Patient-set acceptable pain goal (0–10).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='average_pain',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Average pain over reporting period (0–10).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='faces_choice',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Selected face 0/2/4/6/8/10.', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='faces_description',
            field=models.TextField(blank=True, help_text='Child verbal description of chosen face.'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='flacc_activity',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FLACC Activity (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='flacc_consolability',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FLACC Consolability (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='flacc_cry',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FLACC Cry (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='flacc_face',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FLACC Face (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='flacc_legs',
            field=models.PositiveSmallIntegerField(blank=True, help_text='FLACC Legs (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='has_pain',
            field=models.BooleanField(blank=True, help_text='Is the patient currently experiencing pain? Null = not screened.', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='has_radiation',
            field=models.BooleanField(blank=True, help_text='Does the pain radiate?', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='impact_adl',
            field=models.BooleanField(blank=True, help_text='Does pain interfere with activities of daily living?', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='impact_appetite',
            field=models.BooleanField(blank=True, help_text='Does pain affect appetite?', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='impact_mood',
            field=models.BooleanField(blank=True, help_text='Does pain affect mood?', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='impact_other',
            field=models.CharField(blank=True, help_text='Other functional impacts.', max_length=255),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='impact_sleep',
            field=models.BooleanField(blank=True, help_text='Does pain interfere with sleep?', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='last_pain_episode',
            field=models.TextField(blank=True, help_text='Details of last pain episode if currently pain-free.'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='least_pain_24h',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Least pain in past 24 hours (0–10).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='onset_datetime',
            field=models.DateTimeField(blank=True, help_text='When the pain started.', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='onset_type',
            field=models.CharField(blank=True, help_text='sudden / gradual', max_length=20),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='pain_duration',
            field=models.CharField(blank=True, help_text='How long the pain lasts (minutes / hours / days).', max_length=80),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='pain_frequency',
            field=models.CharField(blank=True, help_text='How often pain occurs (e.g. 3×/day, continuous).', max_length=80),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='pain_locations',
            field=models.JSONField(blank=True, default=list, help_text='Selected body-map regions (head, neck, shoulder, chest, …).'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='pain_pattern',
            field=models.CharField(blank=True, help_text='constant / intermittent', max_length=20),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='painad_body_language',
            field=models.PositiveSmallIntegerField(blank=True, help_text='PAINAD Body Language (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='painad_breathing',
            field=models.PositiveSmallIntegerField(blank=True, help_text='PAINAD Breathing (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='painad_consolability',
            field=models.PositiveSmallIntegerField(blank=True, help_text='PAINAD Consolability (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='painad_facial',
            field=models.PositiveSmallIntegerField(blank=True, help_text='PAINAD Facial Expression (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='painad_negative_vocal',
            field=models.PositiveSmallIntegerField(blank=True, help_text='PAINAD Negative Vocalisation (0–2).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='palliation_factors',
            field=models.JSONField(blank=True, default=list, help_text='List of factors that relieve pain (rest, medication, etc.).'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='post_treatment_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pain score after intervention.', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='pre_treatment_score',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Pain score before intervention.', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='provocation_factors',
            field=models.JSONField(blank=True, default=list, help_text='List of factors that make pain worse (movement, coughing, etc.).'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='quality_descriptors',
            field=models.JSONField(blank=True, default=list, help_text='Selected pain quality descriptors (sharp, dull, aching, burning, …).'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='quality_other',
            field=models.CharField(blank=True, help_text='Free-text pain quality description.', max_length=255),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='radiation_pathway',
            field=models.TextField(blank=True, help_text='Free-text or region list describing radiation path.'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='reassessment_due_at',
            field=models.DateTimeField(blank=True, help_text='When the next pain reassessment is scheduled.', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='tool_type',
            field=models.CharField(choices=[('nrs', 'Numeric Rating Scale (0–10)'), ('vas', 'Visual Analog Scale'), ('faces', 'Wong-Baker FACES'), ('flacc', 'FLACC (Face, Legs, Activity, Cry, Consolability)'), ('painad', 'PAINAD (Pain Assessment in Advanced Dementia)')], default='nrs', help_text='Selected pain assessment tool (auto-selected based on age/condition).', max_length=12),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='treatment_given',
            field=models.TextField(blank=True, help_text='Description of intervention (medication, repositioning, …).'),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='vas_mm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='VAS mark position in mm on a 100 mm line (converted to 0–10).', null=True),
        ),
        migrations.AddField(
            model_name='painassessment',
            name='worst_pain_24h',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Worst pain in past 24 hours (0–10).', null=True),
        ),
        migrations.AlterField(
            model_name='painassessment',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text='Current pain score (0–10).', null=True),
        ),
        migrations.AlterField(
            model_name='painassessment',
            name='score_category',
            field=models.CharField(blank=True, help_text='None / Mild / Moderate / Severe', max_length=20),
        ),
    ]
