# Generated by Django 6.0.4 on 2026-07-08 21:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0027_add_pivc_assessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnteralFeedingAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('ngt', 'Nasogastric Tube (NGT)'), ('ogt', 'Orogastric Tube (OGT)'), ('peg', 'Percutaneous Endoscopic Gastrostomy (PEG)'), ('pej', 'Percutaneous Endoscopic Jejunostomy (PEJ)'), ('gj', 'Gastrojejunostomy (GJ) Tube'), ('j_tube', 'Jejunostomy (J-Tube)'), ('nj', 'Nasojejunal (NJ) Tube'), ('other', 'Other')], db_index=True, help_text='Auto-detected from Device Registry; determines which bundle items apply.', max_length=16)),
                ('device_status', models.CharField(blank=True, default='active', help_text='active / removed', max_length=12)),
                ('insertion_date', models.DateTimeField(blank=True, null=True)),
                ('tube_size', models.CharField(blank=True, help_text='e.g. Fr 16', max_length=40)),
                ('insertion_site', models.CharField(blank=True, max_length=80)),
                ('external_length_cm', models.FloatField(blank=True, help_text='External tube length in cm (NGT/OGT).', null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255)),
                ('balloon_status', models.CharField(blank=True, help_text='Intact / deflated / ruptured / unknown (PEG/PEJ where applicable).', max_length=40)),
                ('bundle_hand_hygiene', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_ppe', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_device_necessity', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_device_securement', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_tube_patency', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_water_flush_protocol', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_feeding_equipment_check', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_patient_positioning', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_oral_care', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_documentation_complete', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_position_verification', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_nare_care', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_skin_protection', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_nasal_pressure_prevention', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_stoma_care', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_external_fixation_check', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_external_length_verify', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_tube_rotation', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_dressing_management', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_buried_bumper', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_peristomal_care', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_med_safety_check', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_patient_education', models.CharField(blank=True, default='', max_length=4)),
                ('bundle_compliance_pct', models.PositiveSmallIntegerField(blank=True, help_text='Auto-calculated percentage of "yes" in applicable bundle items.', null=True)),
                ('device_removed', models.BooleanField(default=False)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('removal_date', models.DateTimeField(blank=True, null=True)),
                ('removal_by_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('assessed_by_user_id', models.IntegerField(blank=True, null=True)),
                ('assessed_by_name', models.CharField(blank=True, max_length=255)),
                ('assessed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enteral_feeding_assessments', to='homecare.assessmentsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enteral_feeding_assessments', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Enteral feeding assessment',
                'verbose_name_plural': 'Enteral feeding assessments',
                'ordering': ['-assessed_at'],
            },
        ),
    ]
