# Generated by Django 6.0.4 on 2026-07-09 10:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0031_cvadassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrainLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('catheter', 'Urinary Catheter'), ('central_line', 'Central Line'), ('picc', 'PICC Line'), ('ventilator', 'Ventilator Circuit'), ('wound_drain', 'Wound Drain'), ('iv_peripheral', 'IV Peripheral'), ('nasogastric', 'Nasogastric Tube'), ('chest_tube', 'Chest Tube'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Free-text device name / ID, e.g. "16Fr Foley".', max_length=255)),
                ('site', models.CharField(blank=True, help_text='Insertion site, e.g. Right IJ, Left forearm.', max_length=255)),
                ('indication', models.TextField(blank=True)),
                ('insert_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('max_days_override', models.PositiveSmallIntegerField(blank=True, help_text='Override the recommended max dwell days for this line type.', null=True)),
                ('dressing_intact', models.BooleanField(default=True)),
                ('site_clean', models.BooleanField(default=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('removal_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drains_lines', to='homecare.homecarepatient')),
            ],
            options={
                'verbose_name': 'Drain / Line',
                'verbose_name_plural': 'Drains & Lines',
                'ordering': ['-insert_date'],
            },
        ),
    ]
