# Generated by Django 6.0.4 on 2026-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homecare', '0034_billingsettings_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'Billing settings', 'verbose_name_plural': 'Billing settings'},
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='auto_generate',
            field=models.BooleanField(db_index=True, default=True, help_text='Master switch for automatic bill generation for this patient.'),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='billing_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('manually', 'Manually (no auto-generation)')], db_index=True, default='daily', help_text="How often this patient's bills are auto-generated.", max_length=16),
        ),
        migrations.AlterField(
            model_name='billingsettings',
            name='last_run_at',
            field=models.DateTimeField(blank=True, help_text='When the auto-generate tick last ran for this patient.', null=True),
        ),
    ]
