# Generated by Django 6.0.4 on 2026-04-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('operating_hours', models.JSONField(blank=True, default=dict, help_text='Day-wise open/close hours')),
                ('services', models.JSONField(blank=True, default=list, help_text='e.g., delivery, compounding')),
                ('delivery_radius_km', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accepts_insurance', models.BooleanField(default=False)),
                ('insurance_providers', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pharmacy Detail',
                'verbose_name_plural': 'Pharmacy Details',
            },
        ),
    ]
