# Generated by Django 6.0.4 on 2026-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0002_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacydetail',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='pharmacy_logos/'),
        ),
    ]
