# Generated by Django 6.0.4 on 2026-05-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0005_delivery_latitude_delivery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='assigned_driver_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
