# Generated by Django 6.0.4 on 2026-05-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0008_increase_lat_lng_to_12_decimals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True),
        ),
    ]
