# Generated by Django 6.0.4 on 2026-09-20 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0009_increase_lat_lng_max_digits_to_30'),
        ('pos', '0009_creditpayment'),
        ('sales_orders', '0003_salesorder_delivery_lat_salesorder_delivery_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='sales_order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='sales_orders.salesorder'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('to_be_packed', 'To Be Packed'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='pos.postransaction'),
        ),
    ]
