# Generated by Django 6.0.4 on 2026-09-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_profile', '0010_delivery_sales_order_alter_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(choices=[('to_be_packed', 'To Be Packed'), ('to_be_shipped', 'To Be Shipped'), ('pending', 'Pending'), ('assigned', 'Assigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
