# Generated by Django 6.0.4 on 2026-04-13 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_type', models.CharField(choices=[('independent', 'Independent'), ('hospital', 'Hospital-Affiliated')], default='independent', max_length=20)),
                ('specialization', models.CharField(max_length=255)),
                ('license_number', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=255)),
                ('years_of_experience', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_accepting_patients', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('available_days', models.JSONField(blank=True, default=list, help_text='e.g. ["Monday","Tuesday","Wednesday"]')),
                ('available_hours', models.JSONField(blank=True, default=dict, help_text='e.g. {"start": "08:00", "end": "17:00"}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(blank=True, help_text='Hospital tenant (if affiliated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='tenants.tenant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
