# Generated by Django 6.0.4 on 2026-05-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctorprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='signature',
            field=models.ImageField(blank=True, help_text="Doctor's digital signature image (PNG)", null=True, upload_to='doctor_signatures/'),
        ),
    ]
