"""
Seed the ExamCatalog with a comprehensive list of standard radiology exams.
Usage:  python manage.py tenant_command seed_exam_catalog --schema=<schema>
        python manage.py tenant_command seed_exam_catalog --schema=<schema> --clear
"""
from django.core.management.base import BaseCommand
from radiology.models import ExamCatalog

EXAMS = [
    # ── X-Ray ─────────────────────────────────────────────────────────
    {"code": "XR-CHEST-PA", "name": "Chest X-Ray (PA)", "modality_type": "xray", "body_region": "Chest", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "PA erect, full inspiration", "prep_instructions": "Remove jewelry and metal objects from chest area."},
    {"code": "XR-CHEST-AP", "name": "Chest X-Ray (AP)", "modality_type": "xray", "body_region": "Chest", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP supine or erect", "prep_instructions": "Remove jewelry and metal objects."},
    {"code": "XR-CHEST-LAT", "name": "Chest X-Ray (Lateral)", "modality_type": "xray", "body_region": "Chest", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "Left lateral erect", "prep_instructions": "Remove jewelry and metal objects."},
    {"code": "XR-ABDOMEN", "name": "Abdominal X-Ray", "modality_type": "xray", "body_region": "Abdomen", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "Supine AP abdomen", "prep_instructions": "No special preparation required."},
    {"code": "XR-KUB", "name": "KUB (Kidneys, Ureters, Bladder)", "modality_type": "xray", "body_region": "Abdomen", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "Supine AP, include diaphragm to symphysis", "prep_instructions": "No special preparation required."},
    {"code": "XR-CSPINE", "name": "Cervical Spine X-Ray", "modality_type": "xray", "body_region": "Spine - Cervical", "estimated_duration_minutes": 15, "price": 2000, "contrast_required": False, "default_protocol": "AP, lateral, obliques, odontoid views", "prep_instructions": "Remove necklaces and earrings."},
    {"code": "XR-TSPINE", "name": "Thoracic Spine X-Ray", "modality_type": "xray", "body_region": "Spine - Thoracic", "estimated_duration_minutes": 15, "price": 2000, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing and jewelry from the area."},
    {"code": "XR-LSPINE", "name": "Lumbar Spine X-Ray", "modality_type": "xray", "body_region": "Spine - Lumbar", "estimated_duration_minutes": 15, "price": 2200, "contrast_required": False, "default_protocol": "AP, lateral, and oblique views", "prep_instructions": "Remove belt and any metal objects."},
    {"code": "XR-PELVIS", "name": "Pelvis X-Ray", "modality_type": "xray", "body_region": "Pelvis", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP pelvis", "prep_instructions": "Remove belt and pocket contents."},
    {"code": "XR-HIP-R", "name": "Hip X-Ray (Right)", "modality_type": "xray", "body_region": "Hip", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-HIP-L", "name": "Hip X-Ray (Left)", "modality_type": "xray", "body_region": "Hip", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-KNEE-R", "name": "Knee X-Ray (Right)", "modality_type": "xray", "body_region": "Knee", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP, lateral, and skyline views", "prep_instructions": "Remove knee braces or supports."},
    {"code": "XR-KNEE-L", "name": "Knee X-Ray (Left)", "modality_type": "xray", "body_region": "Knee", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP, lateral, and skyline views", "prep_instructions": "Remove knee braces or supports."},
    {"code": "XR-ANKLE-R", "name": "Ankle X-Ray (Right)", "modality_type": "xray", "body_region": "Ankle", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP, lateral, and mortise views", "prep_instructions": "Remove shoes and socks."},
    {"code": "XR-ANKLE-L", "name": "Ankle X-Ray (Left)", "modality_type": "xray", "body_region": "Ankle", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP, lateral, and mortise views", "prep_instructions": "Remove shoes and socks."},
    {"code": "XR-FOOT-R", "name": "Foot X-Ray (Right)", "modality_type": "xray", "body_region": "Foot", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP, lateral, and oblique views", "prep_instructions": "Remove shoes and socks."},
    {"code": "XR-FOOT-L", "name": "Foot X-Ray (Left)", "modality_type": "xray", "body_region": "Foot", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP, lateral, and oblique views", "prep_instructions": "Remove shoes and socks."},
    {"code": "XR-SHOULDER-R", "name": "Shoulder X-Ray (Right)", "modality_type": "xray", "body_region": "Shoulder", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP internal/external rotation, scapular Y view", "prep_instructions": "Remove clothing from shoulder area."},
    {"code": "XR-SHOULDER-L", "name": "Shoulder X-Ray (Left)", "modality_type": "xray", "body_region": "Shoulder", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP internal/external rotation, scapular Y view", "prep_instructions": "Remove clothing from shoulder area."},
    {"code": "XR-ELBOW-R", "name": "Elbow X-Ray (Right)", "modality_type": "xray", "body_region": "Elbow", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove watches and bracelets."},
    {"code": "XR-ELBOW-L", "name": "Elbow X-Ray (Left)", "modality_type": "xray", "body_region": "Elbow", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove watches and bracelets."},
    {"code": "XR-WRIST-R", "name": "Wrist X-Ray (Right)", "modality_type": "xray", "body_region": "Wrist", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "PA, lateral, and oblique views", "prep_instructions": "Remove watches and bracelets."},
    {"code": "XR-WRIST-L", "name": "Wrist X-Ray (Left)", "modality_type": "xray", "body_region": "Wrist", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "PA, lateral, and oblique views", "prep_instructions": "Remove watches and bracelets."},
    {"code": "XR-HAND-R", "name": "Hand X-Ray (Right)", "modality_type": "xray", "body_region": "Hand", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "PA, lateral, and oblique views", "prep_instructions": "Remove rings and jewelry."},
    {"code": "XR-HAND-L", "name": "Hand X-Ray (Left)", "modality_type": "xray", "body_region": "Hand", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "PA, lateral, and oblique views", "prep_instructions": "Remove rings and jewelry."},
    {"code": "XR-SKULL", "name": "Skull X-Ray", "modality_type": "xray", "body_region": "Head", "estimated_duration_minutes": 15, "price": 2000, "contrast_required": False, "default_protocol": "PA, lateral, and Towne views", "prep_instructions": "Remove hairpins, glasses, and earrings."},
    {"code": "XR-SINUS", "name": "Sinus X-Ray (Waters View)", "modality_type": "xray", "body_region": "Head", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "Waters, Caldwell, lateral views", "prep_instructions": "Remove glasses and earrings."},
    {"code": "XR-MANDIBLE", "name": "Mandible X-Ray", "modality_type": "xray", "body_region": "Head", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "PA and oblique views", "prep_instructions": "Remove dentures and jewelry."},
    {"code": "XR-RIBS", "name": "Rib X-Ray", "modality_type": "xray", "body_region": "Chest", "estimated_duration_minutes": 15, "price": 2000, "contrast_required": False, "default_protocol": "PA and oblique views", "prep_instructions": "Remove clothing from chest area."},
    {"code": "XR-CLAVICLE", "name": "Clavicle X-Ray", "modality_type": "xray", "body_region": "Shoulder", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP with cephalic tilt", "prep_instructions": "Remove necklaces and clothing from area."},
    {"code": "XR-SACRUM", "name": "Sacrum / Coccyx X-Ray", "modality_type": "xray", "body_region": "Pelvis", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "No special preparation required."},
    {"code": "XR-TIBIA-R", "name": "Tibia/Fibula X-Ray (Right)", "modality_type": "xray", "body_region": "Lower Extremity", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-TIBIA-L", "name": "Tibia/Fibula X-Ray (Left)", "modality_type": "xray", "body_region": "Lower Extremity", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-FOREARM-R", "name": "Forearm X-Ray (Right)", "modality_type": "xray", "body_region": "Upper Extremity", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove watches and bracelets."},
    {"code": "XR-FOREARM-L", "name": "Forearm X-Ray (Left)", "modality_type": "xray", "body_region": "Upper Extremity", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove watches and bracelets."},
    {"code": "XR-HUMERUS-R", "name": "Humerus X-Ray (Right)", "modality_type": "xray", "body_region": "Upper Extremity", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-HUMERUS-L", "name": "Humerus X-Ray (Left)", "modality_type": "xray", "body_region": "Upper Extremity", "estimated_duration_minutes": 10, "price": 1500, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-FEMUR-R", "name": "Femur X-Ray (Right)", "modality_type": "xray", "body_region": "Lower Extremity", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},
    {"code": "XR-FEMUR-L", "name": "Femur X-Ray (Left)", "modality_type": "xray", "body_region": "Lower Extremity", "estimated_duration_minutes": 10, "price": 1800, "contrast_required": False, "default_protocol": "AP and lateral views", "prep_instructions": "Remove clothing from the area."},

    # ── CT Scan ───────────────────────────────────────────────────────
    {"code": "CT-HEAD", "name": "CT Head (Brain) without Contrast", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Axial 5mm slices, base of skull to vertex", "prep_instructions": "Remove hairpins, glasses, earrings. No fasting required."},
    {"code": "CT-HEAD-C", "name": "CT Head (Brain) with Contrast", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 20, "price": 10000, "contrast_required": True, "default_protocol": "Pre and post contrast axial 5mm", "prep_instructions": "Check renal function (creatinine). NPO 4 hours. Remove metal objects."},
    {"code": "CT-SINUS", "name": "CT Sinuses", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 15, "price": 7000, "contrast_required": False, "default_protocol": "Axial and coronal 3mm slices", "prep_instructions": "Remove glasses and earrings."},
    {"code": "CT-ORBIT", "name": "CT Orbits", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Axial and coronal thin slices through orbits", "prep_instructions": "Remove glasses and contact lenses if possible."},
    {"code": "CT-TEMPORAL", "name": "CT Temporal Bones", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "High-resolution axial and coronal 1mm", "prep_instructions": "Remove earrings and hearing aids."},
    {"code": "CT-NECK", "name": "CT Neck (Soft Tissue) with Contrast", "modality_type": "ct", "body_region": "Neck", "estimated_duration_minutes": 20, "price": 10000, "contrast_required": True, "default_protocol": "Axial 3mm from skull base to thoracic inlet", "prep_instructions": "NPO 4 hours. Check renal function. Remove necklaces."},
    {"code": "CT-CSPINE", "name": "CT Cervical Spine", "modality_type": "ct", "body_region": "Spine - Cervical", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Axial with sagittal and coronal reformats", "prep_instructions": "Remove necklaces and collar if safe."},
    {"code": "CT-TSPINE", "name": "CT Thoracic Spine", "modality_type": "ct", "body_region": "Spine - Thoracic", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Axial with sagittal and coronal reformats", "prep_instructions": "Remove clothing and metal from area."},
    {"code": "CT-LSPINE", "name": "CT Lumbar Spine", "modality_type": "ct", "body_region": "Spine - Lumbar", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Axial with sagittal and coronal reformats", "prep_instructions": "Remove belt and metal objects."},
    {"code": "CT-CHEST", "name": "CT Chest without Contrast", "modality_type": "ct", "body_region": "Chest", "estimated_duration_minutes": 15, "price": 10000, "contrast_required": False, "default_protocol": "Axial 5mm, lung and mediastinal windows", "prep_instructions": "Remove jewelry. Breath-hold instructions."},
    {"code": "CT-CHEST-C", "name": "CT Chest with Contrast", "modality_type": "ct", "body_region": "Chest", "estimated_duration_minutes": 20, "price": 12000, "contrast_required": True, "default_protocol": "Pre and post contrast, lung and mediastinal windows", "prep_instructions": "NPO 4 hours. Check renal function. Breath-hold."},
    {"code": "CT-HRCT", "name": "CT Chest HRCT (High-Resolution)", "modality_type": "ct", "body_region": "Chest", "estimated_duration_minutes": 20, "price": 12000, "contrast_required": False, "default_protocol": "Thin-section 1-2mm axial, prone and supine", "prep_instructions": "Remove jewelry. Breath-hold instructions."},
    {"code": "CT-PE", "name": "CT Pulmonary Angiography (CTPA)", "modality_type": "ct", "body_region": "Chest", "estimated_duration_minutes": 20, "price": 15000, "contrast_required": True, "default_protocol": "Bolus-tracked PA opacification, thin slices", "prep_instructions": "NPO 4 hours. Check renal function. IV access required."},
    {"code": "CT-ABDOMEN", "name": "CT Abdomen without Contrast", "modality_type": "ct", "body_region": "Abdomen", "estimated_duration_minutes": 15, "price": 10000, "contrast_required": False, "default_protocol": "Axial 5mm slices, diaphragm to iliac crest", "prep_instructions": "NPO 6 hours if possible. Remove belt."},
    {"code": "CT-ABDOMEN-C", "name": "CT Abdomen with Contrast", "modality_type": "ct", "body_region": "Abdomen", "estimated_duration_minutes": 25, "price": 12000, "contrast_required": True, "default_protocol": "Pre-contrast, arterial, portal venous phases", "prep_instructions": "NPO 6 hours. Check renal function. Oral contrast 1hr before if indicated."},
    {"code": "CT-ABD-PELVIS", "name": "CT Abdomen & Pelvis with Contrast", "modality_type": "ct", "body_region": "Abdomen", "estimated_duration_minutes": 25, "price": 15000, "contrast_required": True, "default_protocol": "Arterial and portal venous phases, diaphragm to symphysis", "prep_instructions": "NPO 6 hours. Check renal function. Oral contrast if indicated."},
    {"code": "CT-KUB", "name": "CT KUB (Renal Stone Protocol)", "modality_type": "ct", "body_region": "Abdomen", "estimated_duration_minutes": 10, "price": 8000, "contrast_required": False, "default_protocol": "Low-dose non-contrast, thin slices kidneys to bladder", "prep_instructions": "No fasting. Drink water to distend bladder."},
    {"code": "CT-PELVIS", "name": "CT Pelvis with Contrast", "modality_type": "ct", "body_region": "Pelvis", "estimated_duration_minutes": 20, "price": 10000, "contrast_required": True, "default_protocol": "Axial 5mm with contrast, iliac crest to symphysis", "prep_instructions": "NPO 4 hours. Check renal function. Full bladder preferred."},
    {"code": "CT-ANGIO-HEAD", "name": "CT Angiography Head (Circle of Willis)", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 20, "price": 15000, "contrast_required": True, "default_protocol": "Bolus-tracked thin-section CTA with 3D reformats", "prep_instructions": "NPO 4 hours. Check renal function. IV access required."},
    {"code": "CT-ANGIO-NECK", "name": "CT Angiography Carotids", "modality_type": "ct", "body_region": "Neck", "estimated_duration_minutes": 20, "price": 15000, "contrast_required": True, "default_protocol": "Bolus-tracked CTA arch to vertex", "prep_instructions": "NPO 4 hours. Check renal function. IV access required."},
    {"code": "CT-ANGIO-CHEST", "name": "CT Angiography Thoracic Aorta", "modality_type": "ct", "body_region": "Chest", "estimated_duration_minutes": 20, "price": 15000, "contrast_required": True, "default_protocol": "ECG-gated CTA aortic root to diaphragm", "prep_instructions": "NPO 4 hours. Check renal function. IV access required."},
    {"code": "CT-ANGIO-ABD", "name": "CT Angiography Abdominal Aorta", "modality_type": "ct", "body_region": "Abdomen", "estimated_duration_minutes": 20, "price": 15000, "contrast_required": True, "default_protocol": "Bolus-tracked CTA, arterial and delayed phases", "prep_instructions": "NPO 4 hours. Check renal function. IV access required."},
    {"code": "CT-ANGIO-RUNOFF", "name": "CT Angiography Lower Limb Runoff", "modality_type": "ct", "body_region": "Lower Extremity", "estimated_duration_minutes": 25, "price": 18000, "contrast_required": True, "default_protocol": "Bolus-tracked CTA aorta to feet", "prep_instructions": "NPO 4 hours. Check renal function. IV access required."},
    {"code": "CT-FACE", "name": "CT Facial Bones", "modality_type": "ct", "body_region": "Head", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Axial and coronal thin slices with 3D reformats", "prep_instructions": "Remove glasses, dentures, earrings."},
    {"code": "CT-CORONARY", "name": "CT Coronary Angiography (Calcium Score)", "modality_type": "ct", "body_region": "Chest", "estimated_duration_minutes": 30, "price": 20000, "contrast_required": True, "default_protocol": "ECG-gated, prospective or retrospective", "prep_instructions": "NPO 4 hours. HR <65 preferred. Beta-blocker pre-medication may be needed."},

    # ── MRI ───────────────────────────────────────────────────────────
    {"code": "MRI-BRAIN", "name": "MRI Brain without Contrast", "modality_type": "mri", "body_region": "Brain", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Axial T1, T2, FLAIR, DWI; Sagittal T1; Coronal T2", "prep_instructions": "MRI safety screening. Remove all metal objects. No special fasting."},
    {"code": "MRI-BRAIN-C", "name": "MRI Brain with Contrast", "modality_type": "mri", "body_region": "Brain", "estimated_duration_minutes": 40, "price": 18000, "contrast_required": True, "default_protocol": "Axial T1, T2, FLAIR, DWI; post-Gd T1 axial/sagittal/coronal", "prep_instructions": "MRI safety screening. Check renal function (eGFR). Remove all metal."},
    {"code": "MRI-BRAIN-MRA", "name": "MRI Brain with MRA", "modality_type": "mri", "body_region": "Brain", "estimated_duration_minutes": 45, "price": 20000, "contrast_required": False, "default_protocol": "Standard brain protocol + 3D TOF MRA Circle of Willis", "prep_instructions": "MRI safety screening. Remove all metal objects."},
    {"code": "MRI-PITUITARY", "name": "MRI Pituitary / Sella", "modality_type": "mri", "body_region": "Brain", "estimated_duration_minutes": 35, "price": 18000, "contrast_required": True, "default_protocol": "Thin-section coronal T1, T2; dynamic post-contrast coronal", "prep_instructions": "MRI safety screening. Check renal function."},
    {"code": "MRI-IAM", "name": "MRI Internal Auditory Meatus", "modality_type": "mri", "body_region": "Head", "estimated_duration_minutes": 30, "price": 18000, "contrast_required": True, "default_protocol": "High-resolution T2 (CISS/FIESTA) + post-contrast T1", "prep_instructions": "MRI safety screening. Remove hearing aids."},
    {"code": "MRI-ORBIT", "name": "MRI Orbits", "modality_type": "mri", "body_region": "Head", "estimated_duration_minutes": 30, "price": 18000, "contrast_required": True, "default_protocol": "Fat-sat T1, T2 axial and coronal; post-contrast fat-sat T1", "prep_instructions": "MRI safety screening. Remove contact lenses."},
    {"code": "MRI-NECK", "name": "MRI Neck (Soft Tissue)", "modality_type": "mri", "body_region": "Neck", "estimated_duration_minutes": 35, "price": 18000, "contrast_required": True, "default_protocol": "Axial T1, T2 fat-sat; Coronal STIR; Post-Gd fat-sat T1", "prep_instructions": "MRI safety screening. Remove necklaces."},
    {"code": "MRI-CSPINE", "name": "MRI Cervical Spine", "modality_type": "mri", "body_region": "Spine - Cervical", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, T2; Axial T2 GRE", "prep_instructions": "MRI safety screening. Remove necklaces and collar."},
    {"code": "MRI-TSPINE", "name": "MRI Thoracic Spine", "modality_type": "mri", "body_region": "Spine - Thoracic", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, T2; Axial T2", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-LSPINE", "name": "MRI Lumbar Spine", "modality_type": "mri", "body_region": "Spine - Lumbar", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, T2; Axial T2 at disc levels", "prep_instructions": "MRI safety screening. Remove belt."},
    {"code": "MRI-WSPINE", "name": "MRI Whole Spine", "modality_type": "mri", "body_region": "Spine - Full", "estimated_duration_minutes": 50, "price": 22000, "contrast_required": False, "default_protocol": "Sagittal T1, T2, STIR whole spine; axial at key levels", "prep_instructions": "MRI safety screening. Session may take 45-60 minutes."},
    {"code": "MRI-SHOULDER-R", "name": "MRI Shoulder (Right)", "modality_type": "mri", "body_region": "Shoulder", "estimated_duration_minutes": 35, "price": 15000, "contrast_required": False, "default_protocol": "Coronal oblique T1, PD fat-sat; Axial PD fat-sat; Sagittal T2", "prep_instructions": "MRI safety screening. Remove all jewelry."},
    {"code": "MRI-SHOULDER-L", "name": "MRI Shoulder (Left)", "modality_type": "mri", "body_region": "Shoulder", "estimated_duration_minutes": 35, "price": 15000, "contrast_required": False, "default_protocol": "Coronal oblique T1, PD fat-sat; Axial PD fat-sat; Sagittal T2", "prep_instructions": "MRI safety screening. Remove all jewelry."},
    {"code": "MRI-KNEE-R", "name": "MRI Knee (Right)", "modality_type": "mri", "body_region": "Knee", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal PD fat-sat, T1; Coronal PD fat-sat; Axial PD fat-sat", "prep_instructions": "MRI safety screening. Remove knee brace."},
    {"code": "MRI-KNEE-L", "name": "MRI Knee (Left)", "modality_type": "mri", "body_region": "Knee", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal PD fat-sat, T1; Coronal PD fat-sat; Axial PD fat-sat", "prep_instructions": "MRI safety screening. Remove knee brace."},
    {"code": "MRI-HIP-R", "name": "MRI Hip (Right)", "modality_type": "mri", "body_region": "Hip", "estimated_duration_minutes": 35, "price": 15000, "contrast_required": False, "default_protocol": "Coronal T1, STIR; Axial PD fat-sat; Sagittal T2", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-HIP-L", "name": "MRI Hip (Left)", "modality_type": "mri", "body_region": "Hip", "estimated_duration_minutes": 35, "price": 15000, "contrast_required": False, "default_protocol": "Coronal T1, STIR; Axial PD fat-sat; Sagittal T2", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-ANKLE-R", "name": "MRI Ankle (Right)", "modality_type": "mri", "body_region": "Ankle", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, PD fat-sat; Axial PD fat-sat; Coronal STIR", "prep_instructions": "MRI safety screening. Remove shoes."},
    {"code": "MRI-ANKLE-L", "name": "MRI Ankle (Left)", "modality_type": "mri", "body_region": "Ankle", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, PD fat-sat; Axial PD fat-sat; Coronal STIR", "prep_instructions": "MRI safety screening. Remove shoes."},
    {"code": "MRI-WRIST-R", "name": "MRI Wrist (Right)", "modality_type": "mri", "body_region": "Wrist", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Coronal T1, PD fat-sat; Axial T2; Sagittal T1", "prep_instructions": "MRI safety screening. Remove watches and rings."},
    {"code": "MRI-WRIST-L", "name": "MRI Wrist (Left)", "modality_type": "mri", "body_region": "Wrist", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Coronal T1, PD fat-sat; Axial T2; Sagittal T1", "prep_instructions": "MRI safety screening. Remove watches and rings."},
    {"code": "MRI-ELBOW-R", "name": "MRI Elbow (Right)", "modality_type": "mri", "body_region": "Elbow", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, T2; Axial PD fat-sat; Coronal STIR", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-ELBOW-L", "name": "MRI Elbow (Left)", "modality_type": "mri", "body_region": "Elbow", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal T1, T2; Axial PD fat-sat; Coronal STIR", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-ABDOMEN", "name": "MRI Abdomen", "modality_type": "mri", "body_region": "Abdomen", "estimated_duration_minutes": 40, "price": 18000, "contrast_required": True, "default_protocol": "Axial T1 in/out phase, T2, DWI; Dynamic post-Gd", "prep_instructions": "MRI safety screening. NPO 4 hours. Check eGFR."},
    {"code": "MRI-LIVER", "name": "MRI Liver (Hepatocyte-Specific)", "modality_type": "mri", "body_region": "Abdomen", "estimated_duration_minutes": 45, "price": 20000, "contrast_required": True, "default_protocol": "Multiphase dynamic + hepatobiliary phase at 20min", "prep_instructions": "MRI safety screening. NPO 6 hours. Check eGFR."},
    {"code": "MRI-MRCP", "name": "MRI MRCP (Cholangiopancreatography)", "modality_type": "mri", "body_region": "Abdomen", "estimated_duration_minutes": 35, "price": 18000, "contrast_required": False, "default_protocol": "Coronal thick-slab T2 + 3D thin-section T2", "prep_instructions": "MRI safety screening. NPO 6 hours."},
    {"code": "MRI-PELVIS", "name": "MRI Pelvis", "modality_type": "mri", "body_region": "Pelvis", "estimated_duration_minutes": 40, "price": 18000, "contrast_required": True, "default_protocol": "Axial T1, T2; Sagittal T2; DWI; Post-Gd T1", "prep_instructions": "MRI safety screening. Moderately full bladder. Check eGFR."},
    {"code": "MRI-PROSTATE", "name": "MRI Prostate (Multiparametric)", "modality_type": "mri", "body_region": "Pelvis", "estimated_duration_minutes": 45, "price": 22000, "contrast_required": True, "default_protocol": "T2 multiplanar, DWI (high b-value), DCE", "prep_instructions": "MRI safety screening. Fleet enema 2hrs before. Moderately full bladder. Check eGFR."},
    {"code": "MRI-BREAST-BI", "name": "MRI Breast (Bilateral)", "modality_type": "mri", "body_region": "Chest", "estimated_duration_minutes": 40, "price": 22000, "contrast_required": True, "default_protocol": "Dynamic contrast-enhanced bilateral, subtraction images", "prep_instructions": "MRI safety screening. Day 7-14 of menstrual cycle if premenopausal. Check eGFR."},
    {"code": "MRI-CARDIAC", "name": "MRI Cardiac", "modality_type": "mri", "body_region": "Chest", "estimated_duration_minutes": 60, "price": 25000, "contrast_required": True, "default_protocol": "Cine SSFP, T1/T2 mapping, LGE", "prep_instructions": "MRI safety screening. Check eGFR. No caffeine 24hrs prior."},
    {"code": "MRI-BRACHIAL", "name": "MRI Brachial Plexus", "modality_type": "mri", "body_region": "Neck", "estimated_duration_minutes": 40, "price": 18000, "contrast_required": True, "default_protocol": "Coronal STIR, axial T1 and T2; post-Gd fat-sat T1", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-SI-JOINTS", "name": "MRI Sacroiliac Joints", "modality_type": "mri", "body_region": "Pelvis", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Coronal oblique T1, STIR; Axial T1", "prep_instructions": "MRI safety screening."},
    {"code": "MRI-TMJ", "name": "MRI Temporomandibular Joints", "modality_type": "mri", "body_region": "Head", "estimated_duration_minutes": 30, "price": 15000, "contrast_required": False, "default_protocol": "Sagittal oblique PD open/closed mouth; Coronal T1", "prep_instructions": "MRI safety screening. Remove dental retainers if removable."},

    # ── Ultrasound ────────────────────────────────────────────────────
    {"code": "US-ABDOMEN", "name": "Ultrasound Abdomen (Complete)", "modality_type": "ultrasound", "body_region": "Abdomen", "estimated_duration_minutes": 30, "price": 5000, "contrast_required": False, "default_protocol": "Liver, gallbladder, pancreas, spleen, kidneys, aorta", "prep_instructions": "NPO 6-8 hours before exam."},
    {"code": "US-LIVER", "name": "Ultrasound Liver", "modality_type": "ultrasound", "body_region": "Abdomen", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Liver parenchyma, hepatic vasculature, biliary system", "prep_instructions": "NPO 6 hours before exam."},
    {"code": "US-RENAL", "name": "Ultrasound Renal (Both Kidneys)", "modality_type": "ultrasound", "body_region": "Abdomen", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Both kidneys, long and transverse; measure size", "prep_instructions": "Drink water 1 hour before to fill bladder."},
    {"code": "US-PELVIS-F", "name": "Ultrasound Pelvis (Female/Transabdominal)", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 25, "price": 4000, "contrast_required": False, "default_protocol": "Uterus, ovaries, cul-de-sac", "prep_instructions": "Full bladder required — drink 4-5 glasses of water 1 hour before."},
    {"code": "US-TVS", "name": "Ultrasound Transvaginal", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 20, "price": 4500, "contrast_required": False, "default_protocol": "Uterus, endometrium, ovaries, adnexa", "prep_instructions": "Empty bladder before exam."},
    {"code": "US-OBS-1ST", "name": "Obstetric Ultrasound (1st Trimester)", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 20, "price": 4000, "contrast_required": False, "default_protocol": "CRL, fetal heart activity, gestational sac, yolk sac", "prep_instructions": "Full bladder required for transabdominal approach."},
    {"code": "US-OBS-2ND", "name": "Obstetric Ultrasound (2nd Trimester / Anomaly Scan)", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 40, "price": 6000, "contrast_required": False, "default_protocol": "Detailed fetal anatomy survey, biometry, placenta, AFI", "prep_instructions": "No special preparation. Moderately full bladder helpful."},
    {"code": "US-OBS-3RD", "name": "Obstetric Ultrasound (3rd Trimester / Growth)", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 30, "price": 5000, "contrast_required": False, "default_protocol": "Fetal biometry, AFI, presentation, placenta, EFW", "prep_instructions": "No special preparation required."},
    {"code": "US-THYROID", "name": "Ultrasound Thyroid", "modality_type": "ultrasound", "body_region": "Neck", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Both lobes, isthmus, cervical lymph nodes", "prep_instructions": "No special preparation. Remove necklaces."},
    {"code": "US-BREAST-BI", "name": "Ultrasound Breast (Bilateral)", "modality_type": "ultrasound", "body_region": "Chest", "estimated_duration_minutes": 25, "price": 4000, "contrast_required": False, "default_protocol": "Both breasts and axillae, radial and anti-radial scanning", "prep_instructions": "No special preparation. Do not apply lotions or powders."},
    {"code": "US-BREAST-R", "name": "Ultrasound Breast (Right)", "modality_type": "ultrasound", "body_region": "Chest", "estimated_duration_minutes": 15, "price": 3000, "contrast_required": False, "default_protocol": "Right breast and axilla", "prep_instructions": "No special preparation."},
    {"code": "US-BREAST-L", "name": "Ultrasound Breast (Left)", "modality_type": "ultrasound", "body_region": "Chest", "estimated_duration_minutes": 15, "price": 3000, "contrast_required": False, "default_protocol": "Left breast and axilla", "prep_instructions": "No special preparation."},
    {"code": "US-SCROTUM", "name": "Ultrasound Scrotum / Testes", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Both testes, epididymis, colour Doppler", "prep_instructions": "No special preparation."},
    {"code": "US-PROSTATE-TR", "name": "Ultrasound Prostate (Transrectal)", "modality_type": "ultrasound", "body_region": "Pelvis", "estimated_duration_minutes": 25, "price": 5000, "contrast_required": False, "default_protocol": "Transrectal sagittal and axial prostate volume", "prep_instructions": "Fleet enema 2 hours before exam."},
    {"code": "US-MSK-SHOULDER", "name": "Ultrasound Shoulder", "modality_type": "ultrasound", "body_region": "Shoulder", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Rotator cuff tendons, biceps tendon, subacromial bursa", "prep_instructions": "No special preparation. Wear loose clothing."},
    {"code": "US-MSK-KNEE", "name": "Ultrasound Knee", "modality_type": "ultrasound", "body_region": "Knee", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Suprapatellar recess, patellar tendon, collateral ligaments", "prep_instructions": "No special preparation."},
    {"code": "US-MSK-ANKLE", "name": "Ultrasound Ankle / Achilles", "modality_type": "ultrasound", "body_region": "Ankle", "estimated_duration_minutes": 20, "price": 3500, "contrast_required": False, "default_protocol": "Achilles tendon, ankle tendons, ligaments", "prep_instructions": "No special preparation."},
    {"code": "US-CAROTID", "name": "Ultrasound Carotid Doppler", "modality_type": "ultrasound", "body_region": "Neck", "estimated_duration_minutes": 25, "price": 5000, "contrast_required": False, "default_protocol": "B-mode, colour & spectral Doppler CCA, ICA, ECA, vertebral arteries", "prep_instructions": "No special preparation. Remove necklaces."},
    {"code": "US-VENOUS-LE", "name": "Ultrasound Venous Doppler (Lower Extremity)", "modality_type": "ultrasound", "body_region": "Lower Extremity", "estimated_duration_minutes": 25, "price": 5000, "contrast_required": False, "default_protocol": "Compression ultrasound CFV, SFV, popliteal, calf veins", "prep_instructions": "No special preparation. Wear shorts or loose pants."},
    {"code": "US-ARTERIAL-LE", "name": "Ultrasound Arterial Doppler (Lower Extremity)", "modality_type": "ultrasound", "body_region": "Lower Extremity", "estimated_duration_minutes": 30, "price": 5000, "contrast_required": False, "default_protocol": "ABI + spectral Doppler CFA, SFA, popliteal, tibial arteries", "prep_instructions": "No special preparation."},
    {"code": "US-SOFT-TISSUE", "name": "Ultrasound Soft Tissue / Lump", "modality_type": "ultrasound", "body_region": "Whole Body", "estimated_duration_minutes": 15, "price": 3000, "contrast_required": False, "default_protocol": "Targeted scan of palpable lump with Doppler", "prep_instructions": "No special preparation. Mark lump location if needed."},
    {"code": "US-NEONATAL-HEAD", "name": "Ultrasound Neonatal Head", "modality_type": "ultrasound", "body_region": "Head", "estimated_duration_minutes": 20, "price": 4000, "contrast_required": False, "default_protocol": "Coronal and sagittal views through anterior fontanelle", "prep_instructions": "No special preparation."},
    {"code": "US-ELASTOGRAPHY", "name": "Ultrasound Liver Elastography (FibroScan)", "modality_type": "ultrasound", "body_region": "Abdomen", "estimated_duration_minutes": 15, "price": 5000, "contrast_required": False, "default_protocol": "Shear wave elastography right lobe liver", "prep_instructions": "NPO 2 hours. No alcohol 24hrs before."},

    # ── Mammography ───────────────────────────────────────────────────
    {"code": "MAM-SCREEN", "name": "Screening Mammogram (Bilateral)", "modality_type": "mammogram", "body_region": "Chest", "estimated_duration_minutes": 15, "price": 5000, "contrast_required": False, "default_protocol": "CC and MLO views bilateral", "prep_instructions": "Do not wear deodorant, powder, or lotion under arms or on breasts on the day of the exam."},
    {"code": "MAM-DIAG", "name": "Diagnostic Mammogram", "modality_type": "mammogram", "body_region": "Chest", "estimated_duration_minutes": 20, "price": 6000, "contrast_required": False, "default_protocol": "CC, MLO, spot compression, magnification as needed", "prep_instructions": "Do not wear deodorant, powder, or lotion. Bring prior mammogram films if available."},
    {"code": "MAM-TOMO", "name": "Tomosynthesis (3D Mammogram)", "modality_type": "mammogram", "body_region": "Chest", "estimated_duration_minutes": 20, "price": 8000, "contrast_required": False, "default_protocol": "3D tomosynthesis CC and MLO bilateral", "prep_instructions": "Do not wear deodorant, powder, or lotion."},

    # ── Fluoroscopy ───────────────────────────────────────────────────
    {"code": "FL-BARIUM-SWALLOW", "name": "Barium Swallow", "modality_type": "fluoroscopy", "body_region": "Neck", "estimated_duration_minutes": 20, "price": 5000, "contrast_required": True, "default_protocol": "AP and lateral views during barium swallow", "prep_instructions": "NPO 8 hours. No smoking morning of exam."},
    {"code": "FL-BARIUM-MEAL", "name": "Barium Meal", "modality_type": "fluoroscopy", "body_region": "Abdomen", "estimated_duration_minutes": 30, "price": 6000, "contrast_required": True, "default_protocol": "Double-contrast upper GI series", "prep_instructions": "NPO 8 hours. No smoking morning of exam."},
    {"code": "FL-BARIUM-ENEMA", "name": "Barium Enema", "modality_type": "fluoroscopy", "body_region": "Abdomen", "estimated_duration_minutes": 30, "price": 6000, "contrast_required": True, "default_protocol": "Double-contrast barium enema", "prep_instructions": "Bowel preparation day before. Clear fluids only. Fleet enema morning of exam."},
    {"code": "FL-HSG", "name": "Hysterosalpingography (HSG)", "modality_type": "fluoroscopy", "body_region": "Pelvis", "estimated_duration_minutes": 20, "price": 8000, "contrast_required": True, "default_protocol": "Fluoroscopic imaging during contrast injection", "prep_instructions": "Schedule day 6-11 of menstrual cycle. Take ibuprofen 1hr before. Pregnancy test required."},
    {"code": "FL-IVP", "name": "Intravenous Pyelogram (IVP)", "modality_type": "fluoroscopy", "body_region": "Abdomen", "estimated_duration_minutes": 45, "price": 8000, "contrast_required": True, "default_protocol": "Scout, immediate, 5, 10, 20 min films, post-void", "prep_instructions": "NPO 6 hours. Bowel prep day before. Check renal function."},
    {"code": "FL-MCU", "name": "Micturating Cystourethrogram (MCU/VCUG)", "modality_type": "fluoroscopy", "body_region": "Pelvis", "estimated_duration_minutes": 25, "price": 6000, "contrast_required": True, "default_protocol": "Catheter insertion, bladder filling, voiding phase", "prep_instructions": "No special preparation. Prophylactic antibiotics may be given."},
    {"code": "FL-FISTULOGRAM", "name": "Fistulogram / Sinogram", "modality_type": "fluoroscopy", "body_region": "Whole Body", "estimated_duration_minutes": 20, "price": 5000, "contrast_required": True, "default_protocol": "Contrast injection into fistula tract under fluoroscopy", "prep_instructions": "No special preparation."},

    # ── PET-CT ────────────────────────────────────────────────────────
    {"code": "PET-FDG-WB", "name": "PET-CT FDG Whole Body", "modality_type": "pet_ct", "body_region": "Whole Body", "estimated_duration_minutes": 90, "price": 80000, "contrast_required": False, "default_protocol": "FDG injection, 60-90 min uptake, skull base to mid-thigh", "prep_instructions": "NPO 6 hours. Blood glucose <200mg/dL. No strenuous exercise 24hrs before. Arrive 2hrs early for injection."},
    {"code": "PET-FDG-BRAIN", "name": "PET-CT FDG Brain", "modality_type": "pet_ct", "body_region": "Brain", "estimated_duration_minutes": 60, "price": 70000, "contrast_required": False, "default_protocol": "FDG injection, 30-45 min uptake, dedicated brain acquisition", "prep_instructions": "NPO 4 hours. Quiet room during uptake. No reading or talking."},

    # ── DEXA ──────────────────────────────────────────────────────────
    {"code": "DEXA-SPINE", "name": "DEXA Bone Density (Lumbar Spine)", "modality_type": "dexa", "body_region": "Spine - Lumbar", "estimated_duration_minutes": 10, "price": 5000, "contrast_required": False, "default_protocol": "PA lumbar spine L1-L4", "prep_instructions": "No calcium supplements 24hrs before. Remove metal belt buckle."},
    {"code": "DEXA-HIP", "name": "DEXA Bone Density (Hip)", "modality_type": "dexa", "body_region": "Hip", "estimated_duration_minutes": 10, "price": 5000, "contrast_required": False, "default_protocol": "Proximal femur, neck, trochanter, Ward's triangle", "prep_instructions": "No calcium supplements 24hrs before."},
    {"code": "DEXA-BOTH", "name": "DEXA Bone Density (Spine + Hip)", "modality_type": "dexa", "body_region": "Whole Body", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "PA lumbar spine L1-L4 + proximal femur bilateral", "prep_instructions": "No calcium supplements 24hrs before. No barium studies in prior 7 days."},
    {"code": "DEXA-FOREARM", "name": "DEXA Bone Density (Forearm)", "modality_type": "dexa", "body_region": "Upper Extremity", "estimated_duration_minutes": 10, "price": 4000, "contrast_required": False, "default_protocol": "Non-dominant forearm distal 1/3 radius", "prep_instructions": "Remove watches and bracelets."},
    {"code": "DEXA-WB-COMP", "name": "DEXA Whole Body Composition", "modality_type": "dexa", "body_region": "Whole Body", "estimated_duration_minutes": 15, "price": 8000, "contrast_required": False, "default_protocol": "Whole body scan for fat, lean, bone mass", "prep_instructions": "Wear light clothing. Remove all metal objects."},

    # ── Other / Interventional ────────────────────────────────────────
    {"code": "IR-US-BIOPSY", "name": "Ultrasound-Guided Biopsy", "modality_type": "other", "body_region": "Whole Body", "estimated_duration_minutes": 30, "price": 10000, "contrast_required": False, "default_protocol": "Real-time US guidance, core biopsy needle", "prep_instructions": "Check coagulation profile. NPO 4 hours. Consent form required."},
    {"code": "IR-CT-BIOPSY", "name": "CT-Guided Biopsy", "modality_type": "other", "body_region": "Whole Body", "estimated_duration_minutes": 45, "price": 15000, "contrast_required": False, "default_protocol": "Intermittent CT guidance, coaxial technique", "prep_instructions": "Check coagulation profile. NPO 6 hours. Consent form required."},
    {"code": "IR-US-DRAIN", "name": "Ultrasound-Guided Drainage", "modality_type": "other", "body_region": "Whole Body", "estimated_duration_minutes": 30, "price": 12000, "contrast_required": False, "default_protocol": "US-guided catheter drainage, Seldinger technique", "prep_instructions": "Check coagulation profile. NPO 4 hours. Consent required."},
    {"code": "IR-PICC", "name": "PICC Line Insertion (Image-Guided)", "modality_type": "other", "body_region": "Upper Extremity", "estimated_duration_minutes": 30, "price": 10000, "contrast_required": False, "default_protocol": "US-guided basilic/brachial vein access, fluoroscopic tip confirmation", "prep_instructions": "No special preparation. Consent required."},
    {"code": "IR-FNA-THYROID", "name": "Thyroid FNA (US-Guided)", "modality_type": "other", "body_region": "Neck", "estimated_duration_minutes": 20, "price": 8000, "contrast_required": False, "default_protocol": "US-guided fine needle aspiration, 25G needle", "prep_instructions": "Hold aspirin/anticoagulants if advised. No fasting required."},
    {"code": "IR-JOINT-INJ", "name": "Image-Guided Joint Injection", "modality_type": "other", "body_region": "Whole Body", "estimated_duration_minutes": 20, "price": 8000, "contrast_required": False, "default_protocol": "US or fluoroscopic guidance, steroid/anesthetic injection", "prep_instructions": "Inform if diabetic (steroids may raise blood sugar). Consent required."},
]


class Command(BaseCommand):
    help = 'Seed ExamCatalog with standard radiology exams'

    def add_arguments(self, parser):
        parser.add_argument('--clear', action='store_true', help='Delete all existing exams before seeding')
        parser.add_argument('--reset', action='store_true', help='Alias for --clear')

    def handle(self, *args, **options):
        if options['clear'] or options['reset']:
            count = ExamCatalog.objects.all().delete()[0]
            self.stdout.write(self.style.WARNING(f'Deleted {count} existing catalog entries.'))

        created = 0
        skipped = 0
        for entry in EXAMS:
            _, was_created = ExamCatalog.objects.get_or_create(
                code=entry['code'],
                defaults=entry,
            )
            if was_created:
                created += 1
            else:
                skipped += 1

        self.stdout.write(self.style.SUCCESS(
            f'Done — {created} exams created, {skipped} skipped (already exist). '
            f'Total catalog size: {ExamCatalog.objects.count()}'
        ))
