"""
Per-request usage billing models.

Lives in the PUBLIC schema (SHARED_APPS) so that:
  * super admins can see usage across every tenant
  * each tenant can read its own rows
  * the tracking middleware writes regardless of which tenant schema is active
"""
from decimal import Decimal

from django.conf import settings
from django.db import models
from django.utils import timezone


class BillingRate(models.Model):
    """
    Pricing for metered API requests.

    Default: 1000 requests = 1 KSH.
    The currently-active rate is the most recent row with `is_active=True`
    whose `effective_from` is in the past.
    """

    requests_per_unit = models.PositiveIntegerField(
        default=1000,
        help_text="How many requests are billed as one cost unit.",
    )
    unit_cost = models.DecimalField(
        max_digits=12,
        decimal_places=4,
        default=Decimal("1.0000"),
        help_text="Cost per `requests_per_unit` block.",
    )
    currency = models.CharField(max_length=8, default="KSH")
    effective_from = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="usage_rates_created",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-effective_from", "-id"]

    def __str__(self):
        return f"{self.requests_per_unit} req = {self.unit_cost} {self.currency}"

    def cost_for(self, request_count: int) -> Decimal:
        if not self.requests_per_unit:
            return Decimal("0")
        units = Decimal(request_count) / Decimal(self.requests_per_unit)
        return (units * self.unit_cost).quantize(Decimal("0.0001"))

    @classmethod
    def current(cls):
        now = timezone.now()
        rate = (
            cls.objects.filter(is_active=True, effective_from__lte=now)
            .order_by("-effective_from", "-id")
            .first()
        )
        if rate:
            return rate
        return cls.objects.create(
            requests_per_unit=1000,
            unit_cost=Decimal("1.0000"),
            currency="KSH",
            notes="Auto-created default rate",
        )


class DailyUsage(models.Model):
    """One row per (tenant, date). Incremented by the request middleware."""

    tenant = models.ForeignKey(
        "tenants.Tenant",
        on_delete=models.CASCADE,
        related_name="usage_days",
    )
    date = models.DateField()
    request_count = models.PositiveIntegerField(default=0)
    lab_request_count = models.PositiveIntegerField(
        default=0,
        help_text="Subset of request_count that hit /api/lab/* endpoints.",
    )
    last_updated = models.DateTimeField(auto_now=True)

    class Meta:
        unique_together = ("tenant", "date")
        ordering = ["-date"]
        indexes = [
            models.Index(fields=["tenant", "date"]),
        ]

    def __str__(self):
        return f"{self.tenant.schema_name} {self.date}: {self.request_count}"


class MonthlyBill(models.Model):
    """
    Aggregated bill for a tenant for a calendar month.
    Generated by an admin action (or scheduled job).
    """

    class Status(models.TextChoices):
        DRAFT = "DRAFT", "Draft"
        ISSUED = "ISSUED", "Issued"
        PAID = "PAID", "Paid"
        CANCELLED = "CANCELLED", "Cancelled"

    tenant = models.ForeignKey(
        "tenants.Tenant",
        on_delete=models.CASCADE,
        related_name="usage_bills",
    )
    year = models.PositiveSmallIntegerField()
    month = models.PositiveSmallIntegerField()
    total_requests = models.PositiveIntegerField(default=0)
    requests_per_unit = models.PositiveIntegerField()
    unit_cost = models.DecimalField(max_digits=12, decimal_places=4)
    amount = models.DecimalField(max_digits=14, decimal_places=4, default=Decimal("0"))
    currency = models.CharField(max_length=8, default="KSH")
    status = models.CharField(max_length=12, choices=Status.choices, default=Status.ISSUED)
    generated_at = models.DateTimeField(auto_now_add=True)
    paid_at = models.DateTimeField(null=True, blank=True)
    notes = models.TextField(blank=True)

    class Meta:
        unique_together = ("tenant", "year", "month")
        ordering = ["-year", "-month"]

    def __str__(self):
        return f"{self.tenant.schema_name} {self.year}-{self.month:02d}: {self.amount} {self.currency}"


class DoctorCommissionRate(models.Model):
    """Platform commission charged on each consultation, as a percentage of the
    doctor's consultation fee. Default 20%. Patients are never billed."""

    percentage = models.DecimalField(
        max_digits=5,
        decimal_places=2,
        default=Decimal("20.00"),
        help_text="Commission % of the consultation fee charged to the doctor.",
    )
    currency = models.CharField(max_length=8, default="KSH")
    effective_from = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    notes = models.TextField(blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="doctor_commission_rates_created",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-effective_from", "-id"]

    def __str__(self):
        return f"{self.percentage}% commission"

    def commission_for(self, fee_total) -> Decimal:
        return (Decimal(fee_total) * self.percentage / Decimal("100")).quantize(Decimal("0.01"))

    @classmethod
    def current(cls):
        now = timezone.now()
        rate = (
            cls.objects.filter(is_active=True, effective_from__lte=now)
            .order_by("-effective_from", "-id")
            .first()
        )
        if rate:
            return rate
        return cls.objects.create(
            percentage=Decimal("20.00"),
            currency="KSH",
            notes="Auto-created default commission rate",
        )
