# Generated by Django 6.0.4 on 2026-04-09 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicationstock',
            name='medication_id',
            field=models.CharField(blank=True, help_text='Auto-generated unique medication ID', max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField(help_text='Positive for additions, negative for removals')),
                ('reason', models.CharField(choices=[('damage', 'Damage'), ('theft', 'Theft'), ('expiry', 'Expiry'), ('count_correction', 'Count Correction'), ('return_to_supplier', 'Return to Supplier'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjusted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_adjustments', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustments', to='inventory.stockbatch')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='inventory.medicationstock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
