# Generated by Django 6.0.4 on 2026-04-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_unit_medicationstock_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='barcode',
            field=models.CharField(blank=True, help_text='Barcode or SKU', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicationstock',
            name='prescription_required',
            field=models.CharField(choices=[('none', 'None'), ('recommended', 'Recommended'), ('required', 'Required')], default='none', help_text='Whether a doctor prescription is needed', max_length=20),
        ),
    ]
