# Generated by Django 6.0.4 on 2026-05-07 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_medicationstock_abbreviation'),
        ('pharmacy_profile', '0004_add_branch_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Physical location of this batch. Null = main / unassigned.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='pharmacy_profile.branch'),
        ),
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('name', models.CharField(help_text='e.g. "Monthly count - May 2026"', max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to='pharmacy_profile.branch')),
                ('category', models.ForeignKey(blank=True, help_text='Optional: limit count to a single category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_counts', to='inventory.category')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_counts', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('approved', 'Approved'), ('in_transit', 'In Transit'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to=settings.AUTH_USER_MODEL)),
                ('dest_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='pharmacy_profile.branch')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transfers', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to=settings.AUTH_USER_MODEL)),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='pharmacy_profile.branch')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='How much actually arrived')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_lines', to='inventory.medicationstock')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.stocktransfer')),
            ],
            options={
                'ordering': ['stock__medication_name'],
            },
        ),
        migrations.CreateModel(
            name='ControlledSubstanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=255)),
                ('schedule', models.CharField(blank=True, help_text='e.g. Schedule II, III', max_length=20)),
                ('action', models.CharField(choices=[('dispensed', 'Dispensed'), ('received', 'Received'), ('adjusted', 'Adjusted'), ('destroyed', 'Destroyed'), ('transferred', 'Transferred'), ('returned', 'Returned')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_id_number', models.CharField(blank=True, help_text='National ID, passport, etc.', max_length=50)),
                ('prescriber_name', models.CharField(blank=True, max_length=255)),
                ('prescription_reference', models.CharField(blank=True, max_length=100)),
                ('source_type', models.CharField(blank=True, help_text='dispense, adjustment, transfer, etc.', max_length=30)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controlled_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['medication_name', '-created_at'], name='inventory_c_medicat_fdbecc_idx'), models.Index(fields=['action', '-created_at'], name='inventory_c_action_a73c1b_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.IntegerField(default=0, help_text='System qty at the time the sheet was generated')),
                ('counted_quantity', models.IntegerField(blank=True, help_text='Physical count', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.inventorycount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='count_lines', to='inventory.medicationstock')),
            ],
            options={
                'ordering': ['stock__medication_name'],
                'unique_together': {('count', 'stock')},
            },
        ),
    ]
