# Generated by Django 6.0.4 on 2026-05-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_stockbatch_branch_inventorycount_stocktransfer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='VAT / tax percentage applied on cost price (0–100)', max_digits=5),
        ),
    ]
