# Generated by Django 6.0.4 on 2026-05-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_add_tax_percent_to_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbatch',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
