# Generated by Django 6.0.4 on 2026-05-21 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_make_expiry_date_optional'),
        ('pharmacy_profile', '0009_increase_lat_lng_max_digits_to_30'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch this stock item belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocks', to='pharmacy_profile.branch'),
        ),
    ]
