# Generated by Django 6.0.4 on 2026-09-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_add_branch_to_medicationstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationstock',
            name='committed_qty',
            field=models.PositiveIntegerField(default=0, help_text='Quantity reserved by paid/partially-paid sales orders (not yet delivered)'),
        ),
    ]
