# Generated by Django 6.0.4 on 2026-09-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_medicationstock_committed_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('damage', 'Damage'), ('theft', 'Theft'), ('expiry', 'Expiry'), ('count_correction', 'Count Correction'), ('return_to_supplier', 'Return to Supplier'), ('sales_order', 'Sales Order Fulfilment'), ('other', 'Other')], max_length=30),
        ),
    ]
