# Generated by Django 6.0.4 on 2026-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_require_branch_on_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='mdi-badge-account-horizontal-outline', max_length=50)),
                ('capabilities', models.JSONField(default=list, help_text='List of capability keys (see rbac.py)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Role definition',
                'verbose_name_plural': 'Role definitions',
                'ordering': ['label'],
            },
        ),
    ]
