# Generated by Django 6.0.4 on 2026-09-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_roledefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledefinition',
            name='is_system',
            field=models.BooleanField(default=False, help_text='True = capability override for a built-in role'),
        ),
    ]
