# Generated by Django 6.0.4 on 2026-04-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_exchange_id', models.IntegerField(blank=True, help_text='FK to PrescriptionExchange (public schema)', null=True)),
                ('patient_user_id', models.IntegerField(help_text='FK to User (public schema)')),
                ('patient_name', models.CharField(max_length=255)),
                ('items_dispensed', models.JSONField(default=list, help_text='[{medication, qty, batch, price}]')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('dispensed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensing_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
