# Generated by Django 6.0.4 on 2026-05-07 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispensing', '0002_dispensing_pos_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensingrecord',
            name='items_dispensed',
            field=models.JSONField(default=list, help_text='[{stock_id, medication_name, qty, unit_price, line_total, batch_number}]'),
        ),
        migrations.CreateModel(
            name='DispenseReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('items_returned', models.JSONField(default=list, help_text='[{stock_id, medication_name, qty, unit_price, line_total, reason}]')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('refund_method', models.CharField(blank=True, max_length=20)),
                ('reason', models.CharField(choices=[('damaged', 'Damaged / faulty'), ('wrong_item', 'Wrong item dispensed'), ('patient_request', 'Patient changed mind'), ('expired', 'Expired'), ('adverse_reaction', 'Adverse reaction'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('restock', models.BooleanField(default=True, help_text='Add returned items back into stock')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='dispensing.dispensingrecord')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispense_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
