# Generated by Django 6.0.4 on 2026-04-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('clinical_pharmacy', 'Clinical Pharmacy'), ('community_pharmacy', 'Community Pharmacy'), ('hospital_pharmacy', 'Hospital Pharmacy'), ('industrial_pharmacy', 'Industrial Pharmacy'), ('compounding', 'Compounding Pharmacy'), ('pharmacovigilance', 'Pharmacovigilance'), ('oncology_pharmacy', 'Oncology Pharmacy'), ('pediatric_pharmacy', 'Pediatric Pharmacy'), ('geriatric_pharmacy', 'Geriatric Pharmacy'), ('psychiatric_pharmacy', 'Psychiatric Pharmacy'), ('ambulatory_care', 'Ambulatory Care Pharmacy'), ('critical_care', 'Critical Care Pharmacy'), ('infectious_disease', 'Infectious Disease Pharmacy'), ('nuclear_pharmacy', 'Nuclear Pharmacy'), ('nutrition_support', 'Nutrition Support Pharmacy'), ('regulatory_affairs', 'Regulatory Affairs'), ('drug_information', 'Drug Information'), ('dispensing', 'Dispensing'), ('inventory_management', 'Inventory Management'), ('sterile_compounding', 'Sterile Compounding'), ('medication_therapy', 'Medication Therapy Management'), ('pharmacy_billing', 'Pharmacy Billing & Insurance'), ('general', 'General'), ('other', 'Other')], default='', max_length=255),
        ),
    ]
