# Generated by Django 6.0.4 on 2026-04-10 08:41

from django.db import migrations

SPECIALIZATIONS = [
    # Pharmacist specializations
    ('Clinical Pharmacy', 'Patient-oriented pharmaceutical care in clinical settings'),
    ('Community Pharmacy', 'Retail and community-based pharmaceutical services'),
    ('Hospital Pharmacy', 'Pharmacy services within hospital settings'),
    ('Industrial Pharmacy', 'Drug manufacturing and pharmaceutical industry'),
    ('Compounding Pharmacy', 'Custom medication preparation and formulation'),
    ('Pharmacovigilance', 'Drug safety monitoring and adverse event reporting'),
    ('Oncology Pharmacy', 'Cancer treatment and chemotherapy management'),
    ('Pediatric Pharmacy', 'Pharmaceutical care for infants, children, and adolescents'),
    ('Geriatric Pharmacy', 'Pharmaceutical care for elderly patients'),
    ('Psychiatric Pharmacy', 'Mental health and psychotropic medication management'),
    ('Ambulatory Care Pharmacy', 'Outpatient pharmaceutical care and chronic disease management'),
    ('Critical Care Pharmacy', 'Intensive care and emergency pharmaceutical services'),
    ('Infectious Disease Pharmacy', 'Antimicrobial therapy and infection management'),
    ('Nuclear Pharmacy', 'Radiopharmaceutical preparation and dispensing'),
    ('Nutrition Support Pharmacy', 'Parenteral and enteral nutrition therapy'),
    ('Regulatory Affairs', 'Drug regulation, compliance, and quality assurance'),
    ('Drug Information', 'Medication information services and evidence-based guidance'),
    # Pharmacy technician specializations
    ('Dispensing', 'Prescription dispensing and medication distribution'),
    ('Inventory Management', 'Stock control, purchasing, and supply chain management'),
    ('Sterile Compounding', 'Aseptic preparation of sterile medications'),
    ('Medication Therapy Management', 'Patient medication reviews and therapy optimization'),
    ('Pharmacy Billing & Insurance', 'Claims processing, insurance verification, and billing'),
    # General
    ('General', 'General pharmacy practice'),
    ('Other', 'Other specialization not listed'),
]


def seed_specializations(apps, schema_editor):
    Specialization = apps.get_model('staff_profiles', 'Specialization')
    for name, description in SPECIALIZATIONS:
        Specialization.objects.get_or_create(name=name, defaults={'description': description})


def reverse_seed(apps, schema_editor):
    Specialization = apps.get_model('staff_profiles', 'Specialization')
    names = [name for name, _ in SPECIALIZATIONS]
    Specialization.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('staff_profiles', '0003_specialization_alter_staffprofile_specialization'),
    ]

    operations = [
        migrations.RunPython(seed_specializations, reverse_seed),
    ]
