"""
Pharmacy stock seed command — Kenyan market catalog.

Seeds MedicationStock for the current tenant with a comprehensive list of
medications commonly available in the Kenyan market (Kenya Essential
Medicines List + common branded products from local distributors such as
Cosmos, Universal Corporation, Dawa, Beta Healthcare, Laborex, GSK,
Pfizer, Sanofi, Cipla, Ranbaxy, Sun Pharma, Aurobindo, Hetero, Macleods,
Stallion, Regal etc.).

Prices and quantities are intentionally seeded as ZERO — pharmacy staff
must update them with their own buying / selling prices and add real
stock batches. This makes the seed safe to re-run and useful as a true
"catalog of products you can carry".

Usage (single tenant):
    python manage.py tenant_command seed_pharmacy_stock --schema=<schema_name>

Usage (all tenants):
    python manage.py all_tenants_command seed_pharmacy_stock

Flags:
    --skip-existing   Skip items that already exist
    --reset           Delete all existing stock and reseed from scratch
"""

from decimal import Decimal

from django.core.management.base import BaseCommand

from inventory.models import Category, MedicationStock, StockBatch, Unit


# ---------------------------------------------------------------------------
# Categories & units
# ---------------------------------------------------------------------------

CATEGORY_DEFS = [
    "Analgesic / Pain Reliever",
    "Antibiotic",
    "Antifungal",
    "Antiviral",
    "Antiparasitic",
    "Antimalarial",
    "Antituberculosis",
    "Antiretroviral (ARV)",
    "Antihypertensive",
    "Antidiabetic",
    "Antihistamine",
    "Antacid / GI",
    "Cardiovascular",
    "Respiratory",
    "Central Nervous System",
    "Psychiatric",
    "Hormonal",
    "Contraceptive",
    "Vitamin / Supplement",
    "Vaccine",
    "Dermatological",
    "Ophthalmic",
    "ENT (Ear/Nose/Throat)",
    "Emergency / IV Fluids",
    "Anticoagulant",
    "Diuretic",
    "Oncology",
    "Urology",
    "Muscle Relaxant",
    "Anaesthetic",
    "Herbal / Traditional",
    "Nutrition / Infant Formula",
    "First Aid / Wound Care",
    "Medical Device / Consumable",
    "Other",
]

UNIT_DEFS = [
    ("Tablets",     "tab"),
    ("Capsules",    "cap"),
    ("Syrup",       "btl"),
    ("Suspension",  "btl"),
    ("Solution",    "btl"),
    ("Injection",   "inj"),
    ("Vial",        "vial"),
    ("Ampoule",     "amp"),
    ("Cream/Gel",   "tube"),
    ("Ointment",    "tube"),
    ("Lotion",      "btl"),
    ("Drops",       "btl"),
    ("Inhaler",     "inh"),
    ("Nebule",      "neb"),
    ("Suppository", "supp"),
    ("Pessary",     "pes"),
    ("Powder",      "sachet"),
    ("Patch",       "patch"),
    ("IV Bag",      "bag"),
    ("Sachet",      "sachet"),
    ("Bottle",      "btl"),
    ("Box",         "box"),
    ("Piece",       "pc"),
    ("Roll",        "roll"),
]

# ---------------------------------------------------------------------------
# Stock catalog — (medication_name, category, unit)
# Prices, reorder levels and quantities are seeded to zero.
# ---------------------------------------------------------------------------
# fmt: off
STOCK_DATA = [
    # ───────────────── Analgesics / NSAIDs / Antipyretics ─────────────────
    ("Paracetamol 500mg Tablet",                       "Analgesic / Pain Reliever",  "Tablets"),
    ("Paracetamol 1g Tablet",                          "Analgesic / Pain Reliever",  "Tablets"),
    ("Paracetamol 120mg/5ml Syrup",                    "Analgesic / Pain Reliever",  "Syrup"),
    ("Paracetamol 250mg/5ml Syrup",                    "Analgesic / Pain Reliever",  "Syrup"),
    ("Paracetamol 100mg Drops (Infants)",              "Analgesic / Pain Reliever",  "Drops"),
    ("Paracetamol 1g Suppository",                     "Analgesic / Pain Reliever",  "Suppository"),
    ("Paracetamol 1g IV Infusion",                     "Analgesic / Pain Reliever",  "IV Bag"),
    ("Ibuprofen 200mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Ibuprofen 400mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Ibuprofen 600mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Ibuprofen 100mg/5ml Suspension",                 "Analgesic / Pain Reliever",  "Suspension"),
    ("Diclofenac 25mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Diclofenac 50mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Diclofenac 75mg SR Tablet",                      "Analgesic / Pain Reliever",  "Tablets"),
    ("Diclofenac 100mg SR Tablet",                     "Analgesic / Pain Reliever",  "Tablets"),
    ("Diclofenac 75mg/3ml Injection",                  "Analgesic / Pain Reliever",  "Ampoule"),
    ("Diclofenac 100mg Suppository",                   "Analgesic / Pain Reliever",  "Suppository"),
    ("Diclofenac 1% Gel",                              "Analgesic / Pain Reliever",  "Cream/Gel"),
    ("Aceclofenac 100mg Tablet",                       "Analgesic / Pain Reliever",  "Tablets"),
    ("Naproxen 250mg Tablet",                          "Analgesic / Pain Reliever",  "Tablets"),
    ("Naproxen 500mg Tablet",                          "Analgesic / Pain Reliever",  "Tablets"),
    ("Meloxicam 7.5mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Meloxicam 15mg Tablet",                          "Analgesic / Pain Reliever",  "Tablets"),
    ("Piroxicam 20mg Capsule",                         "Analgesic / Pain Reliever",  "Capsules"),
    ("Piroxicam 0.5% Gel",                             "Analgesic / Pain Reliever",  "Cream/Gel"),
    ("Indomethacin 25mg Capsule",                      "Analgesic / Pain Reliever",  "Capsules"),
    ("Ketoprofen 100mg Tablet",                        "Analgesic / Pain Reliever",  "Tablets"),
    ("Ketorolac 10mg Tablet",                          "Analgesic / Pain Reliever",  "Tablets"),
    ("Ketorolac 30mg/ml Injection",                    "Analgesic / Pain Reliever",  "Ampoule"),
    ("Etoricoxib 60mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Etoricoxib 90mg Tablet",                         "Analgesic / Pain Reliever",  "Tablets"),
    ("Etoricoxib 120mg Tablet",                        "Analgesic / Pain Reliever",  "Tablets"),
    ("Celecoxib 100mg Capsule",                        "Analgesic / Pain Reliever",  "Capsules"),
    ("Celecoxib 200mg Capsule",                        "Analgesic / Pain Reliever",  "Capsules"),
    ("Aspirin 75mg Tablet (Cardio)",                   "Cardiovascular",             "Tablets"),
    ("Aspirin 300mg Tablet",                           "Analgesic / Pain Reliever",  "Tablets"),
    ("Mefenamic Acid 250mg Capsule",                   "Analgesic / Pain Reliever",  "Capsules"),
    ("Mefenamic Acid 500mg Capsule",                   "Analgesic / Pain Reliever",  "Capsules"),
    ("Tramadol 50mg Capsule",                          "Analgesic / Pain Reliever",  "Capsules"),
    ("Tramadol 100mg SR Tablet",                       "Analgesic / Pain Reliever",  "Tablets"),
    ("Tramadol 50mg/ml Injection",                     "Analgesic / Pain Reliever",  "Ampoule"),
    ("Tramadol + Paracetamol 37.5/325mg Tablet",       "Analgesic / Pain Reliever",  "Tablets"),
    ("Codeine 30mg Tablet",                            "Analgesic / Pain Reliever",  "Tablets"),
    ("Codeine + Paracetamol 30/500mg Tablet",          "Analgesic / Pain Reliever",  "Tablets"),
    ("Pethidine 50mg/ml Injection",                    "Analgesic / Pain Reliever",  "Ampoule"),
    ("Morphine Sulfate 10mg Tablet",                   "Analgesic / Pain Reliever",  "Tablets"),
    ("Morphine Sulfate 30mg SR Tablet",                "Analgesic / Pain Reliever",  "Tablets"),
    ("Morphine 10mg/ml Injection",                     "Analgesic / Pain Reliever",  "Ampoule"),
    ("Fentanyl 50mcg/ml Injection",                    "Analgesic / Pain Reliever",  "Ampoule"),
    ("Fentanyl 25mcg/hr Patch",                        "Analgesic / Pain Reliever",  "Patch"),
    ("Buprenorphine 0.3mg/ml Injection",               "Analgesic / Pain Reliever",  "Ampoule"),
    ("Methyl Salicylate Liniment",                     "Analgesic / Pain Reliever",  "Cream/Gel"),
    ("Capsaicin 0.025% Cream",                         "Analgesic / Pain Reliever",  "Cream/Gel"),
    ("Hyoscine Butylbromide 10mg Tablet (Buscopan)",   "Analgesic / Pain Reliever",  "Tablets"),
    ("Hyoscine Butylbromide 20mg/ml Injection",        "Analgesic / Pain Reliever",  "Ampoule"),
    ("Drotaverine 40mg Tablet",                        "Analgesic / Pain Reliever",  "Tablets"),

    # ───────────────── Antibiotics ────────────────────────────────────────
    ("Amoxicillin 250mg Capsule",                      "Antibiotic", "Capsules"),
    ("Amoxicillin 500mg Capsule",                      "Antibiotic", "Capsules"),
    ("Amoxicillin 125mg/5ml Syrup",                    "Antibiotic", "Syrup"),
    ("Amoxicillin 250mg/5ml Syrup",                    "Antibiotic", "Syrup"),
    ("Amoxicillin + Clavulanate 625mg Tablet",         "Antibiotic", "Tablets"),
    ("Amoxicillin + Clavulanate 1g Tablet",            "Antibiotic", "Tablets"),
    ("Amoxicillin + Clavulanate 228mg/5ml Syrup",      "Antibiotic", "Syrup"),
    ("Amoxicillin + Clavulanate 457mg/5ml Syrup",      "Antibiotic", "Syrup"),
    ("Amoxicillin + Clavulanate 1.2g Injection",       "Antibiotic", "Vial"),
    ("Ampicillin 500mg Capsule",                       "Antibiotic", "Capsules"),
    ("Ampicillin 500mg Injection",                     "Antibiotic", "Vial"),
    ("Ampicillin + Cloxacillin 500mg Capsule",         "Antibiotic", "Capsules"),
    ("Cloxacillin 250mg Capsule",                      "Antibiotic", "Capsules"),
    ("Cloxacillin 500mg Capsule",                      "Antibiotic", "Capsules"),
    ("Cloxacillin 500mg Injection",                    "Antibiotic", "Vial"),
    ("Flucloxacillin 500mg Capsule",                   "Antibiotic", "Capsules"),
    ("Benzylpenicillin 1MU Injection",                 "Antibiotic", "Vial"),
    ("Benzathine Penicillin 1.2MU Injection",          "Antibiotic", "Vial"),
    ("Procaine Penicillin 4MU Injection",              "Antibiotic", "Vial"),
    ("Phenoxymethylpenicillin 250mg Tablet",           "Antibiotic", "Tablets"),
    ("Cephalexin 250mg Capsule",                       "Antibiotic", "Capsules"),
    ("Cephalexin 500mg Capsule",                       "Antibiotic", "Capsules"),
    ("Cefadroxil 500mg Capsule",                       "Antibiotic", "Capsules"),
    ("Cefuroxime 250mg Tablet",                        "Antibiotic", "Tablets"),
    ("Cefuroxime 500mg Tablet",                        "Antibiotic", "Tablets"),
    ("Cefuroxime 750mg Injection",                     "Antibiotic", "Vial"),
    ("Cefixime 200mg Tablet",                          "Antibiotic", "Tablets"),
    ("Cefixime 400mg Tablet",                          "Antibiotic", "Tablets"),
    ("Cefixime 100mg/5ml Suspension",                  "Antibiotic", "Suspension"),
    ("Cefpodoxime 200mg Tablet",                       "Antibiotic", "Tablets"),
    ("Cefdinir 300mg Capsule",                         "Antibiotic", "Capsules"),
    ("Ceftriaxone 1g Injection",                       "Antibiotic", "Vial"),
    ("Ceftriaxone 2g Injection",                       "Antibiotic", "Vial"),
    ("Ceftazidime 1g Injection",                       "Antibiotic", "Vial"),
    ("Cefotaxime 1g Injection",                        "Antibiotic", "Vial"),
    ("Cefepime 1g Injection",                          "Antibiotic", "Vial"),
    ("Meropenem 500mg Injection",                      "Antibiotic", "Vial"),
    ("Meropenem 1g Injection",                         "Antibiotic", "Vial"),
    ("Imipenem + Cilastatin 500mg Injection",          "Antibiotic", "Vial"),
    ("Piperacillin + Tazobactam 4.5g Injection",       "Antibiotic", "Vial"),
    ("Erythromycin 250mg Tablet",                      "Antibiotic", "Tablets"),
    ("Erythromycin 500mg Tablet",                      "Antibiotic", "Tablets"),
    ("Erythromycin 125mg/5ml Suspension",              "Antibiotic", "Suspension"),
    ("Erythromycin 250mg/5ml Suspension",              "Antibiotic", "Suspension"),
    ("Azithromycin 250mg Tablet",                      "Antibiotic", "Tablets"),
    ("Azithromycin 500mg Tablet",                      "Antibiotic", "Tablets"),
    ("Azithromycin 200mg/5ml Suspension",              "Antibiotic", "Suspension"),
    ("Clarithromycin 250mg Tablet",                    "Antibiotic", "Tablets"),
    ("Clarithromycin 500mg Tablet",                    "Antibiotic", "Tablets"),
    ("Roxithromycin 150mg Tablet",                     "Antibiotic", "Tablets"),
    ("Doxycycline 100mg Capsule",                      "Antibiotic", "Capsules"),
    ("Doxycycline 100mg Tablet",                       "Antibiotic", "Tablets"),
    ("Tetracycline 250mg Capsule",                     "Antibiotic", "Capsules"),
    ("Tetracycline 1% Eye Ointment",                   "Ophthalmic", "Ointment"),
    ("Minocycline 100mg Capsule",                      "Antibiotic", "Capsules"),
    ("Ciprofloxacin 250mg Tablet",                     "Antibiotic", "Tablets"),
    ("Ciprofloxacin 500mg Tablet",                     "Antibiotic", "Tablets"),
    ("Ciprofloxacin 750mg Tablet",                     "Antibiotic", "Tablets"),
    ("Ciprofloxacin 200mg/100ml Infusion",             "Antibiotic", "IV Bag"),
    ("Ciprofloxacin 0.3% Eye Drops",                   "Ophthalmic", "Drops"),
    ("Levofloxacin 250mg Tablet",                      "Antibiotic", "Tablets"),
    ("Levofloxacin 500mg Tablet",                      "Antibiotic", "Tablets"),
    ("Levofloxacin 750mg Tablet",                      "Antibiotic", "Tablets"),
    ("Moxifloxacin 400mg Tablet",                      "Antibiotic", "Tablets"),
    ("Ofloxacin 200mg Tablet",                         "Antibiotic", "Tablets"),
    ("Ofloxacin 0.3% Eye Drops",                       "Ophthalmic", "Drops"),
    ("Norfloxacin 400mg Tablet",                       "Antibiotic", "Tablets"),
    ("Nitrofurantoin 100mg Capsule",                   "Antibiotic", "Capsules"),
    ("Nitrofurantoin 100mg SR Tablet",                 "Antibiotic", "Tablets"),
    ("Trimethoprim 100mg Tablet",                      "Antibiotic", "Tablets"),
    ("Cotrimoxazole 480mg Tablet",                     "Antibiotic", "Tablets"),
    ("Cotrimoxazole 960mg Tablet",                     "Antibiotic", "Tablets"),
    ("Cotrimoxazole 240mg/5ml Suspension",             "Antibiotic", "Suspension"),
    ("Metronidazole 200mg Tablet",                     "Antibiotic", "Tablets"),
    ("Metronidazole 400mg Tablet",                     "Antibiotic", "Tablets"),
    ("Metronidazole 500mg Tablet",                     "Antibiotic", "Tablets"),
    ("Metronidazole 200mg/5ml Suspension",             "Antibiotic", "Suspension"),
    ("Metronidazole 500mg/100ml Infusion",             "Antibiotic", "IV Bag"),
    ("Tinidazole 500mg Tablet",                        "Antibiotic", "Tablets"),
    ("Secnidazole 1g Tablet",                          "Antibiotic", "Tablets"),
    ("Ornidazole 500mg Tablet",                        "Antibiotic", "Tablets"),
    ("Clindamycin 150mg Capsule",                      "Antibiotic", "Capsules"),
    ("Clindamycin 300mg Capsule",                      "Antibiotic", "Capsules"),
    ("Clindamycin 1% Topical Solution",                "Antibiotic", "Solution"),
    ("Lincomycin 500mg Capsule",                       "Antibiotic", "Capsules"),
    ("Vancomycin 500mg Injection",                     "Antibiotic", "Vial"),
    ("Linezolid 600mg Tablet",                         "Antibiotic", "Tablets"),
    ("Gentamicin 80mg/2ml Injection",                  "Antibiotic", "Ampoule"),
    ("Gentamicin 0.3% Eye Drops",                      "Ophthalmic", "Drops"),
    ("Amikacin 500mg Injection",                       "Antibiotic", "Vial"),
    ("Streptomycin 1g Injection",                      "Antituberculosis", "Vial"),
    ("Chloramphenicol 250mg Capsule",                  "Antibiotic", "Capsules"),
    ("Chloramphenicol 1% Eye Ointment",                "Ophthalmic", "Ointment"),
    ("Chloramphenicol 0.5% Eye Drops",                 "Ophthalmic", "Drops"),
    ("Fusidic Acid 2% Cream",                          "Antibiotic", "Cream/Gel"),
    ("Mupirocin 2% Ointment",                          "Antibiotic", "Ointment"),
    ("Neomycin + Bacitracin Ointment",                 "Antibiotic", "Ointment"),
    ("Silver Sulfadiazine 1% Cream",                   "Antibiotic", "Cream/Gel"),
    ("Sulfadiazine 500mg Tablet",                      "Antibiotic", "Tablets"),
    ("Rifaximin 200mg Tablet",                         "Antibiotic", "Tablets"),
    ("Rifaximin 550mg Tablet",                         "Antibiotic", "Tablets"),
    ("Nalidixic Acid 500mg Tablet",                    "Antibiotic", "Tablets"),

    # ───────────────── Antifungals ────────────────────────────────────────
    ("Fluconazole 50mg Capsule",                       "Antifungal", "Capsules"),
    ("Fluconazole 150mg Capsule",                      "Antifungal", "Capsules"),
    ("Fluconazole 200mg Capsule",                      "Antifungal", "Capsules"),
    ("Fluconazole 50mg/5ml Suspension",                "Antifungal", "Suspension"),
    ("Fluconazole 200mg/100ml Infusion",               "Antifungal", "IV Bag"),
    ("Itraconazole 100mg Capsule",                     "Antifungal", "Capsules"),
    ("Ketoconazole 200mg Tablet",                      "Antifungal", "Tablets"),
    ("Ketoconazole 2% Shampoo",                        "Antifungal", "Bottle"),
    ("Ketoconazole 2% Cream",                          "Antifungal", "Cream/Gel"),
    ("Clotrimazole 1% Cream",                          "Antifungal", "Cream/Gel"),
    ("Clotrimazole 100mg Pessary",                     "Antifungal", "Pessary"),
    ("Clotrimazole 500mg Pessary",                     "Antifungal", "Pessary"),
    ("Clotrimazole 1% Solution",                       "Antifungal", "Solution"),
    ("Miconazole 2% Cream",                            "Antifungal", "Cream/Gel"),
    ("Miconazole Oral Gel",                            "Antifungal", "Cream/Gel"),
    ("Terbinafine 250mg Tablet",                       "Antifungal", "Tablets"),
    ("Terbinafine 1% Cream",                           "Antifungal", "Cream/Gel"),
    ("Griseofulvin 500mg Tablet",                      "Antifungal", "Tablets"),
    ("Nystatin 100,000IU Oral Drops",                  "Antifungal", "Drops"),
    ("Nystatin 500,000IU Tablet",                      "Antifungal", "Tablets"),
    ("Amphotericin B 50mg Injection",                  "Antifungal", "Vial"),
    ("Voriconazole 200mg Tablet",                      "Antifungal", "Tablets"),
    ("Whitfield's Ointment",                           "Antifungal", "Ointment"),

    # ───────────────── Antivirals ─────────────────────────────────────────
    ("Acyclovir 200mg Tablet",                         "Antiviral", "Tablets"),
    ("Acyclovir 400mg Tablet",                         "Antiviral", "Tablets"),
    ("Acyclovir 800mg Tablet",                         "Antiviral", "Tablets"),
    ("Acyclovir 5% Cream",                             "Antiviral", "Cream/Gel"),
    ("Acyclovir 250mg Injection",                      "Antiviral", "Vial"),
    ("Valacyclovir 500mg Tablet",                      "Antiviral", "Tablets"),
    ("Valacyclovir 1g Tablet",                         "Antiviral", "Tablets"),
    ("Oseltamivir 75mg Capsule",                       "Antiviral", "Capsules"),
    ("Ganciclovir 500mg Injection",                    "Antiviral", "Vial"),

    # ───────────────── Antiretrovirals (ARVs) ─────────────────────────────
    ("Tenofovir + Lamivudine + Dolutegravir (TLD)",    "Antiretroviral (ARV)", "Tablets"),
    ("Tenofovir + Lamivudine (TDF/3TC)",               "Antiretroviral (ARV)", "Tablets"),
    ("Tenofovir + Emtricitabine (Truvada)",            "Antiretroviral (ARV)", "Tablets"),
    ("Abacavir + Lamivudine (ABC/3TC)",                "Antiretroviral (ARV)", "Tablets"),
    ("Zidovudine + Lamivudine (AZT/3TC)",              "Antiretroviral (ARV)", "Tablets"),
    ("Lopinavir + Ritonavir (Aluvia)",                 "Antiretroviral (ARV)", "Tablets"),
    ("Atazanavir 300mg + Ritonavir 100mg",             "Antiretroviral (ARV)", "Capsules"),
    ("Dolutegravir 50mg Tablet",                       "Antiretroviral (ARV)", "Tablets"),
    ("Efavirenz 600mg Tablet",                         "Antiretroviral (ARV)", "Tablets"),
    ("Nevirapine 200mg Tablet",                        "Antiretroviral (ARV)", "Tablets"),
    ("Raltegravir 400mg Tablet",                       "Antiretroviral (ARV)", "Tablets"),
    ("Darunavir 600mg Tablet",                         "Antiretroviral (ARV)", "Tablets"),
    ("Cabotegravir + Rilpivirine LA Injection",        "Antiretroviral (ARV)", "Vial"),
    ("Cotrimoxazole Prophylaxis 960mg Tablet",         "Antiretroviral (ARV)", "Tablets"),

    # ───────────────── Antiparasitic / Anthelmintic ───────────────────────
    ("Albendazole 200mg Tablet",                       "Antiparasitic", "Tablets"),
    ("Albendazole 400mg Tablet",                       "Antiparasitic", "Tablets"),
    ("Albendazole 200mg/5ml Suspension",               "Antiparasitic", "Suspension"),
    ("Mebendazole 100mg Tablet",                       "Antiparasitic", "Tablets"),
    ("Mebendazole 500mg Tablet",                       "Antiparasitic", "Tablets"),
    ("Praziquantel 600mg Tablet",                      "Antiparasitic", "Tablets"),
    ("Pyrantel Pamoate 250mg Tablet",                  "Antiparasitic", "Tablets"),
    ("Pyrantel Pamoate 250mg/5ml Suspension",          "Antiparasitic", "Suspension"),
    ("Levamisole 50mg Tablet",                         "Antiparasitic", "Tablets"),
    ("Ivermectin 3mg Tablet",                          "Antiparasitic", "Tablets"),
    ("Ivermectin 6mg Tablet",                          "Antiparasitic", "Tablets"),
    ("Ivermectin 12mg Tablet",                         "Antiparasitic", "Tablets"),
    ("Niclosamide 500mg Tablet",                       "Antiparasitic", "Tablets"),
    ("Diethylcarbamazine 100mg Tablet",                "Antiparasitic", "Tablets"),
    ("Permethrin 5% Cream",                            "Antiparasitic", "Cream/Gel"),
    ("Benzyl Benzoate 25% Lotion",                     "Antiparasitic", "Lotion"),

    # ───────────────── Antimalarials ──────────────────────────────────────
    ("Artemether + Lumefantrine 20/120mg Tablet",      "Antimalarial", "Tablets"),
    ("Artemether + Lumefantrine 80/480mg Tablet",      "Antimalarial", "Tablets"),
    ("Artemether + Lumefantrine Suspension",           "Antimalarial", "Suspension"),
    ("Dihydroartemisinin + Piperaquine Tablet",        "Antimalarial", "Tablets"),
    ("Artesunate 60mg Injection",                      "Antimalarial", "Vial"),
    ("Artesunate + Amodiaquine Tablet",                "Antimalarial", "Tablets"),
    ("Artesunate + Mefloquine Tablet",                 "Antimalarial", "Tablets"),
    ("Quinine 300mg Tablet",                           "Antimalarial", "Tablets"),
    ("Quinine 600mg/2ml Injection",                    "Antimalarial", "Ampoule"),
    ("Sulfadoxine + Pyrimethamine (Fansidar) Tablet",  "Antimalarial", "Tablets"),
    ("Primaquine 7.5mg Tablet",                        "Antimalarial", "Tablets"),
    ("Primaquine 15mg Tablet",                         "Antimalarial", "Tablets"),
    ("Mefloquine 250mg Tablet",                        "Antimalarial", "Tablets"),
    ("Doxycycline Malaria Prophylaxis 100mg",          "Antimalarial", "Capsules"),
    ("Atovaquone + Proguanil (Malarone) Tablet",       "Antimalarial", "Tablets"),

    # ───────────────── Antituberculosis ───────────────────────────────────
    ("Rifampicin + Isoniazid + Pyrazinamide + Ethambutol (RHZE)", "Antituberculosis", "Tablets"),
    ("Rifampicin + Isoniazid (RH)",                    "Antituberculosis", "Tablets"),
    ("Isoniazid 100mg Tablet",                         "Antituberculosis", "Tablets"),
    ("Isoniazid 300mg Tablet",                         "Antituberculosis", "Tablets"),
    ("Rifampicin 150mg Capsule",                       "Antituberculosis", "Capsules"),
    ("Rifampicin 300mg Capsule",                       "Antituberculosis", "Capsules"),
    ("Rifampicin 100mg/5ml Suspension",                "Antituberculosis", "Suspension"),
    ("Pyrazinamide 500mg Tablet",                      "Antituberculosis", "Tablets"),
    ("Ethambutol 400mg Tablet",                        "Antituberculosis", "Tablets"),
    ("Bedaquiline 100mg Tablet",                       "Antituberculosis", "Tablets"),
    ("Linezolid 600mg Tablet (TB)",                    "Antituberculosis", "Tablets"),
    ("Levofloxacin 250mg Tablet (TB)",                 "Antituberculosis", "Tablets"),
    ("Moxifloxacin 400mg Tablet (TB)",                 "Antituberculosis", "Tablets"),
    ("Pyridoxine 50mg Tablet (TB Adjunct)",            "Antituberculosis", "Tablets"),

    # ───────────────── Antihypertensives ──────────────────────────────────
    ("Amlodipine 5mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Amlodipine 10mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Nifedipine 10mg Capsule",                        "Antihypertensive", "Capsules"),
    ("Nifedipine 20mg SR Tablet",                      "Antihypertensive", "Tablets"),
    ("Nifedipine 30mg SR Tablet",                      "Antihypertensive", "Tablets"),
    ("Nifedipine 60mg SR Tablet",                      "Antihypertensive", "Tablets"),
    ("Felodipine 5mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Felodipine 10mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Lercanidipine 10mg Tablet",                      "Antihypertensive", "Tablets"),
    ("Lercanidipine 20mg Tablet",                      "Antihypertensive", "Tablets"),
    ("Enalapril 5mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Enalapril 10mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Enalapril 20mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Lisinopril 5mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Lisinopril 10mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Lisinopril 20mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Captopril 25mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Captopril 50mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Ramipril 2.5mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Ramipril 5mg Tablet",                            "Antihypertensive", "Tablets"),
    ("Ramipril 10mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Perindopril 4mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Perindopril 8mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Losartan 25mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Losartan 50mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Losartan 100mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Losartan + Hydrochlorothiazide 50/12.5mg",       "Antihypertensive", "Tablets"),
    ("Valsartan 80mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Valsartan 160mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Telmisartan 40mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Telmisartan 80mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Telmisartan + Hydrochlorothiazide 40/12.5mg",    "Antihypertensive", "Tablets"),
    ("Olmesartan 20mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Irbesartan 150mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Irbesartan 300mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Atenolol 25mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Atenolol 50mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Atenolol 100mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Bisoprolol 2.5mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Bisoprolol 5mg Tablet",                          "Antihypertensive", "Tablets"),
    ("Bisoprolol 10mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Carvedilol 6.25mg Tablet",                       "Antihypertensive", "Tablets"),
    ("Carvedilol 12.5mg Tablet",                       "Antihypertensive", "Tablets"),
    ("Carvedilol 25mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Metoprolol 50mg Tablet",                         "Antihypertensive", "Tablets"),
    ("Metoprolol 100mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Nebivolol 5mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Propranolol 10mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Propranolol 40mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Methyldopa 250mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Methyldopa 500mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Hydralazine 25mg Tablet",                        "Antihypertensive", "Tablets"),
    ("Hydralazine 20mg/ml Injection",                  "Antihypertensive", "Ampoule"),
    ("Clonidine 100mcg Tablet",                        "Antihypertensive", "Tablets"),
    ("Doxazosin 2mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Doxazosin 4mg Tablet",                           "Antihypertensive", "Tablets"),
    ("Prazosin 1mg Tablet",                            "Antihypertensive", "Tablets"),

    # ───────────────── Diuretics ──────────────────────────────────────────
    ("Furosemide 20mg Tablet",                         "Diuretic", "Tablets"),
    ("Furosemide 40mg Tablet",                         "Diuretic", "Tablets"),
    ("Furosemide 20mg/2ml Injection",                  "Diuretic", "Ampoule"),
    ("Hydrochlorothiazide 12.5mg Tablet",              "Diuretic", "Tablets"),
    ("Hydrochlorothiazide 25mg Tablet",                "Diuretic", "Tablets"),
    ("Indapamide 1.5mg SR Tablet",                     "Diuretic", "Tablets"),
    ("Indapamide 2.5mg Tablet",                        "Diuretic", "Tablets"),
    ("Spironolactone 25mg Tablet",                     "Diuretic", "Tablets"),
    ("Spironolactone 50mg Tablet",                     "Diuretic", "Tablets"),
    ("Spironolactone 100mg Tablet",                    "Diuretic", "Tablets"),
    ("Bumetanide 1mg Tablet",                          "Diuretic", "Tablets"),
    ("Mannitol 20% Infusion",                          "Diuretic", "IV Bag"),
    ("Acetazolamide 250mg Tablet",                     "Diuretic", "Tablets"),

    # ───────────────── Cardiovascular ─────────────────────────────────────
    ("Atorvastatin 10mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Atorvastatin 20mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Atorvastatin 40mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Atorvastatin 80mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Rosuvastatin 5mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Rosuvastatin 10mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Rosuvastatin 20mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Rosuvastatin 40mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Simvastatin 20mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Simvastatin 40mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Pravastatin 40mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Fenofibrate 145mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Fenofibrate 200mg Capsule",                      "Cardiovascular", "Capsules"),
    ("Gemfibrozil 600mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Ezetimibe 10mg Tablet",                          "Cardiovascular", "Tablets"),
    ("Clopidogrel 75mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Clopidogrel 300mg Tablet",                       "Cardiovascular", "Tablets"),
    ("Ticagrelor 90mg Tablet",                         "Cardiovascular", "Tablets"),
    ("Prasugrel 10mg Tablet",                          "Cardiovascular", "Tablets"),
    ("Isosorbide Dinitrate 5mg Tablet",                "Cardiovascular", "Tablets"),
    ("Isosorbide Mononitrate 20mg Tablet",             "Cardiovascular", "Tablets"),
    ("Isosorbide Mononitrate 60mg SR Tablet",          "Cardiovascular", "Tablets"),
    ("Glyceryl Trinitrate 0.5mg Sublingual Tablet",    "Cardiovascular", "Tablets"),
    ("Nicorandil 10mg Tablet",                         "Cardiovascular", "Tablets"),
    ("Ivabradine 5mg Tablet",                          "Cardiovascular", "Tablets"),
    ("Ivabradine 7.5mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Trimetazidine 35mg MR Tablet",                   "Cardiovascular", "Tablets"),
    ("Digoxin 0.25mg Tablet",                          "Cardiovascular", "Tablets"),
    ("Digoxin 0.5mg/2ml Injection",                    "Cardiovascular", "Ampoule"),
    ("Amiodarone 200mg Tablet",                        "Cardiovascular", "Tablets"),
    ("Amiodarone 150mg/3ml Injection",                 "Cardiovascular", "Ampoule"),
    ("Adrenaline (Epinephrine) 1mg/ml Injection",      "Emergency / IV Fluids", "Ampoule"),
    ("Atropine 0.6mg/ml Injection",                    "Emergency / IV Fluids", "Ampoule"),
    ("Dopamine 200mg/5ml Injection",                   "Cardiovascular", "Ampoule"),
    ("Dobutamine 250mg Injection",                     "Cardiovascular", "Vial"),
    ("Noradrenaline 4mg/4ml Injection",                "Emergency / IV Fluids", "Ampoule"),

    # ───────────────── Anticoagulants ─────────────────────────────────────
    ("Warfarin 1mg Tablet",                            "Anticoagulant", "Tablets"),
    ("Warfarin 2mg Tablet",                            "Anticoagulant", "Tablets"),
    ("Warfarin 5mg Tablet",                            "Anticoagulant", "Tablets"),
    ("Heparin 5,000IU/ml Injection",                   "Anticoagulant", "Vial"),
    ("Enoxaparin 40mg/0.4ml Injection",                "Anticoagulant", "Ampoule"),
    ("Enoxaparin 60mg/0.6ml Injection",                "Anticoagulant", "Ampoule"),
    ("Enoxaparin 80mg/0.8ml Injection",                "Anticoagulant", "Ampoule"),
    ("Rivaroxaban 10mg Tablet",                        "Anticoagulant", "Tablets"),
    ("Rivaroxaban 15mg Tablet",                        "Anticoagulant", "Tablets"),
    ("Rivaroxaban 20mg Tablet",                        "Anticoagulant", "Tablets"),
    ("Apixaban 2.5mg Tablet",                          "Anticoagulant", "Tablets"),
    ("Apixaban 5mg Tablet",                            "Anticoagulant", "Tablets"),
    ("Dabigatran 110mg Capsule",                       "Anticoagulant", "Capsules"),
    ("Dabigatran 150mg Capsule",                       "Anticoagulant", "Capsules"),
    ("Tranexamic Acid 500mg Tablet",                   "Anticoagulant", "Tablets"),
    ("Tranexamic Acid 500mg/5ml Injection",            "Anticoagulant", "Ampoule"),
    ("Vitamin K1 (Phytomenadione) 10mg/ml Injection",  "Anticoagulant", "Ampoule"),

    # ───────────────── Antidiabetics ──────────────────────────────────────
    ("Metformin 500mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Metformin 850mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Metformin 1000mg Tablet",                        "Antidiabetic", "Tablets"),
    ("Metformin XR 500mg Tablet",                      "Antidiabetic", "Tablets"),
    ("Metformin XR 1000mg Tablet",                     "Antidiabetic", "Tablets"),
    ("Glibenclamide 5mg Tablet",                       "Antidiabetic", "Tablets"),
    ("Gliclazide 30mg MR Tablet",                      "Antidiabetic", "Tablets"),
    ("Gliclazide 60mg MR Tablet",                      "Antidiabetic", "Tablets"),
    ("Gliclazide 80mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Glimepiride 1mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Glimepiride 2mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Glimepiride 4mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Glipizide 5mg Tablet",                           "Antidiabetic", "Tablets"),
    ("Sitagliptin 50mg Tablet",                        "Antidiabetic", "Tablets"),
    ("Sitagliptin 100mg Tablet",                       "Antidiabetic", "Tablets"),
    ("Vildagliptin 50mg Tablet",                       "Antidiabetic", "Tablets"),
    ("Linagliptin 5mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Empagliflozin 10mg Tablet",                      "Antidiabetic", "Tablets"),
    ("Empagliflozin 25mg Tablet",                      "Antidiabetic", "Tablets"),
    ("Dapagliflozin 5mg Tablet",                       "Antidiabetic", "Tablets"),
    ("Dapagliflozin 10mg Tablet",                      "Antidiabetic", "Tablets"),
    ("Pioglitazone 15mg Tablet",                       "Antidiabetic", "Tablets"),
    ("Pioglitazone 30mg Tablet",                       "Antidiabetic", "Tablets"),
    ("Repaglinide 1mg Tablet",                         "Antidiabetic", "Tablets"),
    ("Acarbose 50mg Tablet",                           "Antidiabetic", "Tablets"),
    ("Insulin Soluble (Actrapid) 100IU/ml Vial",       "Antidiabetic", "Vial"),
    ("Insulin NPH (Insulatard) 100IU/ml Vial",         "Antidiabetic", "Vial"),
    ("Insulin Mixtard 30/70 100IU/ml Vial",            "Antidiabetic", "Vial"),
    ("Insulin Glargine (Lantus) 100IU/ml Pen",         "Antidiabetic", "Vial"),
    ("Insulin Detemir (Levemir) 100IU/ml Pen",         "Antidiabetic", "Vial"),
    ("Insulin Aspart (NovoRapid) 100IU/ml Pen",        "Antidiabetic", "Vial"),
    ("Insulin Lispro (Humalog) 100IU/ml Pen",          "Antidiabetic", "Vial"),
    ("Insulin Degludec (Tresiba) 100IU/ml Pen",        "Antidiabetic", "Vial"),
    ("Liraglutide 6mg/ml Pen",                         "Antidiabetic", "Vial"),
    ("Glucagon 1mg Injection",                         "Antidiabetic", "Vial"),
    ("Insulin Syringes 1ml/100IU",                     "Medical Device / Consumable", "Box"),
    ("Glucometer Test Strips",                         "Medical Device / Consumable", "Box"),
    ("Lancets",                                        "Medical Device / Consumable", "Box"),

    # ───────────────── Antihistamines ─────────────────────────────────────
    ("Cetirizine 10mg Tablet",                         "Antihistamine", "Tablets"),
    ("Cetirizine 5mg/5ml Syrup",                       "Antihistamine", "Syrup"),
    ("Levocetirizine 5mg Tablet",                      "Antihistamine", "Tablets"),
    ("Levocetirizine 2.5mg/5ml Syrup",                 "Antihistamine", "Syrup"),
    ("Loratadine 10mg Tablet",                         "Antihistamine", "Tablets"),
    ("Loratadine 5mg/5ml Syrup",                       "Antihistamine", "Syrup"),
    ("Desloratadine 5mg Tablet",                       "Antihistamine", "Tablets"),
    ("Fexofenadine 120mg Tablet",                      "Antihistamine", "Tablets"),
    ("Fexofenadine 180mg Tablet",                      "Antihistamine", "Tablets"),
    ("Chlorpheniramine 4mg Tablet (Piriton)",          "Antihistamine", "Tablets"),
    ("Chlorpheniramine 2mg/5ml Syrup",                 "Antihistamine", "Syrup"),
    ("Chlorpheniramine 10mg/ml Injection",             "Antihistamine", "Ampoule"),
    ("Promethazine 25mg Tablet",                       "Antihistamine", "Tablets"),
    ("Promethazine 5mg/5ml Syrup",                     "Antihistamine", "Syrup"),
    ("Promethazine 25mg/ml Injection",                 "Antihistamine", "Ampoule"),
    ("Diphenhydramine 50mg Capsule",                   "Antihistamine", "Capsules"),
    ("Hydroxyzine 25mg Tablet",                        "Antihistamine", "Tablets"),

    # ───────────────── Antacids / GI ──────────────────────────────────────
    ("Omeprazole 20mg Capsule",                        "Antacid / GI", "Capsules"),
    ("Omeprazole 40mg Capsule",                        "Antacid / GI", "Capsules"),
    ("Omeprazole 40mg Injection",                      "Antacid / GI", "Vial"),
    ("Esomeprazole 20mg Tablet",                       "Antacid / GI", "Tablets"),
    ("Esomeprazole 40mg Tablet",                       "Antacid / GI", "Tablets"),
    ("Pantoprazole 20mg Tablet",                       "Antacid / GI", "Tablets"),
    ("Pantoprazole 40mg Tablet",                       "Antacid / GI", "Tablets"),
    ("Pantoprazole 40mg Injection",                    "Antacid / GI", "Vial"),
    ("Lansoprazole 30mg Capsule",                      "Antacid / GI", "Capsules"),
    ("Rabeprazole 20mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Ranitidine 150mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Ranitidine 300mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Famotidine 20mg Tablet",                         "Antacid / GI", "Tablets"),
    ("Famotidine 40mg Tablet",                         "Antacid / GI", "Tablets"),
    ("Cimetidine 200mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Magnesium Trisilicate Suspension",               "Antacid / GI", "Suspension"),
    ("Aluminium Hydroxide + Magnesium Suspension",     "Antacid / GI", "Suspension"),
    ("Aluminium Hydroxide Tablet",                     "Antacid / GI", "Tablets"),
    ("Sucralfate 1g Tablet",                           "Antacid / GI", "Tablets"),
    ("Sucralfate 1g/5ml Suspension",                   "Antacid / GI", "Suspension"),
    ("Domperidone 10mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Domperidone 1mg/ml Suspension",                  "Antacid / GI", "Suspension"),
    ("Metoclopramide 10mg Tablet",                     "Antacid / GI", "Tablets"),
    ("Metoclopramide 10mg/2ml Injection",              "Antacid / GI", "Ampoule"),
    ("Ondansetron 4mg Tablet",                         "Antacid / GI", "Tablets"),
    ("Ondansetron 8mg Tablet",                         "Antacid / GI", "Tablets"),
    ("Ondansetron 4mg/2ml Injection",                  "Antacid / GI", "Ampoule"),
    ("Ondansetron 8mg/4ml Injection",                  "Antacid / GI", "Ampoule"),
    ("Granisetron 1mg Tablet",                         "Antacid / GI", "Tablets"),
    ("Loperamide 2mg Capsule",                         "Antacid / GI", "Capsules"),
    ("ORS Sachet (Low Osmolarity)",                    "Antacid / GI", "Sachet"),
    ("Zinc Sulphate 20mg Dispersible Tablet",          "Antacid / GI", "Tablets"),
    ("Bismuth Subsalicylate Suspension",               "Antacid / GI", "Suspension"),
    ("Lactulose Solution",                             "Antacid / GI", "Solution"),
    ("Bisacodyl 5mg Tablet",                           "Antacid / GI", "Tablets"),
    ("Bisacodyl 10mg Suppository",                     "Antacid / GI", "Suppository"),
    ("Senna 7.5mg Tablet",                             "Antacid / GI", "Tablets"),
    ("Glycerin Suppository (Adult)",                   "Antacid / GI", "Suppository"),
    ("Glycerin Suppository (Paediatric)",              "Antacid / GI", "Suppository"),
    ("Mesalazine 400mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Sulfasalazine 500mg Tablet",                     "Antacid / GI", "Tablets"),
    ("Hyoscine Butylbromide 10mg Tablet",              "Antacid / GI", "Tablets"),
    ("Mebeverine 135mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Drotaverine 80mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Simethicone 40mg/ml Drops",                      "Antacid / GI", "Drops"),
    ("Simethicone 80mg Tablet",                        "Antacid / GI", "Tablets"),
    ("Activated Charcoal 250mg Capsule",               "Antacid / GI", "Capsules"),
    ("Pancreatin (Creon) 10,000 Capsule",              "Antacid / GI", "Capsules"),

    # ───────────────── Respiratory ────────────────────────────────────────
    ("Salbutamol 2mg Tablet",                          "Respiratory", "Tablets"),
    ("Salbutamol 4mg Tablet",                          "Respiratory", "Tablets"),
    ("Salbutamol 2mg/5ml Syrup",                       "Respiratory", "Syrup"),
    ("Salbutamol 100mcg Inhaler",                      "Respiratory", "Inhaler"),
    ("Salbutamol 2.5mg/2.5ml Nebule",                  "Respiratory", "Nebule"),
    ("Salbutamol 5mg/2.5ml Nebule",                    "Respiratory", "Nebule"),
    ("Ipratropium Bromide 250mcg Nebule",              "Respiratory", "Nebule"),
    ("Ipratropium + Salbutamol Nebule",                "Respiratory", "Nebule"),
    ("Beclometasone 100mcg Inhaler",                   "Respiratory", "Inhaler"),
    ("Beclometasone 250mcg Inhaler",                   "Respiratory", "Inhaler"),
    ("Budesonide 200mcg Inhaler",                      "Respiratory", "Inhaler"),
    ("Budesonide 0.5mg Nebule",                        "Respiratory", "Nebule"),
    ("Fluticasone 125mcg Inhaler",                     "Respiratory", "Inhaler"),
    ("Fluticasone + Salmeterol (Seretide) Inhaler",    "Respiratory", "Inhaler"),
    ("Budesonide + Formoterol (Symbicort) Inhaler",    "Respiratory", "Inhaler"),
    ("Tiotropium 18mcg Inhaler",                       "Respiratory", "Inhaler"),
    ("Montelukast 4mg Chewable Tablet",                "Respiratory", "Tablets"),
    ("Montelukast 5mg Chewable Tablet",                "Respiratory", "Tablets"),
    ("Montelukast 10mg Tablet",                        "Respiratory", "Tablets"),
    ("Theophylline 100mg Tablet",                      "Respiratory", "Tablets"),
    ("Aminophylline 100mg Tablet",                     "Respiratory", "Tablets"),
    ("Aminophylline 250mg/10ml Injection",             "Respiratory", "Ampoule"),
    ("Bromhexine 8mg Tablet",                          "Respiratory", "Tablets"),
    ("Bromhexine 4mg/5ml Syrup",                       "Respiratory", "Syrup"),
    ("Ambroxol 30mg Tablet",                           "Respiratory", "Tablets"),
    ("Ambroxol 30mg/5ml Syrup",                        "Respiratory", "Syrup"),
    ("Acetylcysteine 200mg Sachet",                    "Respiratory", "Sachet"),
    ("Acetylcysteine 600mg Effervescent Tablet",       "Respiratory", "Tablets"),
    ("Carbocisteine 375mg Capsule",                    "Respiratory", "Capsules"),
    ("Guaifenesin Cough Syrup",                        "Respiratory", "Syrup"),
    ("Dextromethorphan Cough Syrup",                   "Respiratory", "Syrup"),
    ("Pholcodine Linctus",                             "Respiratory", "Syrup"),
    ("Codeine + Promethazine Linctus",                 "Respiratory", "Syrup"),
    ("Pseudoephedrine 60mg Tablet",                    "Respiratory", "Tablets"),
    ("Phenylephrine 10mg Tablet",                      "Respiratory", "Tablets"),

    # ───────────────── CNS / Anticonvulsants ──────────────────────────────
    ("Diazepam 5mg Tablet",                            "Central Nervous System", "Tablets"),
    ("Diazepam 10mg/2ml Injection",                    "Central Nervous System", "Ampoule"),
    ("Diazepam 5mg Rectal Solution",                   "Central Nervous System", "Solution"),
    ("Lorazepam 1mg Tablet",                           "Central Nervous System", "Tablets"),
    ("Lorazepam 2mg Tablet",                           "Central Nervous System", "Tablets"),
    ("Midazolam 5mg/ml Injection",                     "Central Nervous System", "Ampoule"),
    ("Phenobarbital 30mg Tablet",                      "Central Nervous System", "Tablets"),
    ("Phenobarbital 60mg Tablet",                      "Central Nervous System", "Tablets"),
    ("Phenobarbital 200mg/ml Injection",               "Central Nervous System", "Ampoule"),
    ("Phenytoin 100mg Tablet",                         "Central Nervous System", "Tablets"),
    ("Phenytoin 30mg/5ml Suspension",                  "Central Nervous System", "Suspension"),
    ("Phenytoin 250mg/5ml Injection",                  "Central Nervous System", "Ampoule"),
    ("Carbamazepine 200mg Tablet",                     "Central Nervous System", "Tablets"),
    ("Carbamazepine 400mg CR Tablet",                  "Central Nervous System", "Tablets"),
    ("Carbamazepine 100mg/5ml Suspension",             "Central Nervous System", "Suspension"),
    ("Sodium Valproate 200mg Tablet",                  "Central Nervous System", "Tablets"),
    ("Sodium Valproate 500mg CR Tablet",               "Central Nervous System", "Tablets"),
    ("Sodium Valproate 200mg/5ml Syrup",               "Central Nervous System", "Syrup"),
    ("Lamotrigine 25mg Tablet",                        "Central Nervous System", "Tablets"),
    ("Lamotrigine 50mg Tablet",                        "Central Nervous System", "Tablets"),
    ("Lamotrigine 100mg Tablet",                       "Central Nervous System", "Tablets"),
    ("Levetiracetam 250mg Tablet",                     "Central Nervous System", "Tablets"),
    ("Levetiracetam 500mg Tablet",                     "Central Nervous System", "Tablets"),
    ("Levetiracetam 1000mg Tablet",                    "Central Nervous System", "Tablets"),
    ("Topiramate 25mg Tablet",                         "Central Nervous System", "Tablets"),
    ("Topiramate 50mg Tablet",                         "Central Nervous System", "Tablets"),
    ("Topiramate 100mg Tablet",                        "Central Nervous System", "Tablets"),
    ("Gabapentin 100mg Capsule",                       "Central Nervous System", "Capsules"),
    ("Gabapentin 300mg Capsule",                       "Central Nervous System", "Capsules"),
    ("Gabapentin 400mg Capsule",                       "Central Nervous System", "Capsules"),
    ("Pregabalin 75mg Capsule",                        "Central Nervous System", "Capsules"),
    ("Pregabalin 150mg Capsule",                       "Central Nervous System", "Capsules"),
    ("Pregabalin 300mg Capsule",                       "Central Nervous System", "Capsules"),

    # ───────────────── Psychiatric ────────────────────────────────────────
    ("Fluoxetine 20mg Capsule",                        "Psychiatric", "Capsules"),
    ("Sertraline 50mg Tablet",                         "Psychiatric", "Tablets"),
    ("Sertraline 100mg Tablet",                        "Psychiatric", "Tablets"),
    ("Citalopram 20mg Tablet",                         "Psychiatric", "Tablets"),
    ("Escitalopram 10mg Tablet",                       "Psychiatric", "Tablets"),
    ("Escitalopram 20mg Tablet",                       "Psychiatric", "Tablets"),
    ("Paroxetine 20mg Tablet",                         "Psychiatric", "Tablets"),
    ("Amitriptyline 10mg Tablet",                      "Psychiatric", "Tablets"),
    ("Amitriptyline 25mg Tablet",                      "Psychiatric", "Tablets"),
    ("Amitriptyline 50mg Tablet",                      "Psychiatric", "Tablets"),
    ("Imipramine 25mg Tablet",                         "Psychiatric", "Tablets"),
    ("Clomipramine 25mg Tablet",                       "Psychiatric", "Tablets"),
    ("Mirtazapine 30mg Tablet",                        "Psychiatric", "Tablets"),
    ("Venlafaxine 75mg Tablet",                        "Psychiatric", "Tablets"),
    ("Duloxetine 30mg Capsule",                        "Psychiatric", "Capsules"),
    ("Duloxetine 60mg Capsule",                        "Psychiatric", "Capsules"),
    ("Bupropion 150mg SR Tablet",                      "Psychiatric", "Tablets"),
    ("Risperidone 1mg Tablet",                         "Psychiatric", "Tablets"),
    ("Risperidone 2mg Tablet",                         "Psychiatric", "Tablets"),
    ("Risperidone 4mg Tablet",                         "Psychiatric", "Tablets"),
    ("Olanzapine 5mg Tablet",                          "Psychiatric", "Tablets"),
    ("Olanzapine 10mg Tablet",                         "Psychiatric", "Tablets"),
    ("Quetiapine 25mg Tablet",                         "Psychiatric", "Tablets"),
    ("Quetiapine 100mg Tablet",                        "Psychiatric", "Tablets"),
    ("Quetiapine 200mg Tablet",                        "Psychiatric", "Tablets"),
    ("Aripiprazole 10mg Tablet",                       "Psychiatric", "Tablets"),
    ("Haloperidol 1.5mg Tablet",                       "Psychiatric", "Tablets"),
    ("Haloperidol 5mg Tablet",                         "Psychiatric", "Tablets"),
    ("Haloperidol 5mg/ml Injection",                   "Psychiatric", "Ampoule"),
    ("Chlorpromazine 25mg Tablet",                     "Psychiatric", "Tablets"),
    ("Chlorpromazine 100mg Tablet",                    "Psychiatric", "Tablets"),
    ("Chlorpromazine 50mg/2ml Injection",              "Psychiatric", "Ampoule"),
    ("Lithium Carbonate 300mg Tablet",                 "Psychiatric", "Tablets"),
    ("Sodium Valproate (Bipolar) 500mg",               "Psychiatric", "Tablets"),
    ("Zolpidem 10mg Tablet",                           "Psychiatric", "Tablets"),
    ("Zopiclone 7.5mg Tablet",                         "Psychiatric", "Tablets"),
    ("Buspirone 10mg Tablet",                          "Psychiatric", "Tablets"),
    ("Methylphenidate 10mg Tablet",                    "Psychiatric", "Tablets"),

    # ───────────────── Hormonal ───────────────────────────────────────────
    ("Levothyroxine 25mcg Tablet",                     "Hormonal", "Tablets"),
    ("Levothyroxine 50mcg Tablet",                     "Hormonal", "Tablets"),
    ("Levothyroxine 75mcg Tablet",                     "Hormonal", "Tablets"),
    ("Levothyroxine 100mcg Tablet",                    "Hormonal", "Tablets"),
    ("Levothyroxine 125mcg Tablet",                    "Hormonal", "Tablets"),
    ("Carbimazole 5mg Tablet",                         "Hormonal", "Tablets"),
    ("Carbimazole 10mg Tablet",                        "Hormonal", "Tablets"),
    ("Propylthiouracil 50mg Tablet",                   "Hormonal", "Tablets"),
    ("Prednisolone 5mg Tablet",                        "Hormonal", "Tablets"),
    ("Prednisolone 25mg Tablet",                       "Hormonal", "Tablets"),
    ("Prednisolone 5mg/5ml Syrup",                     "Hormonal", "Syrup"),
    ("Methylprednisolone 4mg Tablet",                  "Hormonal", "Tablets"),
    ("Methylprednisolone 16mg Tablet",                 "Hormonal", "Tablets"),
    ("Methylprednisolone 40mg Injection",              "Hormonal", "Vial"),
    ("Methylprednisolone 500mg Injection",             "Hormonal", "Vial"),
    ("Methylprednisolone 1g Injection",                "Hormonal", "Vial"),
    ("Hydrocortisone 100mg Injection",                 "Hormonal", "Vial"),
    ("Hydrocortisone 1% Cream",                        "Dermatological", "Cream/Gel"),
    ("Dexamethasone 0.5mg Tablet",                     "Hormonal", "Tablets"),
    ("Dexamethasone 4mg Tablet",                       "Hormonal", "Tablets"),
    ("Dexamethasone 4mg/ml Injection",                 "Hormonal", "Ampoule"),
    ("Dexamethasone 8mg/2ml Injection",                "Hormonal", "Ampoule"),
    ("Estradiol 1mg Tablet",                           "Hormonal", "Tablets"),
    ("Estradiol 2mg Tablet",                           "Hormonal", "Tablets"),
    ("Conjugated Estrogens 0.625mg Tablet",            "Hormonal", "Tablets"),
    ("Progesterone 100mg Capsule",                     "Hormonal", "Capsules"),
    ("Progesterone 200mg Capsule",                     "Hormonal", "Capsules"),
    ("Medroxyprogesterone 5mg Tablet",                 "Hormonal", "Tablets"),
    ("Medroxyprogesterone 150mg Injection (Depo)",     "Contraceptive", "Vial"),
    ("Norethisterone 5mg Tablet",                      "Hormonal", "Tablets"),
    ("Tibolone 2.5mg Tablet",                          "Hormonal", "Tablets"),
    ("Testosterone 250mg Injection",                   "Hormonal", "Ampoule"),
    ("Bromocriptine 2.5mg Tablet",                     "Hormonal", "Tablets"),
    ("Cabergoline 0.5mg Tablet",                       "Hormonal", "Tablets"),

    # ───────────────── Contraceptives ─────────────────────────────────────
    ("Combined Oral Contraceptive (Microgynon)",       "Contraceptive", "Tablets"),
    ("Levonorgestrel + Ethinylestradiol Tablet",       "Contraceptive", "Tablets"),
    ("Norethisterone + Ethinylestradiol Tablet",       "Contraceptive", "Tablets"),
    ("Drospirenone + Ethinylestradiol (Yasmin)",       "Contraceptive", "Tablets"),
    ("Desogestrel 75mcg Tablet (Cerazette)",           "Contraceptive", "Tablets"),
    ("Levonorgestrel 1.5mg Emergency (Postinor-2)",    "Contraceptive", "Tablets"),
    ("Ulipristal Acetate 30mg Emergency",              "Contraceptive", "Tablets"),
    ("Etonogestrel Implant (Implanon NXT)",            "Contraceptive", "Piece"),
    ("Levonorgestrel Implant (Jadelle)",               "Contraceptive", "Piece"),
    ("IUD Copper T 380A",                              "Contraceptive", "Piece"),
    ("Hormonal IUD (Mirena)",                          "Contraceptive", "Piece"),
    ("Male Condoms",                                   "Contraceptive", "Box"),
    ("Female Condoms",                                 "Contraceptive", "Box"),

    # ───────────────── Vitamins / Supplements ─────────────────────────────
    ("Multivitamin Adult Tablet",                      "Vitamin / Supplement", "Tablets"),
    ("Multivitamin Paediatric Syrup",                  "Vitamin / Supplement", "Syrup"),
    ("Multivitamin Drops (Infant)",                    "Vitamin / Supplement", "Drops"),
    ("Vitamin B Complex Tablet",                       "Vitamin / Supplement", "Tablets"),
    ("Vitamin B Complex Syrup",                        "Vitamin / Supplement", "Syrup"),
    ("Vitamin B Complex Injection",                    "Vitamin / Supplement", "Ampoule"),
    ("Vitamin B12 (Cyanocobalamin) 50mcg Tablet",      "Vitamin / Supplement", "Tablets"),
    ("Vitamin B12 1000mcg Injection",                  "Vitamin / Supplement", "Ampoule"),
    ("Folic Acid 1mg Tablet",                          "Vitamin / Supplement", "Tablets"),
    ("Folic Acid 5mg Tablet",                          "Vitamin / Supplement", "Tablets"),
    ("Iron + Folate (Ferrous Sulphate) Tablet",        "Vitamin / Supplement", "Tablets"),
    ("Ferrous Sulphate 200mg Tablet",                  "Vitamin / Supplement", "Tablets"),
    ("Ferrous Fumarate 200mg Tablet",                  "Vitamin / Supplement", "Tablets"),
    ("Iron Polymaltose Syrup",                         "Vitamin / Supplement", "Syrup"),
    ("Iron Sucrose Injection",                         "Vitamin / Supplement", "Ampoule"),
    ("Vitamin C 500mg Tablet",                         "Vitamin / Supplement", "Tablets"),
    ("Vitamin C 1000mg Effervescent Tablet",           "Vitamin / Supplement", "Tablets"),
    ("Vitamin D3 1000IU Tablet",                       "Vitamin / Supplement", "Tablets"),
    ("Vitamin D3 5000IU Capsule",                      "Vitamin / Supplement", "Capsules"),
    ("Vitamin D3 50,000IU Capsule",                    "Vitamin / Supplement", "Capsules"),
    ("Calcium + Vitamin D3 Tablet",                    "Vitamin / Supplement", "Tablets"),
    ("Calcium Carbonate 500mg Tablet",                 "Vitamin / Supplement", "Tablets"),
    ("Calcium Gluconate 10% Injection",                "Vitamin / Supplement", "Ampoule"),
    ("Vitamin A 200,000IU Capsule",                    "Vitamin / Supplement", "Capsules"),
    ("Vitamin K1 1mg Injection (Neonatal)",            "Vitamin / Supplement", "Ampoule"),
    ("Vitamin E 400IU Capsule",                        "Vitamin / Supplement", "Capsules"),
    ("Magnesium Sulphate 50% Injection",               "Emergency / IV Fluids", "Ampoule"),
    ("Magnesium Citrate Sachet",                       "Vitamin / Supplement", "Sachet"),
    ("Zinc Sulphate 20mg Tablet",                      "Vitamin / Supplement", "Tablets"),
    ("Zinc Gluconate 50mg Tablet",                     "Vitamin / Supplement", "Tablets"),
    ("Omega-3 Fish Oil 1000mg Capsule",                "Vitamin / Supplement", "Capsules"),
    ("Cod Liver Oil Capsule",                          "Vitamin / Supplement", "Capsules"),
    ("Glucosamine + Chondroitin Tablet",               "Vitamin / Supplement", "Tablets"),
    ("Probiotic Capsule (Lactobacillus)",              "Vitamin / Supplement", "Capsules"),

    # ───────────────── Vaccines ───────────────────────────────────────────
    ("BCG Vaccine",                                    "Vaccine", "Vial"),
    ("OPV (Oral Polio) Drops",                         "Vaccine", "Drops"),
    ("IPV (Inactivated Polio) Injection",              "Vaccine", "Vial"),
    ("Pentavalent (DPT-HepB-Hib) Vaccine",             "Vaccine", "Vial"),
    ("Measles Vaccine",                                "Vaccine", "Vial"),
    ("MR Vaccine",                                     "Vaccine", "Vial"),
    ("Yellow Fever Vaccine",                           "Vaccine", "Vial"),
    ("Tetanus Toxoid (TT) Vaccine",                    "Vaccine", "Vial"),
    ("Td Vaccine",                                     "Vaccine", "Vial"),
    ("Rotavirus Vaccine",                              "Vaccine", "Vial"),
    ("Pneumococcal (PCV-10) Vaccine",                  "Vaccine", "Vial"),
    ("HPV Vaccine (Cervarix/Gardasil)",                "Vaccine", "Vial"),
    ("Hepatitis B Vaccine",                            "Vaccine", "Vial"),
    ("Hepatitis A Vaccine",                            "Vaccine", "Vial"),
    ("Influenza Vaccine",                              "Vaccine", "Vial"),
    ("Rabies Vaccine",                                 "Vaccine", "Vial"),
    ("Typhoid Vaccine",                                "Vaccine", "Vial"),
    ("Meningococcal Vaccine",                          "Vaccine", "Vial"),
    ("Anti-Snake Venom Polyvalent",                    "Emergency / IV Fluids", "Vial"),
    ("Anti-D Immunoglobulin",                          "Vaccine", "Vial"),

    # ───────────────── Dermatological ─────────────────────────────────────
    ("Hydrocortisone 0.5% Cream",                      "Dermatological", "Cream/Gel"),
    ("Hydrocortisone 1% Cream",                        "Dermatological", "Cream/Gel"),
    ("Betamethasone 0.05% Cream",                      "Dermatological", "Cream/Gel"),
    ("Betamethasone 0.1% Cream",                       "Dermatological", "Cream/Gel"),
    ("Clobetasol 0.05% Cream",                         "Dermatological", "Cream/Gel"),
    ("Clobetasol 0.05% Ointment",                      "Dermatological", "Ointment"),
    ("Mometasone 0.1% Cream",                          "Dermatological", "Cream/Gel"),
    ("Triamcinolone 0.1% Cream",                       "Dermatological", "Cream/Gel"),
    ("Calamine Lotion",                                "Dermatological", "Lotion"),
    ("Aqueous Cream",                                  "Dermatological", "Cream/Gel"),
    ("Emulsifying Ointment",                           "Dermatological", "Ointment"),
    ("Petroleum Jelly",                                "Dermatological", "Ointment"),
    ("Zinc Oxide Cream",                               "Dermatological", "Cream/Gel"),
    ("Salicylic Acid 6% Ointment",                     "Dermatological", "Ointment"),
    ("Benzoyl Peroxide 5% Gel",                        "Dermatological", "Cream/Gel"),
    ("Benzoyl Peroxide 10% Gel",                       "Dermatological", "Cream/Gel"),
    ("Adapalene 0.1% Gel",                             "Dermatological", "Cream/Gel"),
    ("Tretinoin 0.025% Cream",                         "Dermatological", "Cream/Gel"),
    ("Tretinoin 0.05% Cream",                          "Dermatological", "Cream/Gel"),
    ("Isotretinoin 10mg Capsule",                      "Dermatological", "Capsules"),
    ("Isotretinoin 20mg Capsule",                      "Dermatological", "Capsules"),
    ("Hydroquinone 2% Cream",                          "Dermatological", "Cream/Gel"),
    ("Hydroquinone 4% Cream",                          "Dermatological", "Cream/Gel"),
    ("Mometasone + Salicylic Acid Ointment",           "Dermatological", "Ointment"),
    ("Coal Tar Shampoo",                               "Dermatological", "Bottle"),
    ("Selenium Sulphide 2.5% Shampoo",                 "Dermatological", "Bottle"),
    ("Calcipotriol 0.005% Ointment",                   "Dermatological", "Ointment"),
    ("Tacrolimus 0.03% Ointment",                      "Dermatological", "Ointment"),
    ("Tacrolimus 0.1% Ointment",                       "Dermatological", "Ointment"),

    # ───────────────── Ophthalmic / ENT ───────────────────────────────────
    ("Timolol 0.5% Eye Drops",                         "Ophthalmic", "Drops"),
    ("Latanoprost 0.005% Eye Drops",                   "Ophthalmic", "Drops"),
    ("Brimonidine 0.2% Eye Drops",                     "Ophthalmic", "Drops"),
    ("Dorzolamide 2% Eye Drops",                       "Ophthalmic", "Drops"),
    ("Pilocarpine 2% Eye Drops",                       "Ophthalmic", "Drops"),
    ("Tropicamide 1% Eye Drops",                       "Ophthalmic", "Drops"),
    ("Cyclopentolate 1% Eye Drops",                    "Ophthalmic", "Drops"),
    ("Atropine 1% Eye Drops",                          "Ophthalmic", "Drops"),
    ("Tobramycin 0.3% Eye Drops",                      "Ophthalmic", "Drops"),
    ("Tobramycin + Dexamethasone Eye Drops",           "Ophthalmic", "Drops"),
    ("Moxifloxacin 0.5% Eye Drops",                    "Ophthalmic", "Drops"),
    ("Prednisolone Acetate 1% Eye Drops",              "Ophthalmic", "Drops"),
    ("Dexamethasone 0.1% Eye Drops",                   "Ophthalmic", "Drops"),
    ("Sodium Cromoglicate 2% Eye Drops",               "Ophthalmic", "Drops"),
    ("Olopatadine 0.1% Eye Drops",                     "Ophthalmic", "Drops"),
    ("Carboxymethylcellulose Eye Drops",               "Ophthalmic", "Drops"),
    ("Hypromellose Eye Drops",                         "Ophthalmic", "Drops"),
    ("Fluorescein 1% Eye Drops",                       "Ophthalmic", "Drops"),
    ("Ofloxacin Ear Drops",                            "ENT (Ear/Nose/Throat)", "Drops"),
    ("Ciprofloxacin + Hydrocortisone Ear Drops",       "ENT (Ear/Nose/Throat)", "Drops"),
    ("Polymyxin + Neomycin Ear Drops",                 "ENT (Ear/Nose/Throat)", "Drops"),
    ("Hydrogen Peroxide 3% Ear Drops",                 "ENT (Ear/Nose/Throat)", "Drops"),
    ("Olive Oil Ear Drops",                            "ENT (Ear/Nose/Throat)", "Drops"),
    ("Saline Nasal Spray",                             "ENT (Ear/Nose/Throat)", "Bottle"),
    ("Xylometazoline 0.05% Nasal Drops (Paediatric)",  "ENT (Ear/Nose/Throat)", "Drops"),
    ("Xylometazoline 0.1% Nasal Spray",                "ENT (Ear/Nose/Throat)", "Bottle"),
    ("Oxymetazoline Nasal Spray",                      "ENT (Ear/Nose/Throat)", "Bottle"),
    ("Mometasone Nasal Spray",                         "ENT (Ear/Nose/Throat)", "Bottle"),
    ("Fluticasone Nasal Spray",                        "ENT (Ear/Nose/Throat)", "Bottle"),
    ("Beclometasone Nasal Spray",                      "ENT (Ear/Nose/Throat)", "Bottle"),
    ("Lozenges (Strepsils/Difflam)",                   "ENT (Ear/Nose/Throat)", "Box"),

    # ───────────────── Emergency / IV Fluids ──────────────────────────────
    ("Normal Saline 0.9% 500ml Infusion",              "Emergency / IV Fluids", "IV Bag"),
    ("Normal Saline 0.9% 1000ml Infusion",             "Emergency / IV Fluids", "IV Bag"),
    ("Normal Saline 0.9% 100ml Infusion",              "Emergency / IV Fluids", "IV Bag"),
    ("Dextrose 5% 500ml Infusion",                     "Emergency / IV Fluids", "IV Bag"),
    ("Dextrose 5% 1000ml Infusion",                    "Emergency / IV Fluids", "IV Bag"),
    ("Dextrose 10% 500ml Infusion",                    "Emergency / IV Fluids", "IV Bag"),
    ("Dextrose 50% 50ml Injection",                    "Emergency / IV Fluids", "Vial"),
    ("Ringer's Lactate 500ml Infusion",                "Emergency / IV Fluids", "IV Bag"),
    ("Ringer's Lactate 1000ml Infusion",               "Emergency / IV Fluids", "IV Bag"),
    ("Hartmann's Solution 500ml",                      "Emergency / IV Fluids", "IV Bag"),
    ("Dextrose Saline 5%/0.9% 500ml",                  "Emergency / IV Fluids", "IV Bag"),
    ("Sodium Bicarbonate 8.4% Injection",              "Emergency / IV Fluids", "Ampoule"),
    ("Potassium Chloride 15% Injection",               "Emergency / IV Fluids", "Ampoule"),
    ("Calcium Gluconate 10% Injection",                "Emergency / IV Fluids", "Ampoule"),
    ("Magnesium Sulphate 50% Injection",               "Emergency / IV Fluids", "Ampoule"),
    ("Naloxone 0.4mg/ml Injection",                    "Emergency / IV Fluids", "Ampoule"),
    ("Flumazenil 0.5mg/5ml Injection",                 "Emergency / IV Fluids", "Ampoule"),
    ("Adrenaline Auto-Injector (EpiPen)",              "Emergency / IV Fluids", "Piece"),
    ("Activated Charcoal 50g Suspension",              "Emergency / IV Fluids", "Bottle"),
    ("Hydroxyethyl Starch 6% Infusion",                "Emergency / IV Fluids", "IV Bag"),
    ("Gelatin (Gelofusine) 500ml",                     "Emergency / IV Fluids", "IV Bag"),
    ("Mannitol 20% 500ml Infusion",                    "Emergency / IV Fluids", "IV Bag"),
    ("Aminoacid Infusion (Aminoven)",                  "Emergency / IV Fluids", "IV Bag"),

    # ───────────────── Anaesthetics / Muscle Relaxants ────────────────────
    ("Lidocaine 1% Injection",                         "Anaesthetic", "Ampoule"),
    ("Lidocaine 2% Injection",                         "Anaesthetic", "Ampoule"),
    ("Lidocaine 2% Gel",                               "Anaesthetic", "Cream/Gel"),
    ("Lidocaine + Adrenaline Injection",               "Anaesthetic", "Ampoule"),
    ("Bupivacaine 0.5% Injection",                     "Anaesthetic", "Ampoule"),
    ("Bupivacaine Heavy 0.5% Injection",               "Anaesthetic", "Ampoule"),
    ("EMLA Cream (Lidocaine + Prilocaine)",            "Anaesthetic", "Cream/Gel"),
    ("Ketamine 50mg/ml Injection",                     "Anaesthetic", "Vial"),
    ("Propofol 1% Injection",                          "Anaesthetic", "Vial"),
    ("Thiopental Sodium 500mg Injection",              "Anaesthetic", "Vial"),
    ("Suxamethonium 50mg/ml Injection",                "Muscle Relaxant", "Ampoule"),
    ("Atracurium 25mg/2.5ml Injection",                "Muscle Relaxant", "Ampoule"),
    ("Vecuronium 4mg Injection",                       "Muscle Relaxant", "Vial"),
    ("Rocuronium 50mg/5ml Injection",                  "Muscle Relaxant", "Ampoule"),
    ("Neostigmine 2.5mg/ml Injection",                 "Muscle Relaxant", "Ampoule"),
    ("Baclofen 10mg Tablet",                           "Muscle Relaxant", "Tablets"),
    ("Tizanidine 2mg Tablet",                          "Muscle Relaxant", "Tablets"),
    ("Tizanidine 4mg Tablet",                          "Muscle Relaxant", "Tablets"),
    ("Cyclobenzaprine 10mg Tablet",                    "Muscle Relaxant", "Tablets"),
    ("Methocarbamol 500mg Tablet",                     "Muscle Relaxant", "Tablets"),
    ("Diazepam (Spasm) 5mg Tablet",                    "Muscle Relaxant", "Tablets"),

    # ───────────────── Urology / Sexual Health ────────────────────────────
    ("Tamsulosin 0.4mg Capsule",                       "Urology", "Capsules"),
    ("Finasteride 5mg Tablet",                         "Urology", "Tablets"),
    ("Dutasteride 0.5mg Capsule",                      "Urology", "Capsules"),
    ("Sildenafil 25mg Tablet",                         "Urology", "Tablets"),
    ("Sildenafil 50mg Tablet",                         "Urology", "Tablets"),
    ("Sildenafil 100mg Tablet",                        "Urology", "Tablets"),
    ("Tadalafil 5mg Tablet",                           "Urology", "Tablets"),
    ("Tadalafil 20mg Tablet",                          "Urology", "Tablets"),
    ("Vardenafil 10mg Tablet",                         "Urology", "Tablets"),
    ("Solifenacin 5mg Tablet",                         "Urology", "Tablets"),
    ("Oxybutynin 5mg Tablet",                          "Urology", "Tablets"),
    ("Tolterodine 2mg Tablet",                         "Urology", "Tablets"),
    ("Desmopressin 0.1mg Tablet",                      "Urology", "Tablets"),
    ("Phenazopyridine 100mg Tablet",                   "Urology", "Tablets"),

    # ───────────────── Oncology (commonly stocked) ────────────────────────
    ("Tamoxifen 20mg Tablet",                          "Oncology", "Tablets"),
    ("Letrozole 2.5mg Tablet",                         "Oncology", "Tablets"),
    ("Anastrozole 1mg Tablet",                         "Oncology", "Tablets"),
    ("Methotrexate 2.5mg Tablet",                      "Oncology", "Tablets"),
    ("Methotrexate 50mg/2ml Injection",                "Oncology", "Vial"),
    ("Hydroxyurea 500mg Capsule",                      "Oncology", "Capsules"),
    ("Imatinib 100mg Tablet",                          "Oncology", "Tablets"),
    ("Imatinib 400mg Tablet",                          "Oncology", "Tablets"),
    ("Capecitabine 500mg Tablet",                      "Oncology", "Tablets"),
    ("Cyclophosphamide 50mg Tablet",                   "Oncology", "Tablets"),
    ("Allopurinol 100mg Tablet",                       "Oncology", "Tablets"),
    ("Allopurinol 300mg Tablet",                       "Oncology", "Tablets"),
    ("Febuxostat 40mg Tablet",                         "Oncology", "Tablets"),
    ("Colchicine 0.5mg Tablet",                        "Oncology", "Tablets"),

    # ───────────────── Nutrition / Infant Formula ─────────────────────────
    ("F-75 Therapeutic Milk",                          "Nutrition / Infant Formula", "Sachet"),
    ("F-100 Therapeutic Milk",                         "Nutrition / Infant Formula", "Sachet"),
    ("RUTF (Plumpy'Nut) Sachet",                       "Nutrition / Infant Formula", "Sachet"),
    ("Infant Formula Stage 1",                         "Nutrition / Infant Formula", "Bottle"),
    ("Infant Formula Stage 2",                         "Nutrition / Infant Formula", "Bottle"),
    ("Follow-on Formula Stage 3",                      "Nutrition / Infant Formula", "Bottle"),
    ("Soy-based Infant Formula",                       "Nutrition / Infant Formula", "Bottle"),
    ("Lactose-free Infant Formula",                    "Nutrition / Infant Formula", "Bottle"),
    ("Adult Nutritional Supplement (Ensure)",          "Nutrition / Infant Formula", "Bottle"),
    ("Diabetic Nutritional Supplement (Glucerna)",     "Nutrition / Infant Formula", "Bottle"),

    # ───────────────── First Aid / Wound Care ─────────────────────────────
    ("Povidone Iodine 10% Solution",                   "First Aid / Wound Care", "Bottle"),
    ("Povidone Iodine 7.5% Scrub",                     "First Aid / Wound Care", "Bottle"),
    ("Chlorhexidine 4% Solution",                      "First Aid / Wound Care", "Bottle"),
    ("Chlorhexidine 0.05% Solution",                   "First Aid / Wound Care", "Bottle"),
    ("Hydrogen Peroxide 3% Solution",                  "First Aid / Wound Care", "Bottle"),
    ("Methylated Spirit",                              "First Aid / Wound Care", "Bottle"),
    ("Surgical Spirit",                                "First Aid / Wound Care", "Bottle"),
    ("Savlon Antiseptic Cream",                        "First Aid / Wound Care", "Cream/Gel"),
    ("Dettol Antiseptic Liquid",                       "First Aid / Wound Care", "Bottle"),
    ("Hand Sanitizer 70% Alcohol",                     "First Aid / Wound Care", "Bottle"),
    ("Cotton Wool 100g",                               "Medical Device / Consumable", "Roll"),
    ("Cotton Wool 25g",                                "Medical Device / Consumable", "Roll"),
    ("Gauze Swabs 4x4 (Sterile)",                      "Medical Device / Consumable", "Box"),
    ("Bandage Crepe 4 Inch",                           "Medical Device / Consumable", "Roll"),
    ("Bandage Crepe 6 Inch",                           "Medical Device / Consumable", "Roll"),
    ("Plaster of Paris Bandage",                       "Medical Device / Consumable", "Roll"),
    ("Adhesive Plaster (Elastoplast)",                 "Medical Device / Consumable", "Roll"),
    ("Micropore Tape 1 Inch",                          "Medical Device / Consumable", "Roll"),
    ("Surgical Tape 2 Inch",                           "Medical Device / Consumable", "Roll"),
    ("Plasters (Band-Aid) Assorted",                   "Medical Device / Consumable", "Box"),

    # ───────────────── Medical Devices / Consumables ──────────────────────
    ("Disposable Syringe 2ml",                         "Medical Device / Consumable", "Box"),
    ("Disposable Syringe 5ml",                         "Medical Device / Consumable", "Box"),
    ("Disposable Syringe 10ml",                        "Medical Device / Consumable", "Box"),
    ("Disposable Syringe 20ml",                        "Medical Device / Consumable", "Box"),
    ("Hypodermic Needle 21G",                          "Medical Device / Consumable", "Box"),
    ("Hypodermic Needle 23G",                          "Medical Device / Consumable", "Box"),
    ("Cannula 18G",                                    "Medical Device / Consumable", "Box"),
    ("Cannula 20G",                                    "Medical Device / Consumable", "Box"),
    ("Cannula 22G",                                    "Medical Device / Consumable", "Box"),
    ("Cannula 24G (Paediatric)",                       "Medical Device / Consumable", "Box"),
    ("IV Giving Set",                                  "Medical Device / Consumable", "Piece"),
    ("Blood Giving Set",                               "Medical Device / Consumable", "Piece"),
    ("Foley Catheter 12Fr",                            "Medical Device / Consumable", "Piece"),
    ("Foley Catheter 14Fr",                            "Medical Device / Consumable", "Piece"),
    ("Foley Catheter 16Fr",                            "Medical Device / Consumable", "Piece"),
    ("Urine Bag 2L",                                   "Medical Device / Consumable", "Piece"),
    ("NG Tube 16Fr",                                   "Medical Device / Consumable", "Piece"),
    ("Examination Gloves (S/M/L) Box",                 "Medical Device / Consumable", "Box"),
    ("Surgical Gloves Sterile (Pair)",                 "Medical Device / Consumable", "Box"),
    ("Surgical Mask 3-Ply",                            "Medical Device / Consumable", "Box"),
    ("N95 Respirator Mask",                            "Medical Device / Consumable", "Piece"),
    ("Face Shield",                                    "Medical Device / Consumable", "Piece"),
    ("Disposable Gown",                                "Medical Device / Consumable", "Piece"),
    ("Thermometer Digital",                            "Medical Device / Consumable", "Piece"),
    ("Thermometer Infrared",                           "Medical Device / Consumable", "Piece"),
    ("Pulse Oximeter (Finger)",                        "Medical Device / Consumable", "Piece"),
    ("Sphygmomanometer (BP Machine)",                  "Medical Device / Consumable", "Piece"),
    ("Stethoscope",                                    "Medical Device / Consumable", "Piece"),
    ("Glucometer Device",                              "Medical Device / Consumable", "Piece"),
    ("Pregnancy Test Strip",                           "Medical Device / Consumable", "Piece"),
    ("Malaria Rapid Test Kit",                         "Medical Device / Consumable", "Piece"),
    ("HIV Rapid Test Kit",                             "Medical Device / Consumable", "Piece"),
    ("COVID-19 Antigen Test Kit",                      "Medical Device / Consumable", "Piece"),
    ("Sanitary Pads (Pack)",                           "Medical Device / Consumable", "Box"),
    ("Adult Diapers (Pack)",                           "Medical Device / Consumable", "Box"),
    ("Baby Diapers (Pack)",                            "Medical Device / Consumable", "Box"),

    # ───────────────── Herbal / Traditional ───────────────────────────────
    ("Aloe Vera Gel",                                  "Herbal / Traditional", "Cream/Gel"),
    ("Eucalyptus Oil",                                 "Herbal / Traditional", "Bottle"),
    ("Tea Tree Oil",                                   "Herbal / Traditional", "Bottle"),
    ("Ginger Capsule",                                 "Herbal / Traditional", "Capsules"),
    ("Garlic Capsule",                                 "Herbal / Traditional", "Capsules"),
    ("Turmeric (Curcumin) Capsule",                    "Herbal / Traditional", "Capsules"),
    ("Echinacea Capsule",                              "Herbal / Traditional", "Capsules"),
    ("Moringa Leaf Powder",                            "Herbal / Traditional", "Powder"),
    ("Honey (Pure) 500g",                              "Herbal / Traditional", "Bottle"),
    ("Apple Cider Vinegar",                            "Herbal / Traditional", "Bottle"),
]
# fmt: on


class Command(BaseCommand):
    help = (
        "Seed MedicationStock for the current tenant with the comprehensive "
        "Kenyan-market medication catalog. Prices and quantities are seeded "
        "to ZERO — staff must add their own pricing and stock batches."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--skip-existing",
            action="store_true",
            default=False,
            help="Skip medications that already have a stock entry.",
        )
        parser.add_argument(
            "--reset",
            action="store_true",
            default=False,
            help="Delete ALL existing stock entries (and batches) before seeding.",
        )

    def handle(self, *args, **options):
        skip_existing = options["skip_existing"]
        reset = options["reset"]

        if reset:
            batch_del, _ = StockBatch.objects.all().delete()
            if batch_del:
                self.stdout.write(self.style.WARNING(f"Deleted {batch_del} existing batches."))
            deleted, _ = MedicationStock.objects.all().delete()
            self.stdout.write(self.style.WARNING(f"Deleted {deleted} existing stock entries."))

        # ── Ensure Categories exist ──────────────────────────────────────
        category_map = {}
        for name in CATEGORY_DEFS:
            cat, _ = Category.objects.get_or_create(name=name)
            category_map[name] = cat

        # ── Ensure Units exist ───────────────────────────────────────────
        unit_map = {}
        for name, abbr in UNIT_DEFS:
            unit, _ = Unit.objects.get_or_create(
                name=name,
                defaults={"abbreviation": abbr},
            )
            unit_map[name] = unit

        # ── Seed stock (zero prices, zero quantities) ────────────────────
        ZERO = Decimal("0")
        created = skipped = updated = 0

        # Use a set to dedupe in case the catalog accidentally repeats a name
        seen = set()
        for med_name, cat_name, unit_name in STOCK_DATA:
            if med_name in seen:
                continue
            seen.add(med_name)

            category = category_map.get(cat_name)
            unit = unit_map.get(unit_name)

            existing = MedicationStock.objects.filter(
                medication_name=med_name,
            ).first()

            if existing:
                if skip_existing:
                    skipped += 1
                    continue
                fields_to_update = []
                if existing.selling_price != ZERO:
                    existing.selling_price = ZERO
                    fields_to_update.append("selling_price")
                if existing.cost_price != ZERO:
                    existing.cost_price = ZERO
                    fields_to_update.append("cost_price")
                if existing.reorder_level != 0:
                    existing.reorder_level = 0
                    fields_to_update.append("reorder_level")
                if existing.reorder_quantity != 0:
                    existing.reorder_quantity = 0
                    fields_to_update.append("reorder_quantity")
                if category and existing.category_id != category.id:
                    existing.category = category
                    fields_to_update.append("category")
                if unit and existing.unit_id != unit.id:
                    existing.unit = unit
                    fields_to_update.append("unit")
                if fields_to_update:
                    existing.save(update_fields=fields_to_update)
                    updated += 1
                else:
                    skipped += 1
            else:
                MedicationStock.objects.create(
                    medication_name=med_name,
                    category=category,
                    unit=unit,
                    selling_price=ZERO,
                    cost_price=ZERO,
                    reorder_level=0,
                    reorder_quantity=0,
                    is_active=True,
                )
                created += 1

        total = MedicationStock.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f"\nPharmacy Stock Seed Complete (Kenyan market catalog)\n"
            f"  Catalog items: {len(seen)}\n"
            f"  Created      : {created}\n"
            f"  Updated      : {updated}\n"
            f"  Skipped      : {skipped}\n"
            f"  Total in DB  : {total}\n"
            f"\n  Note: prices and quantities are 0. Update via the\n"
            f"  Bulk Edit screen and add stock batches as deliveries arrive."
        ))
