# Generated by Django 6.0.4 on 2026-05-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('drug', 'Drug / Medication'), ('food', 'Food'), ('environmental', 'Environmental'), ('insect', 'Insect / Venom'), ('latex', 'Latex'), ('contrast', 'Contrast / Dye'), ('chemical', 'Chemical'), ('other', 'Other')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('common_symptoms', models.TextField(blank=True, help_text='Comma-separated list of common symptoms')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Allergy',
                'verbose_name_plural': 'Allergies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChronicCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('category', models.CharField(choices=[('cardiovascular', 'Cardiovascular'), ('endocrine', 'Endocrine / Metabolic'), ('respiratory', 'Respiratory'), ('neurological', 'Neurological'), ('musculoskeletal', 'Musculoskeletal'), ('gastrointestinal', 'Gastrointestinal'), ('renal', 'Renal / Urological'), ('hematological', 'Hematological'), ('immunological', 'Immunological / Infectious'), ('mental_health', 'Mental Health'), ('oncological', 'Oncological'), ('dermatological', 'Dermatological'), ('ophthalmological', 'Ophthalmological'), ('other', 'Other')], db_index=True, max_length=20)),
                ('icd_code', models.CharField(blank=True, db_index=True, help_text='ICD-10 code, e.g. E11 for Type 2 Diabetes', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chronic Condition',
                'verbose_name_plural': 'Chronic Conditions',
                'ordering': ['category', 'name'],
            },
        ),
    ]
