# Generated by Django 6.0.4 on 2026-05-07 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_medicationstock_abbreviation'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='Cached display name (auto-filled from stock or entered manually).', max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, help_text='Supplier purchase price per unit.', max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, help_text='Recommended selling price per unit.', max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, help_text='Typical supply quantity per order.', max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(blank=True, help_text='Linked stock item; null for manually-entered items.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_items', to='inventory.medicationstock')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['item_name'],
            },
        ),
    ]
