# Generated by Django 6.0.4 on 2026-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('actor_email', models.CharField(blank=True, db_index=True, max_length=255)),
                ('actor_role', models.CharField(blank=True, max_length=64)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('print', 'Print'), ('config', 'Config Change'), ('action', 'Custom Action')], db_index=True, max_length=16)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('notice', 'Notice'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='info', max_length=16)),
                ('object_type', models.CharField(blank=True, db_index=True, max_length=120)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, help_text='Human-readable summary of the event.', max_length=255)),
                ('method', models.CharField(blank=True, db_index=True, max_length=10)),
                ('path', models.CharField(blank=True, db_index=True, max_length=512)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload_diff', models.JSONField(blank=True, default=dict, help_text='Before/after snapshot or redacted request body.')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Free-form context (session id, branch, tenant module...).')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_id', models.CharField(blank=True, db_index=True, help_text='Correlation id linking related events.', max_length=64)),
            ],
            options={
                'verbose_name': 'Audit event',
                'verbose_name_plural': 'Audit events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__0e78a5_idx'), models.Index(fields=['actor_user_id', '-created_at'], name='audit_audit_actor_u_65f79c_idx'), models.Index(fields=['-created_at', 'action'], name='audit_audit_created_8a476e_idx'), models.Index(fields=['severity', '-created_at'], name='audit_audit_severit_17e6b2_idx')],
            },
        ),
    ]
