# Generated by Django 6.0.4 on 2026-05-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_instrument_referringfacility_reporttemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homesamplevisit',
            name='address_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='homesamplevisit',
            name='address_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='homesamplevisit',
            name='address_place_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
