# Generated by Django 6.0.4 on 2026-05-11 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_homesamplevisit_address_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReagent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50)),
                ('catalog_no', models.CharField(blank=True, max_length=100)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('category', models.CharField(choices=[('reagent', 'Reagent'), ('control', 'Control'), ('calibrator', 'Calibrator'), ('stain', 'Stain / Dye'), ('kit', 'Test Kit'), ('consumable', 'Consumable'), ('buffer', 'Buffer / Diluent'), ('media', 'Culture Media'), ('other', 'Other')], default='reagent', max_length=20)),
                ('storage', models.CharField(choices=[('room', 'Room (15-25°C)'), ('fridge', 'Refrigerated (2-8°C)'), ('freezer', 'Frozen (-20°C)'), ('ultra', 'Ultra-low (-80°C)'), ('dark', 'Protect from light'), ('other', 'Other')], default='room', max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, help_text='e.g., mL, vial, test, bottle', max_length=30)),
                ('pack_size', models.CharField(blank=True, help_text='e.g., 100 tests, 500 mL', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, help_text='Trigger low-stock alert at this on-hand quantity', max_digits=12)),
                ('reorder_qty', models.DecimalField(decimal_places=2, default=0, help_text='Suggested replenish quantity', max_digits=12)),
                ('msds_url', models.URLField(blank=True, help_text='Material Safety Data Sheet')),
                ('hazard_class', models.CharField(blank=True, max_length=80)),
                ('is_controlled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagents', to='lab.instrument')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReagentLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(db_index=True, max_length=100)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('opened_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('open_stability_days', models.PositiveIntegerField(blank=True, help_text='Days valid after opening (overrides expiry if sooner)', null=True)),
                ('initial_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('active', 'Active'), ('quarantine', 'Quarantine'), ('expired', 'Expired'), ('discarded', 'Discarded'), ('depleted', 'Depleted')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='lab.labreagent')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_lots_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['expiry_date', 'received_date'],
            },
        ),
        migrations.CreateModel(
            name='ReagentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_type', models.CharField(choices=[('receive', 'Receive'), ('consume', 'Consume'), ('adjust', 'Adjust'), ('discard', 'Discard'), ('transfer', 'Transfer'), ('return', 'Return')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Positive for receive / negative for consume', max_digits=14)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('reference', models.CharField(blank=True, help_text='e.g., test order #, requisition, PO number', max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='lab.reagentlot')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reagent_txns_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
