# Generated by Django 6.0.4 on 2026-04-09 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esi_level', models.IntegerField(choices=[(1, 'Level 1 - Resuscitation'), (2, 'Level 2 - Emergent'), (3, 'Level 3 - Urgent'), (4, 'Level 4 - Less Urgent'), (5, 'Level 5 - Non-Urgent')])),
                ('chief_complaint', models.TextField()),
                ('vital_signs', models.JSONField(default=dict, help_text='BP, temp, pulse, resp rate, O2 sat, weight')),
                ('arrival_mode', models.CharField(choices=[('walk_in', 'Walk-in'), ('ambulance', 'Ambulance'), ('referral', 'Referral'), ('police', 'Police')], default='walk_in', max_length=20)),
                ('pain_scale', models.IntegerField(default=0, help_text='0-10 scale')),
                ('notes', models.TextField(blank=True)),
                ('triage_time', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages_performed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triages', to='patients.patient')),
            ],
            options={
                'ordering': ['esi_level', 'triage_time'],
            },
        ),
    ]
