# Generated by Django 6.0.4 on 2026-08-03 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='alcohol_use',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='allergies_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triage',
            name='allergies_updated',
            field=models.JSONField(blank=True, default=list, help_text='Confirmed/updated allergies list'),
        ),
        migrations.AddField(
            model_name='triage',
            name='avpu',
            field=models.CharField(choices=[('alert', 'Alert'), ('voice', 'Responds to Voice'), ('pain', 'Responds to Pain'), ('unresponsive', 'Unresponsive')], default='alert', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='bmi',
            field=models.FloatField(blank=True, help_text='Auto-calculated from height/weight', null=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='esi_override_reason',
            field=models.TextField(blank=True, help_text='Reason if nurse overrode system suggestion'),
        ),
        migrations.AddField(
            model_name='triage',
            name='fall_risk',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='infection_risk',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='triage',
            name='interventions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='medication_history',
            field=models.JSONField(blank=True, default=list, help_text='Confirmed medication list'),
        ),
        migrations.AddField(
            model_name='triage',
            name='mental_health_screen',
            field=models.JSONField(blank=True, default=dict, help_text='Mental health screening notes'),
        ),
        migrations.AddField(
            model_name='triage',
            name='news2_score',
            field=models.IntegerField(default=0, help_text='Auto-calculated NEWS2 score'),
        ),
        migrations.AddField(
            model_name='triage',
            name='nursing_assessment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='nutrition_screen',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='triage',
            name='patient_education',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='triage',
            name='pregnancy_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='smoking_status',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='substance_use',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='triage',
            name='suggested_esi',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1 - Resuscitation'), (2, 'Level 2 - Emergent'), (3, 'Level 3 - Urgent'), (4, 'Level 4 - Less Urgent'), (5, 'Level 5 - Non-Urgent')], help_text='System-suggested ESI based on NEWS2', null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='chief_complaint',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='esi_level',
            field=models.IntegerField(blank=True, choices=[(1, 'Level 1 - Resuscitation'), (2, 'Level 2 - Emergent'), (3, 'Level 3 - Urgent'), (4, 'Level 4 - Less Urgent'), (5, 'Level 5 - Non-Urgent')], null=True),
        ),
        migrations.AlterField(
            model_name='triage',
            name='vital_signs',
            field=models.JSONField(default=dict, help_text='BP, temp, pulse, resp rate, O2 sat, weight, height, blood_sugar'),
        ),
    ]
